/**
 * Cyberwave API
 * Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/AlertSchema.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

AlertSchema::AlertSchema()
{
    m_Uuid = utility::conversions::to_string_t("");
    m_UuidIsSet = false;
    m_Name = utility::conversions::to_string_t("");
    m_NameIsSet = false;
    m_Description = utility::conversions::to_string_t("");
    m_DescriptionIsSet = false;
    m_Alert_type = utility::conversions::to_string_t("");
    m_Alert_typeIsSet = false;
    m_Severity = utility::conversions::to_string_t("");
    m_SeverityIsSet = false;
    m_Status = utility::conversions::to_string_t("");
    m_StatusIsSet = false;
    m_Source_type = utility::conversions::to_string_t("");
    m_Source_typeIsSet = false;
    m_Category = utility::conversions::to_string_t("");
    m_CategoryIsSet = false;
    m_Workspace_uuid = utility::conversions::to_string_t("");
    m_Workspace_uuidIsSet = false;
    m_Created_at = utility::datetime();
    m_Created_atIsSet = false;
    m_Updated_at = utility::datetime();
    m_Updated_atIsSet = false;
    m_Dedupe_count = 0;
    m_Dedupe_countIsSet = false;
}

AlertSchema::~AlertSchema()
{
}

void AlertSchema::validate()
{
    // TODO: implement validation
}

web::json::value AlertSchema::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_UuidIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("uuid"))] = ModelBase::toJson(m_Uuid);
    }
    if(m_NameIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("name"))] = ModelBase::toJson(m_Name);
    }
    if(m_DescriptionIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("description"))] = ModelBase::toJson(m_Description);
    }
    if(m_Media.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("media"))] = ModelBase::toJson(m_Media.get());
    }
    if(m_Alert_typeIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("alert_type"))] = ModelBase::toJson(m_Alert_type);
    }
    if(m_SeverityIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("severity"))] = ModelBase::toJson(m_Severity);
    }
    if(m_StatusIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("status"))] = ModelBase::toJson(m_Status);
    }
    if(m_Source_typeIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("source_type"))] = ModelBase::toJson(m_Source_type);
    }
    if(m_CategoryIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("category"))] = ModelBase::toJson(m_Category);
    }
    if(m_Twin_uuid.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("twin_uuid"))] = ModelBase::toJson(m_Twin_uuid.get());
    }
    if(m_Environment_uuid.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("environment_uuid"))] = ModelBase::toJson(m_Environment_uuid.get());
    }
    if(m_Workflow_uuid.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("workflow_uuid"))] = ModelBase::toJson(m_Workflow_uuid.get());
    }
    if(m_Workspace_uuidIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("workspace_uuid"))] = ModelBase::toJson(m_Workspace_uuid);
    }
    if(m_Created_by_uuid.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("created_by_uuid"))] = ModelBase::toJson(m_Created_by_uuid.get());
    }
    if(m_Created_atIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("created_at"))] = ModelBase::toJson(m_Created_at);
    }
    if(m_Updated_atIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("updated_at"))] = ModelBase::toJson(m_Updated_at);
    }
    if(m_Resolved_at.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("resolved_at"))] = ModelBase::toJson(m_Resolved_at.get());
    }
    if(m_Last_seen_at.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("last_seen_at"))] = ModelBase::toJson(m_Last_seen_at.get());
    }
    if(m_Dedupe_countIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("dedupe_count"))] = ModelBase::toJson(m_Dedupe_count);
    }
    if(m_Metadata.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("metadata"))] = ModelBase::toJson(m_Metadata.get());
    }

    return val;
}

bool AlertSchema::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("uuid"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("uuid")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setUuid;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUuid);
            setUuid(refVal_setUuid);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setName);
            setName(refVal_setName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("description"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("description")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setDescription;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDescription);
            setDescription(refVal_setDescription);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("media"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("media")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setMedia;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMedia);
            setMedia(refVal_setMedia);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("alert_type"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("alert_type")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setAlertType;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAlertType);
            setAlertType(refVal_setAlertType);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("severity"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("severity")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setSeverity;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSeverity);
            setSeverity(refVal_setSeverity);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("status")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setStatus;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStatus);
            setStatus(refVal_setStatus);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("source_type"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("source_type")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setSourceType;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSourceType);
            setSourceType(refVal_setSourceType);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("category"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("category")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCategory;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCategory);
            setCategory(refVal_setCategory);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("twin_uuid"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("twin_uuid")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setTwinUuid;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTwinUuid);
            setTwinUuid(refVal_setTwinUuid);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("environment_uuid"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("environment_uuid")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setEnvironmentUuid;
            ok &= ModelBase::fromJson(fieldValue, refVal_setEnvironmentUuid);
            setEnvironmentUuid(refVal_setEnvironmentUuid);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("workflow_uuid"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("workflow_uuid")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setWorkflowUuid;
            ok &= ModelBase::fromJson(fieldValue, refVal_setWorkflowUuid);
            setWorkflowUuid(refVal_setWorkflowUuid);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("workspace_uuid"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("workspace_uuid")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setWorkspaceUuid;
            ok &= ModelBase::fromJson(fieldValue, refVal_setWorkspaceUuid);
            setWorkspaceUuid(refVal_setWorkspaceUuid);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("created_by_uuid"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("created_by_uuid")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCreatedByUuid;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCreatedByUuid);
            setCreatedByUuid(refVal_setCreatedByUuid);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("created_at"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("created_at")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setCreatedAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCreatedAt);
            setCreatedAt(refVal_setCreatedAt);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("updated_at"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("updated_at")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setUpdatedAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUpdatedAt);
            setUpdatedAt(refVal_setUpdatedAt);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("resolved_at"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("resolved_at")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setResolvedAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setResolvedAt);
            setResolvedAt(refVal_setResolvedAt);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("last_seen_at"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("last_seen_at")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setLastSeenAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLastSeenAt);
            setLastSeenAt(refVal_setLastSeenAt);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("dedupe_count"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("dedupe_count")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setDedupeCount;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDedupeCount);
            setDedupeCount(refVal_setDedupeCount);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("metadata"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("metadata")));
        if(!fieldValue.is_null())
        {
            std::map<utility::string_t, std::shared_ptr<AnyType>> refVal_setMetadata;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMetadata);
            setMetadata(refVal_setMetadata);
            
        }
    }
    return ok;
}

void AlertSchema::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_UuidIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("uuid")), m_Uuid));
    }
    if(m_NameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("name")), m_Name));
    }
    if(m_DescriptionIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("description")), m_Description));
    }
    if(m_Media.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("media")), m_Media.get()));
    }
    if(m_Alert_typeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("alert_type")), m_Alert_type));
    }
    if(m_SeverityIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("severity")), m_Severity));
    }
    if(m_StatusIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("status")), m_Status));
    }
    if(m_Source_typeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("source_type")), m_Source_type));
    }
    if(m_CategoryIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("category")), m_Category));
    }
    if(m_Twin_uuid.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("twin_uuid")), m_Twin_uuid.get()));
    }
    if(m_Environment_uuid.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("environment_uuid")), m_Environment_uuid.get()));
    }
    if(m_Workflow_uuid.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("workflow_uuid")), m_Workflow_uuid.get()));
    }
    if(m_Workspace_uuidIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("workspace_uuid")), m_Workspace_uuid));
    }
    if(m_Created_by_uuid.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("created_by_uuid")), m_Created_by_uuid.get()));
    }
    if(m_Created_atIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("created_at")), m_Created_at));
    }
    if(m_Updated_atIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("updated_at")), m_Updated_at));
    }
    if(m_Resolved_at.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("resolved_at")), m_Resolved_at.get()));
    }
    if(m_Last_seen_at.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("last_seen_at")), m_Last_seen_at.get()));
    }
    if(m_Dedupe_countIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("dedupe_count")), m_Dedupe_count));
    }
    if(m_Metadata.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("metadata")), m_Metadata.get()));
    }
}

bool AlertSchema::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("uuid"))))
    {
        utility::string_t refVal_setUuid;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("uuid"))), refVal_setUuid );
        setUuid(refVal_setUuid);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        utility::string_t refVal_setName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("name"))), refVal_setName );
        setName(refVal_setName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("description"))))
    {
        utility::string_t refVal_setDescription;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("description"))), refVal_setDescription );
        setDescription(refVal_setDescription);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("media"))))
    {
        utility::string_t refVal_setMedia;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("media"))), refVal_setMedia );
        setMedia(refVal_setMedia);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("alert_type"))))
    {
        utility::string_t refVal_setAlertType;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("alert_type"))), refVal_setAlertType );
        setAlertType(refVal_setAlertType);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("severity"))))
    {
        utility::string_t refVal_setSeverity;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("severity"))), refVal_setSeverity );
        setSeverity(refVal_setSeverity);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        utility::string_t refVal_setStatus;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("status"))), refVal_setStatus );
        setStatus(refVal_setStatus);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("source_type"))))
    {
        utility::string_t refVal_setSourceType;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("source_type"))), refVal_setSourceType );
        setSourceType(refVal_setSourceType);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("category"))))
    {
        utility::string_t refVal_setCategory;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("category"))), refVal_setCategory );
        setCategory(refVal_setCategory);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("twin_uuid"))))
    {
        utility::string_t refVal_setTwinUuid;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("twin_uuid"))), refVal_setTwinUuid );
        setTwinUuid(refVal_setTwinUuid);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("environment_uuid"))))
    {
        utility::string_t refVal_setEnvironmentUuid;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("environment_uuid"))), refVal_setEnvironmentUuid );
        setEnvironmentUuid(refVal_setEnvironmentUuid);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("workflow_uuid"))))
    {
        utility::string_t refVal_setWorkflowUuid;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("workflow_uuid"))), refVal_setWorkflowUuid );
        setWorkflowUuid(refVal_setWorkflowUuid);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("workspace_uuid"))))
    {
        utility::string_t refVal_setWorkspaceUuid;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("workspace_uuid"))), refVal_setWorkspaceUuid );
        setWorkspaceUuid(refVal_setWorkspaceUuid);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("created_by_uuid"))))
    {
        utility::string_t refVal_setCreatedByUuid;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("created_by_uuid"))), refVal_setCreatedByUuid );
        setCreatedByUuid(refVal_setCreatedByUuid);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("created_at"))))
    {
        utility::datetime refVal_setCreatedAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("created_at"))), refVal_setCreatedAt );
        setCreatedAt(refVal_setCreatedAt);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("updated_at"))))
    {
        utility::datetime refVal_setUpdatedAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("updated_at"))), refVal_setUpdatedAt );
        setUpdatedAt(refVal_setUpdatedAt);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("resolved_at"))))
    {
        utility::datetime refVal_setResolvedAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("resolved_at"))), refVal_setResolvedAt );
        setResolvedAt(refVal_setResolvedAt);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("last_seen_at"))))
    {
        utility::datetime refVal_setLastSeenAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("last_seen_at"))), refVal_setLastSeenAt );
        setLastSeenAt(refVal_setLastSeenAt);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("dedupe_count"))))
    {
        int32_t refVal_setDedupeCount;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("dedupe_count"))), refVal_setDedupeCount );
        setDedupeCount(refVal_setDedupeCount);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("metadata"))))
    {
        std::map<utility::string_t, std::shared_ptr<AnyType>> refVal_setMetadata;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("metadata"))), refVal_setMetadata );
        setMetadata(refVal_setMetadata);
    }
    return ok;
}


utility::string_t AlertSchema::getUuid() const
{
    return m_Uuid;
}


void AlertSchema::setUuid(const utility::string_t& value)
{
    m_Uuid = value;
    m_UuidIsSet = true;
}

bool AlertSchema::uuidIsSet() const
{
    return m_UuidIsSet;
}

void AlertSchema::unsetUuid()
{
    m_UuidIsSet = false;
}
utility::string_t AlertSchema::getName() const
{
    return m_Name;
}


void AlertSchema::setName(const utility::string_t& value)
{
    m_Name = value;
    m_NameIsSet = true;
}

bool AlertSchema::nameIsSet() const
{
    return m_NameIsSet;
}

void AlertSchema::unsetName()
{
    m_NameIsSet = false;
}
utility::string_t AlertSchema::getDescription() const
{
    return m_Description;
}


void AlertSchema::setDescription(const utility::string_t& value)
{
    m_Description = value;
    m_DescriptionIsSet = true;
}

bool AlertSchema::descriptionIsSet() const
{
    return m_DescriptionIsSet;
}

void AlertSchema::unsetDescription()
{
    m_DescriptionIsSet = false;
}
utility::string_t AlertSchema::getMedia() const
{
    return m_Media.get();
}


void AlertSchema::setMedia(const utility::string_t& value)
{
    m_Media = value;
}

bool AlertSchema::mediaIsSet() const
{
    return m_Media.has_value();
}

void AlertSchema::unsetMedia()
{
    m_Media.reset();
}
utility::string_t AlertSchema::getAlertType() const
{
    return m_Alert_type;
}


void AlertSchema::setAlertType(const utility::string_t& value)
{
    m_Alert_type = value;
    m_Alert_typeIsSet = true;
}

bool AlertSchema::alertTypeIsSet() const
{
    return m_Alert_typeIsSet;
}

void AlertSchema::unsetAlert_type()
{
    m_Alert_typeIsSet = false;
}
utility::string_t AlertSchema::getSeverity() const
{
    return m_Severity;
}


void AlertSchema::setSeverity(const utility::string_t& value)
{
    m_Severity = value;
    m_SeverityIsSet = true;
}

bool AlertSchema::severityIsSet() const
{
    return m_SeverityIsSet;
}

void AlertSchema::unsetSeverity()
{
    m_SeverityIsSet = false;
}
utility::string_t AlertSchema::getStatus() const
{
    return m_Status;
}


void AlertSchema::setStatus(const utility::string_t& value)
{
    m_Status = value;
    m_StatusIsSet = true;
}

bool AlertSchema::statusIsSet() const
{
    return m_StatusIsSet;
}

void AlertSchema::unsetStatus()
{
    m_StatusIsSet = false;
}
utility::string_t AlertSchema::getSourceType() const
{
    return m_Source_type;
}


void AlertSchema::setSourceType(const utility::string_t& value)
{
    m_Source_type = value;
    m_Source_typeIsSet = true;
}

bool AlertSchema::sourceTypeIsSet() const
{
    return m_Source_typeIsSet;
}

void AlertSchema::unsetSource_type()
{
    m_Source_typeIsSet = false;
}
utility::string_t AlertSchema::getCategory() const
{
    return m_Category;
}


void AlertSchema::setCategory(const utility::string_t& value)
{
    m_Category = value;
    m_CategoryIsSet = true;
}

bool AlertSchema::categoryIsSet() const
{
    return m_CategoryIsSet;
}

void AlertSchema::unsetCategory()
{
    m_CategoryIsSet = false;
}
utility::string_t AlertSchema::getTwinUuid() const
{
    return m_Twin_uuid.get();
}


void AlertSchema::setTwinUuid(const utility::string_t& value)
{
    m_Twin_uuid = value;
}

bool AlertSchema::twinUuidIsSet() const
{
    return m_Twin_uuid.has_value();
}

void AlertSchema::unsetTwin_uuid()
{
    m_Twin_uuid.reset();
}
utility::string_t AlertSchema::getEnvironmentUuid() const
{
    return m_Environment_uuid.get();
}


void AlertSchema::setEnvironmentUuid(const utility::string_t& value)
{
    m_Environment_uuid = value;
}

bool AlertSchema::environmentUuidIsSet() const
{
    return m_Environment_uuid.has_value();
}

void AlertSchema::unsetEnvironment_uuid()
{
    m_Environment_uuid.reset();
}
utility::string_t AlertSchema::getWorkflowUuid() const
{
    return m_Workflow_uuid.get();
}


void AlertSchema::setWorkflowUuid(const utility::string_t& value)
{
    m_Workflow_uuid = value;
}

bool AlertSchema::workflowUuidIsSet() const
{
    return m_Workflow_uuid.has_value();
}

void AlertSchema::unsetWorkflow_uuid()
{
    m_Workflow_uuid.reset();
}
utility::string_t AlertSchema::getWorkspaceUuid() const
{
    return m_Workspace_uuid;
}


void AlertSchema::setWorkspaceUuid(const utility::string_t& value)
{
    m_Workspace_uuid = value;
    m_Workspace_uuidIsSet = true;
}

bool AlertSchema::workspaceUuidIsSet() const
{
    return m_Workspace_uuidIsSet;
}

void AlertSchema::unsetWorkspace_uuid()
{
    m_Workspace_uuidIsSet = false;
}
utility::string_t AlertSchema::getCreatedByUuid() const
{
    return m_Created_by_uuid.get();
}


void AlertSchema::setCreatedByUuid(const utility::string_t& value)
{
    m_Created_by_uuid = value;
}

bool AlertSchema::createdByUuidIsSet() const
{
    return m_Created_by_uuid.has_value();
}

void AlertSchema::unsetCreated_by_uuid()
{
    m_Created_by_uuid.reset();
}
utility::datetime AlertSchema::getCreatedAt() const
{
    return m_Created_at;
}


void AlertSchema::setCreatedAt(const utility::datetime& value)
{
    m_Created_at = value;
    m_Created_atIsSet = true;
}

bool AlertSchema::createdAtIsSet() const
{
    return m_Created_atIsSet;
}

void AlertSchema::unsetCreated_at()
{
    m_Created_atIsSet = false;
}
utility::datetime AlertSchema::getUpdatedAt() const
{
    return m_Updated_at;
}


void AlertSchema::setUpdatedAt(const utility::datetime& value)
{
    m_Updated_at = value;
    m_Updated_atIsSet = true;
}

bool AlertSchema::updatedAtIsSet() const
{
    return m_Updated_atIsSet;
}

void AlertSchema::unsetUpdated_at()
{
    m_Updated_atIsSet = false;
}
utility::datetime AlertSchema::getResolvedAt() const
{
    return m_Resolved_at.get();
}


void AlertSchema::setResolvedAt(const utility::datetime& value)
{
    m_Resolved_at = value;
}

bool AlertSchema::resolvedAtIsSet() const
{
    return m_Resolved_at.has_value();
}

void AlertSchema::unsetResolved_at()
{
    m_Resolved_at.reset();
}
utility::datetime AlertSchema::getLastSeenAt() const
{
    return m_Last_seen_at.get();
}


void AlertSchema::setLastSeenAt(const utility::datetime& value)
{
    m_Last_seen_at = value;
}

bool AlertSchema::lastSeenAtIsSet() const
{
    return m_Last_seen_at.has_value();
}

void AlertSchema::unsetLast_seen_at()
{
    m_Last_seen_at.reset();
}
int32_t AlertSchema::getDedupeCount() const
{
    return m_Dedupe_count;
}

void AlertSchema::setDedupeCount(int32_t value)
{
    m_Dedupe_count = value;
    m_Dedupe_countIsSet = true;
}

bool AlertSchema::dedupeCountIsSet() const
{
    return m_Dedupe_countIsSet;
}

void AlertSchema::unsetDedupe_count()
{
    m_Dedupe_countIsSet = false;
}
std::map<utility::string_t, std::shared_ptr<AnyType>> AlertSchema::getMetadata() const
{
    return m_Metadata.get();
}


void AlertSchema::setMetadata(const std::map<utility::string_t, std::shared_ptr<AnyType>>& value)
{
    m_Metadata = value;
}

bool AlertSchema::metadataIsSet() const
{
    return m_Metadata.has_value();
}

void AlertSchema::unsetMetadata()
{
    m_Metadata.reset();
}

}
}
}
}


