/**
 * Cyberwave API
 * Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.26.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/APITokenUpdateSchema.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

APITokenUpdateSchema::APITokenUpdateSchema()
{
}

APITokenUpdateSchema::~APITokenUpdateSchema()
{
}

void APITokenUpdateSchema::validate()
{
    // TODO: implement validation
}

web::json::value APITokenUpdateSchema::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_Name.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("name"))] = ModelBase::toJson(m_Name.get());
    }
    if(m_Expires_at.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("expires_at"))] = ModelBase::toJson(m_Expires_at.get());
    }

    return val;
}

bool APITokenUpdateSchema::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setName);
            setName(refVal_setName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("expires_at"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("expires_at")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setExpiresAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setExpiresAt);
            setExpiresAt(refVal_setExpiresAt);
            
        }
    }
    return ok;
}

void APITokenUpdateSchema::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_Name.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("name")), m_Name.get()));
    }
    if(m_Expires_at.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("expires_at")), m_Expires_at.get()));
    }
}

bool APITokenUpdateSchema::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        utility::string_t refVal_setName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("name"))), refVal_setName );
        setName(refVal_setName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("expires_at"))))
    {
        utility::datetime refVal_setExpiresAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("expires_at"))), refVal_setExpiresAt );
        setExpiresAt(refVal_setExpiresAt);
    }
    return ok;
}


utility::string_t APITokenUpdateSchema::getName() const
{
    return m_Name.get();
}


void APITokenUpdateSchema::setName(const utility::string_t& value)
{
    m_Name = value;
}

bool APITokenUpdateSchema::nameIsSet() const
{
    return m_Name.has_value();
}

void APITokenUpdateSchema::unsetName()
{
    m_Name.reset();
}
utility::datetime APITokenUpdateSchema::getExpiresAt() const
{
    return m_Expires_at.get();
}


void APITokenUpdateSchema::setExpiresAt(const utility::datetime& value)
{
    m_Expires_at = value;
}

bool APITokenUpdateSchema::expiresAtIsSet() const
{
    return m_Expires_at.has_value();
}

void APITokenUpdateSchema::unsetExpires_at()
{
    m_Expires_at.reset();
}

}
}
}
}


