/**
 * Cyberwave API
 * Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.23.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/AssetCatalogImportSchema.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

AssetCatalogImportSchema::AssetCatalogImportSchema()
{
    m_Registry_id = utility::conversions::to_string_t("");
    m_Registry_idIsSet = false;
    m_Workspace_slug = utility::conversions::to_string_t("");
    m_Workspace_slugIsSet = false;
}

AssetCatalogImportSchema::~AssetCatalogImportSchema()
{
}

void AssetCatalogImportSchema::validate()
{
    // TODO: implement validation
}

web::json::value AssetCatalogImportSchema::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_Registry_idIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("registry_id"))] = ModelBase::toJson(m_Registry_id);
    }
    if(m_Workspace_slugIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("workspace_slug"))] = ModelBase::toJson(m_Workspace_slug);
    }
    if(m_Source_url.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("source_url"))] = ModelBase::toJson(m_Source_url.get());
    }
    if(m_Source_token.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("source_token"))] = ModelBase::toJson(m_Source_token.get());
    }

    return val;
}

bool AssetCatalogImportSchema::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("registry_id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("registry_id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setRegistryId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRegistryId);
            setRegistryId(refVal_setRegistryId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("workspace_slug"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("workspace_slug")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setWorkspaceSlug;
            ok &= ModelBase::fromJson(fieldValue, refVal_setWorkspaceSlug);
            setWorkspaceSlug(refVal_setWorkspaceSlug);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("source_url"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("source_url")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setSourceUrl;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSourceUrl);
            setSourceUrl(refVal_setSourceUrl);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("source_token"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("source_token")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setSourceToken;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSourceToken);
            setSourceToken(refVal_setSourceToken);
            
        }
    }
    return ok;
}

void AssetCatalogImportSchema::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_Registry_idIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("registry_id")), m_Registry_id));
    }
    if(m_Workspace_slugIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("workspace_slug")), m_Workspace_slug));
    }
    if(m_Source_url.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("source_url")), m_Source_url.get()));
    }
    if(m_Source_token.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("source_token")), m_Source_token.get()));
    }
}

bool AssetCatalogImportSchema::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("registry_id"))))
    {
        utility::string_t refVal_setRegistryId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("registry_id"))), refVal_setRegistryId );
        setRegistryId(refVal_setRegistryId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("workspace_slug"))))
    {
        utility::string_t refVal_setWorkspaceSlug;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("workspace_slug"))), refVal_setWorkspaceSlug );
        setWorkspaceSlug(refVal_setWorkspaceSlug);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("source_url"))))
    {
        utility::string_t refVal_setSourceUrl;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("source_url"))), refVal_setSourceUrl );
        setSourceUrl(refVal_setSourceUrl);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("source_token"))))
    {
        utility::string_t refVal_setSourceToken;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("source_token"))), refVal_setSourceToken );
        setSourceToken(refVal_setSourceToken);
    }
    return ok;
}


utility::string_t AssetCatalogImportSchema::getRegistryId() const
{
    return m_Registry_id;
}


void AssetCatalogImportSchema::setRegistryId(const utility::string_t& value)
{
    m_Registry_id = value;
    m_Registry_idIsSet = true;
}

bool AssetCatalogImportSchema::registryIdIsSet() const
{
    return m_Registry_idIsSet;
}

void AssetCatalogImportSchema::unsetRegistry_id()
{
    m_Registry_idIsSet = false;
}
utility::string_t AssetCatalogImportSchema::getWorkspaceSlug() const
{
    return m_Workspace_slug;
}


void AssetCatalogImportSchema::setWorkspaceSlug(const utility::string_t& value)
{
    m_Workspace_slug = value;
    m_Workspace_slugIsSet = true;
}

bool AssetCatalogImportSchema::workspaceSlugIsSet() const
{
    return m_Workspace_slugIsSet;
}

void AssetCatalogImportSchema::unsetWorkspace_slug()
{
    m_Workspace_slugIsSet = false;
}
utility::string_t AssetCatalogImportSchema::getSourceUrl() const
{
    return m_Source_url.get();
}


void AssetCatalogImportSchema::setSourceUrl(const utility::string_t& value)
{
    m_Source_url = value;
}

bool AssetCatalogImportSchema::sourceUrlIsSet() const
{
    return m_Source_url.has_value();
}

void AssetCatalogImportSchema::unsetSource_url()
{
    m_Source_url.reset();
}
utility::string_t AssetCatalogImportSchema::getSourceToken() const
{
    return m_Source_token.get();
}


void AssetCatalogImportSchema::setSourceToken(const utility::string_t& value)
{
    m_Source_token = value;
}

bool AssetCatalogImportSchema::sourceTokenIsSet() const
{
    return m_Source_token.has_value();
}

void AssetCatalogImportSchema::unsetSource_token()
{
    m_Source_token.reset();
}

}
}
}
}


