/**
 * Cyberwave API
 * Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/BatchDeleteRecordingsSchema.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

BatchDeleteRecordingsSchema::BatchDeleteRecordingsSchema()
{
    m_Recording_uuidsIsSet = false;
}

BatchDeleteRecordingsSchema::~BatchDeleteRecordingsSchema()
{
}

void BatchDeleteRecordingsSchema::validate()
{
    // TODO: implement validation
}

web::json::value BatchDeleteRecordingsSchema::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_Recording_uuidsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("recording_uuids"))] = ModelBase::toJson(m_Recording_uuids);
    }

    return val;
}

bool BatchDeleteRecordingsSchema::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("recording_uuids"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("recording_uuids")));
        if(!fieldValue.is_null())
        {
            std::vector<utility::string_t> refVal_setRecordingUuids;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRecordingUuids);
            setRecordingUuids(refVal_setRecordingUuids);
            
        }
    }
    return ok;
}

void BatchDeleteRecordingsSchema::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_Recording_uuidsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("recording_uuids")), m_Recording_uuids));
    }
}

bool BatchDeleteRecordingsSchema::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("recording_uuids"))))
    {
        std::vector<utility::string_t> refVal_setRecordingUuids;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("recording_uuids"))), refVal_setRecordingUuids );
        setRecordingUuids(refVal_setRecordingUuids);
    }
    return ok;
}


std::vector<utility::string_t> BatchDeleteRecordingsSchema::getRecordingUuids() const
{
    return m_Recording_uuids;
}


void BatchDeleteRecordingsSchema::setRecordingUuids(const std::vector<utility::string_t>& value)
{
    m_Recording_uuids = value;
    m_Recording_uuidsIsSet = true;
}

bool BatchDeleteRecordingsSchema::recordingUuidsIsSet() const
{
    return m_Recording_uuidsIsSet;
}

void BatchDeleteRecordingsSchema::unsetRecording_uuids()
{
    m_Recording_uuidsIsSet = false;
}

}
}
}
}


