/**
 * Cyberwave API
 * Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.26.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/CapabilityControlSetup.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

CapabilityControlSetup::CapabilityControlSetup()
{
    m_VersionIsSet = false;
    m_Manual_inputIsSet = false;
    m_PolicyIsSet = false;
    m_Input_devicesIsSet = false;
}

CapabilityControlSetup::~CapabilityControlSetup()
{
}

void CapabilityControlSetup::validate()
{
    // TODO: implement validation
}

web::json::value CapabilityControlSetup::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_VersionIsSet)
    {
        
        int32_t refVal = fromVersionEnum(m_Version);
        val[utility::conversions::to_string_t(_XPLATSTR("version"))] = ModelBase::toJson(refVal);
        
    }
    if(m_Manual_inputIsSet)
    {
        
        utility::string_t refVal = fromManual_inputEnum(m_Manual_input);
        val[utility::conversions::to_string_t(_XPLATSTR("manual_input"))] = ModelBase::toJson(refVal);
        
    }
    if(m_PolicyIsSet)
    {
        
        utility::string_t refVal = fromPolicyEnum(m_Policy);
        val[utility::conversions::to_string_t(_XPLATSTR("policy"))] = ModelBase::toJson(refVal);
        
    }
    if(m_Preferred.has_value())
    {
        
        utility::string_t refVal = fromPreferredEnum(m_Preferred.get());
        val[utility::conversions::to_string_t(_XPLATSTR("preferred"))] = ModelBase::toJson(refVal);
        
    }
    if(m_Input_devicesIsSet)
    {
        
        std::vector<utility::string_t> refVal = fromInput_devicesEnum(m_Input_devices);
        val[utility::conversions::to_string_t(_XPLATSTR("input_devices"))] = ModelBase::toJson(refVal);
        
    }

    return val;
}

bool CapabilityControlSetup::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("version"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("version")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setVersion;
            if (!fieldValue.is_number() || !fieldValue.as_number().is_int32()) return false;
            if (!ModelBase::fromJson(fieldValue, refVal_setVersion)) return false;
            
            setVersion(toVersionEnum(refVal_setVersion));
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("manual_input"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("manual_input")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setManualInput;
            ok &= ModelBase::fromJson(fieldValue, refVal_setManualInput);
            
            setManualInput(toManual_inputEnum(refVal_setManualInput));
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("policy"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("policy")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setPolicy;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPolicy);
            
            setPolicy(toPolicyEnum(refVal_setPolicy));
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("preferred"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("preferred")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setPreferred;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPreferred);
            
            setPreferred(toPreferredEnum(refVal_setPreferred));
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("input_devices"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("input_devices")));
        if(!fieldValue.is_null())
        {
            std::vector<utility::string_t> refVal_setInputDevices;
            ok &= ModelBase::fromJson(fieldValue, refVal_setInputDevices);
            
            setInputDevices(toInput_devicesEnum(refVal_setInputDevices));
            
        }
    }
    return ok;
}

void CapabilityControlSetup::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_VersionIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("version")), fromVersionEnum(m_Version)));
    }
    if(m_Manual_inputIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("manual_input")), fromManual_inputEnum(m_Manual_input)));
    }
    if(m_PolicyIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("policy")), fromPolicyEnum(m_Policy)));
    }
    if(m_Preferred.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("preferred")), fromPreferredEnum(m_Preferred.get())));
    }
    if(m_Input_devicesIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("input_devices")), fromInput_devicesEnum(m_Input_devices)));
            }
}

bool CapabilityControlSetup::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("version"))))
    {
        int32_t refVal_setVersion;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("version"))), refVal_setVersion );
        setVersion(toVersionEnum(refVal_setVersion));
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("manual_input"))))
    {
        utility::string_t refVal_setManualInput;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("manual_input"))), refVal_setManualInput );
        setManualInput(toManual_inputEnum(refVal_setManualInput));
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("policy"))))
    {
        utility::string_t refVal_setPolicy;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("policy"))), refVal_setPolicy );
        setPolicy(toPolicyEnum(refVal_setPolicy));
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("preferred"))))
    {
        utility::string_t refVal_setPreferred;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("preferred"))), refVal_setPreferred );
        setPreferred(toPreferredEnum(refVal_setPreferred));
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("input_devices"))))
    {
        std::vector<utility::string_t> refVal_setInputDevices;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("input_devices"))), refVal_setInputDevices );
        setInputDevices(toInput_devicesEnum(refVal_setInputDevices));
    }
    return ok;
}

CapabilityControlSetup::VersionEnum CapabilityControlSetup::toVersionEnum(const int32_t& value) const
{
    // cpp-restsdk numeric-enum wire-type repair
    if (value == static_cast<int32_t>(1)) return VersionEnum::_1;
    throw std::invalid_argument("Invalid value for conversion to VersionEnum");
}


const int32_t CapabilityControlSetup::fromVersionEnum(const VersionEnum value) const
{
    switch(value)
    {
        case VersionEnum::_1: return static_cast<int32_t>(1);
        default: throw std::invalid_argument("Invalid VersionEnum value");
    }
}

CapabilityControlSetup::Manual_inputEnum CapabilityControlSetup::toManual_inputEnum(const utility::string_t& value) const
{
    
    if (value == utility::conversions::to_string_t("optional")) {
        return Manual_inputEnum::OPTIONAL;
    }
    
    if (value == utility::conversions::to_string_t("required")) {
        return Manual_inputEnum::REQUIRED;
    }
    
    if (value == utility::conversions::to_string_t("unsupported")) {
        return Manual_inputEnum::UNSUPPORTED;
    }
    
    throw std::invalid_argument("Invalid value for conversion to Manual_inputEnum");
}


const utility::string_t CapabilityControlSetup::fromManual_inputEnum(const Manual_inputEnum value) const
{
    switch(value)
    {
        
        case Manual_inputEnum::OPTIONAL: return utility::conversions::to_string_t("optional");
        
        case Manual_inputEnum::REQUIRED: return utility::conversions::to_string_t("required");
        
        case Manual_inputEnum::UNSUPPORTED: return utility::conversions::to_string_t("unsupported");
        
    }
}

CapabilityControlSetup::PolicyEnum CapabilityControlSetup::toPolicyEnum(const utility::string_t& value) const
{
    
    if (value == utility::conversions::to_string_t("optional")) {
        return PolicyEnum::OPTIONAL;
    }
    
    if (value == utility::conversions::to_string_t("required")) {
        return PolicyEnum::REQUIRED;
    }
    
    if (value == utility::conversions::to_string_t("unsupported")) {
        return PolicyEnum::UNSUPPORTED;
    }
    
    throw std::invalid_argument("Invalid value for conversion to PolicyEnum");
}


const utility::string_t CapabilityControlSetup::fromPolicyEnum(const PolicyEnum value) const
{
    switch(value)
    {
        
        case PolicyEnum::OPTIONAL: return utility::conversions::to_string_t("optional");
        
        case PolicyEnum::REQUIRED: return utility::conversions::to_string_t("required");
        
        case PolicyEnum::UNSUPPORTED: return utility::conversions::to_string_t("unsupported");
        
    }
}

CapabilityControlSetup::PreferredEnum CapabilityControlSetup::toPreferredEnum(const utility::string_t& value) const
{
    
    if (value == utility::conversions::to_string_t("manual_input")) {
        return PreferredEnum::MANUAL_INPUT;
    }
    
    if (value == utility::conversions::to_string_t("policy")) {
        return PreferredEnum::POLICY;
    }
    
    throw std::invalid_argument("Invalid value for conversion to PreferredEnum");
}


const utility::string_t CapabilityControlSetup::fromPreferredEnum(const PreferredEnum value) const
{
    switch(value)
    {
        
        case PreferredEnum::MANUAL_INPUT: return utility::conversions::to_string_t("manual_input");
        
        case PreferredEnum::POLICY: return utility::conversions::to_string_t("policy");
        
    }
}

CapabilityControlSetup::Input_devicesEnum CapabilityControlSetup::toInput_devicesEnum(const utility::string_t& value) const
{
    
    if (value == utility::conversions::to_string_t("keyboard")) {
        return Input_devicesEnum::KEYBOARD;
    }
    
    if (value == utility::conversions::to_string_t("gamepad")) {
        return Input_devicesEnum::GAMEPAD;
    }
    
    if (value == utility::conversions::to_string_t("leader_arm")) {
        return Input_devicesEnum::LEADER_ARM;
    }
    
    if (value == utility::conversions::to_string_t("custom_leader_arm")) {
        return Input_devicesEnum::CUSTOM_LEADER_ARM;
    }
    
    throw std::invalid_argument("Invalid value for conversion to std::vector<Input_devicesEnum>");
}

const utility::string_t CapabilityControlSetup::fromInput_devicesEnum(const Input_devicesEnum value) const
{
    switch(value)
    {
        
        case Input_devicesEnum::KEYBOARD: return utility::conversions::to_string_t("keyboard");
        
        case Input_devicesEnum::GAMEPAD: return utility::conversions::to_string_t("gamepad");
        
        case Input_devicesEnum::LEADER_ARM: return utility::conversions::to_string_t("leader_arm");
        
        case Input_devicesEnum::CUSTOM_LEADER_ARM: return utility::conversions::to_string_t("custom_leader_arm");
        
    }
}

std::vector<utility::string_t> CapabilityControlSetup::fromInput_devicesEnum(const std::vector<Input_devicesEnum>& value) const
{
    std::vector<utility::string_t> ret;
    for (auto it = value.begin(); it != value.end(); it++) {
        ret.push_back(fromInput_devicesEnum(*it));
    }
    return ret;
}

std::vector<CapabilityControlSetup::Input_devicesEnum> CapabilityControlSetup::toInput_devicesEnum(const std::vector<utility::string_t>& value) const
{
    std::vector<Input_devicesEnum> ret;
    for (auto it = value.begin(); it != value.end(); it++) {
        ret.push_back(toInput_devicesEnum(*it));
    }
    return ret;
}

CapabilityControlSetup::VersionEnum CapabilityControlSetup::getVersion() const
{
    return m_Version;
}

void CapabilityControlSetup::setVersion(int32_t value)
{
    setVersion(toVersionEnum(value));
}

void CapabilityControlSetup::setVersion(const VersionEnum value)
{
    m_Version = value;
    m_VersionIsSet = true;
}

bool CapabilityControlSetup::versionIsSet() const
{
    return m_VersionIsSet;
}

void CapabilityControlSetup::unsetVersion()
{
    m_VersionIsSet = false;
}
CapabilityControlSetup::Manual_inputEnum CapabilityControlSetup::getManualInput() const
{
    return m_Manual_input;
}


void CapabilityControlSetup::setManualInput(const Manual_inputEnum value)
{
    m_Manual_input = value;
    m_Manual_inputIsSet = true;
}

bool CapabilityControlSetup::manualInputIsSet() const
{
    return m_Manual_inputIsSet;
}

void CapabilityControlSetup::unsetManual_input()
{
    m_Manual_inputIsSet = false;
}
CapabilityControlSetup::PolicyEnum CapabilityControlSetup::getPolicy() const
{
    return m_Policy;
}


void CapabilityControlSetup::setPolicy(const PolicyEnum value)
{
    m_Policy = value;
    m_PolicyIsSet = true;
}

bool CapabilityControlSetup::policyIsSet() const
{
    return m_PolicyIsSet;
}

void CapabilityControlSetup::unsetPolicy()
{
    m_PolicyIsSet = false;
}
CapabilityControlSetup::PreferredEnum CapabilityControlSetup::getPreferred() const
{
    return m_Preferred.get();
}


void CapabilityControlSetup::setPreferred(const PreferredEnum value)
{
    m_Preferred = value;
}

bool CapabilityControlSetup::preferredIsSet() const
{
    return m_Preferred.has_value();
}

void CapabilityControlSetup::unsetPreferred()
{
    m_Preferred.reset();
}
std::vector<CapabilityControlSetup::Input_devicesEnum> CapabilityControlSetup::getInputDevices() const
{
    return m_Input_devices;
}


void CapabilityControlSetup::setInputDevices(const std::vector<Input_devicesEnum> value)
{
    m_Input_devices = value;
    m_Input_devicesIsSet = true;
}

bool CapabilityControlSetup::inputDevicesIsSet() const
{
    return m_Input_devicesIsSet;
}

void CapabilityControlSetup::unsetInput_devices()
{
    m_Input_devicesIsSet = false;
}

}
}
}
}


