/**
 * Cyberwave API
 * Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.24.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/CloudNodeWorkloadAttachmentResponseSchema.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

CloudNodeWorkloadAttachmentResponseSchema::CloudNodeWorkloadAttachmentResponseSchema()
{
    m_Signed_url = utility::conversions::to_string_t("");
    m_Signed_urlIsSet = false;
    m_Filename = utility::conversions::to_string_t("");
    m_FilenameIsSet = false;
    m_Expiration_hours = 0;
    m_Expiration_hoursIsSet = false;
}

CloudNodeWorkloadAttachmentResponseSchema::~CloudNodeWorkloadAttachmentResponseSchema()
{
}

void CloudNodeWorkloadAttachmentResponseSchema::validate()
{
    // TODO: implement validation
}

web::json::value CloudNodeWorkloadAttachmentResponseSchema::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_Signed_urlIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("signed_url"))] = ModelBase::toJson(m_Signed_url);
    }
    if(m_FilenameIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("filename"))] = ModelBase::toJson(m_Filename);
    }
    if(m_Expiration_hoursIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("expiration_hours"))] = ModelBase::toJson(m_Expiration_hours);
    }

    return val;
}

bool CloudNodeWorkloadAttachmentResponseSchema::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("signed_url"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("signed_url")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setSignedUrl;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSignedUrl);
            setSignedUrl(refVal_setSignedUrl);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("filename"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("filename")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setFilename;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFilename);
            setFilename(refVal_setFilename);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("expiration_hours"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("expiration_hours")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setExpirationHours;
            ok &= ModelBase::fromJson(fieldValue, refVal_setExpirationHours);
            setExpirationHours(refVal_setExpirationHours);
            
        }
    }
    return ok;
}

void CloudNodeWorkloadAttachmentResponseSchema::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_Signed_urlIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("signed_url")), m_Signed_url));
    }
    if(m_FilenameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("filename")), m_Filename));
    }
    if(m_Expiration_hoursIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("expiration_hours")), m_Expiration_hours));
    }
}

bool CloudNodeWorkloadAttachmentResponseSchema::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("signed_url"))))
    {
        utility::string_t refVal_setSignedUrl;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("signed_url"))), refVal_setSignedUrl );
        setSignedUrl(refVal_setSignedUrl);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("filename"))))
    {
        utility::string_t refVal_setFilename;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("filename"))), refVal_setFilename );
        setFilename(refVal_setFilename);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("expiration_hours"))))
    {
        int32_t refVal_setExpirationHours;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("expiration_hours"))), refVal_setExpirationHours );
        setExpirationHours(refVal_setExpirationHours);
    }
    return ok;
}


utility::string_t CloudNodeWorkloadAttachmentResponseSchema::getSignedUrl() const
{
    return m_Signed_url;
}


void CloudNodeWorkloadAttachmentResponseSchema::setSignedUrl(const utility::string_t& value)
{
    m_Signed_url = value;
    m_Signed_urlIsSet = true;
}

bool CloudNodeWorkloadAttachmentResponseSchema::signedUrlIsSet() const
{
    return m_Signed_urlIsSet;
}

void CloudNodeWorkloadAttachmentResponseSchema::unsetSigned_url()
{
    m_Signed_urlIsSet = false;
}
utility::string_t CloudNodeWorkloadAttachmentResponseSchema::getFilename() const
{
    return m_Filename;
}


void CloudNodeWorkloadAttachmentResponseSchema::setFilename(const utility::string_t& value)
{
    m_Filename = value;
    m_FilenameIsSet = true;
}

bool CloudNodeWorkloadAttachmentResponseSchema::filenameIsSet() const
{
    return m_FilenameIsSet;
}

void CloudNodeWorkloadAttachmentResponseSchema::unsetFilename()
{
    m_FilenameIsSet = false;
}
int32_t CloudNodeWorkloadAttachmentResponseSchema::getExpirationHours() const
{
    return m_Expiration_hours;
}

void CloudNodeWorkloadAttachmentResponseSchema::setExpirationHours(int32_t value)
{
    m_Expiration_hours = value;
    m_Expiration_hoursIsSet = true;
}

bool CloudNodeWorkloadAttachmentResponseSchema::expirationHoursIsSet() const
{
    return m_Expiration_hoursIsSet;
}

void CloudNodeWorkloadAttachmentResponseSchema::unsetExpiration_hours()
{
    m_Expiration_hoursIsSet = false;
}

}
}
}
}


