/**
 * Cyberwave API
 * Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.26.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/ControlInputCompatibilitySchema.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

ControlInputCompatibilitySchema::ControlInputCompatibilitySchema()
{
    m_StatusIsSet = false;
    m_Reason = utility::conversions::to_string_t("");
    m_ReasonIsSet = false;
}

ControlInputCompatibilitySchema::~ControlInputCompatibilitySchema()
{
}

void ControlInputCompatibilitySchema::validate()
{
    // TODO: implement validation
}

web::json::value ControlInputCompatibilitySchema::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_Code.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("code"))] = ModelBase::toJson(m_Code.get());
    }
    if(m_StatusIsSet)
    {
        
        utility::string_t refVal = fromStatusEnum(m_Status);
        val[utility::conversions::to_string_t(_XPLATSTR("status"))] = ModelBase::toJson(refVal);
        
    }
    if(m_ReasonIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("reason"))] = ModelBase::toJson(m_Reason);
    }

    return val;
}

bool ControlInputCompatibilitySchema::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("code"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("code")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCode;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCode);
            setCode(refVal_setCode);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("status")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setStatus;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStatus);
            
            setStatus(toStatusEnum(refVal_setStatus));
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("reason"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("reason")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setReason;
            ok &= ModelBase::fromJson(fieldValue, refVal_setReason);
            setReason(refVal_setReason);
            
        }
    }
    return ok;
}

void ControlInputCompatibilitySchema::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_Code.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("code")), m_Code.get()));
    }
    if(m_StatusIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("status")), fromStatusEnum(m_Status)));
    }
    if(m_ReasonIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("reason")), m_Reason));
    }
}

bool ControlInputCompatibilitySchema::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("code"))))
    {
        utility::string_t refVal_setCode;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("code"))), refVal_setCode );
        setCode(refVal_setCode);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        utility::string_t refVal_setStatus;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("status"))), refVal_setStatus );
        setStatus(toStatusEnum(refVal_setStatus));
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("reason"))))
    {
        utility::string_t refVal_setReason;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("reason"))), refVal_setReason );
        setReason(refVal_setReason);
    }
    return ok;
}

ControlInputCompatibilitySchema::StatusEnum ControlInputCompatibilitySchema::toStatusEnum(const utility::string_t& value) const
{
    
    if (value == utility::conversions::to_string_t("mapped")) {
        return StatusEnum::MAPPED;
    }
    
    if (value == utility::conversions::to_string_t("needs_mapping")) {
        return StatusEnum::NEEDS_MAPPING;
    }
    
    if (value == utility::conversions::to_string_t("unavailable")) {
        return StatusEnum::UNAVAILABLE;
    }
    
    throw std::invalid_argument("Invalid value for conversion to StatusEnum");
}


const utility::string_t ControlInputCompatibilitySchema::fromStatusEnum(const StatusEnum value) const
{
    switch(value)
    {
        
        case StatusEnum::MAPPED: return utility::conversions::to_string_t("mapped");
        
        case StatusEnum::NEEDS_MAPPING: return utility::conversions::to_string_t("needs_mapping");
        
        case StatusEnum::UNAVAILABLE: return utility::conversions::to_string_t("unavailable");
        
    }
}


utility::string_t ControlInputCompatibilitySchema::getCode() const
{
    return m_Code.get();
}


void ControlInputCompatibilitySchema::setCode(const utility::string_t& value)
{
    m_Code = value;
}

bool ControlInputCompatibilitySchema::codeIsSet() const
{
    return m_Code.has_value();
}

void ControlInputCompatibilitySchema::unsetCode()
{
    m_Code.reset();
}
ControlInputCompatibilitySchema::StatusEnum ControlInputCompatibilitySchema::getStatus() const
{
    return m_Status;
}


void ControlInputCompatibilitySchema::setStatus(const StatusEnum value)
{
    m_Status = value;
    m_StatusIsSet = true;
}

bool ControlInputCompatibilitySchema::statusIsSet() const
{
    return m_StatusIsSet;
}

void ControlInputCompatibilitySchema::unsetStatus()
{
    m_StatusIsSet = false;
}
utility::string_t ControlInputCompatibilitySchema::getReason() const
{
    return m_Reason;
}


void ControlInputCompatibilitySchema::setReason(const utility::string_t& value)
{
    m_Reason = value;
    m_ReasonIsSet = true;
}

bool ControlInputCompatibilitySchema::reasonIsSet() const
{
    return m_ReasonIsSet;
}

void ControlInputCompatibilitySchema::unsetReason()
{
    m_ReasonIsSet = false;
}

}
}
}
}


