/**
 * Cyberwave API
 * Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.24.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/DatasetSchema.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

DatasetSchema::DatasetSchema()
{
    m_Uuid = utility::conversions::to_string_t("");
    m_UuidIsSet = false;
    m_EpisodesIsSet = false;
    m_MetadataIsSet = false;
    m_Processed_datasetsIsSet = false;
    m_Processing_status = utility::conversions::to_string_t("");
    m_Processing_statusIsSet = false;
    m_Is_ready = false;
    m_Is_readyIsSet = false;
    m_Is_imported = false;
    m_Is_importedIsSet = false;
    m_Visibility = utility::conversions::to_string_t("");
    m_VisibilityIsSet = false;
    m_Total_episodes = 0;
    m_Total_episodesIsSet = false;
    m_Processed_episodes = 0;
    m_Processed_episodesIsSet = false;
    m_Failed_episodes = 0;
    m_Failed_episodesIsSet = false;
    m_Failed_episode_uuidsIsSet = false;
    m_Created_at = utility::datetime();
    m_Created_atIsSet = false;
    m_Updated_at = utility::datetime();
    m_Updated_atIsSet = false;
}

DatasetSchema::~DatasetSchema()
{
}

void DatasetSchema::validate()
{
    // TODO: implement validation
}

web::json::value DatasetSchema::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_UuidIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("uuid"))] = ModelBase::toJson(m_Uuid);
    }
    if(m_Name.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("name"))] = ModelBase::toJson(m_Name.get());
    }
    if(m_EpisodesIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("episodes"))] = ModelBase::toJson(m_Episodes);
    }
    if(m_MetadataIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("metadata"))] = ModelBase::toJson(m_Metadata);
    }
    if(m_Processed_datasetsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("processed_datasets"))] = ModelBase::toJson(m_Processed_datasets);
    }
    if(m_Processing_statusIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("processing_status"))] = ModelBase::toJson(m_Processing_status);
    }
    if(m_Is_readyIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("is_ready"))] = ModelBase::toJson(m_Is_ready);
    }
    if(m_Is_importedIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("is_imported"))] = ModelBase::toJson(m_Is_imported);
    }
    if(m_Source.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("source"))] = ModelBase::toJson(m_Source.get());
    }
    if(m_Source_format.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("source_format"))] = ModelBase::toJson(m_Source_format.get());
    }
    if(m_Slug.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("slug"))] = ModelBase::toJson(m_Slug.get());
    }
    if(m_VisibilityIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("visibility"))] = ModelBase::toJson(m_Visibility);
    }
    if(m_Total_episodesIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("total_episodes"))] = ModelBase::toJson(m_Total_episodes);
    }
    if(m_Processed_episodesIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("processed_episodes"))] = ModelBase::toJson(m_Processed_episodes);
    }
    if(m_Failed_episodesIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("failed_episodes"))] = ModelBase::toJson(m_Failed_episodes);
    }
    if(m_Failed_episode_uuidsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("failed_episode_uuids"))] = ModelBase::toJson(m_Failed_episode_uuids);
    }
    if(m_Cameras.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("cameras"))] = ModelBase::toJson(m_Cameras.get());
    }
    if(m_Fps.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("fps"))] = ModelBase::toJson(m_Fps.get());
    }
    if(m_Robot_type.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("robot_type"))] = ModelBase::toJson(m_Robot_type.get());
    }
    if(m_Action_dim.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("action_dim"))] = ModelBase::toJson(m_Action_dim.get());
    }
    if(m_State_dim.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("state_dim"))] = ModelBase::toJson(m_State_dim.get());
    }
    if(m_Created_atIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("created_at"))] = ModelBase::toJson(m_Created_at);
    }
    if(m_Updated_atIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("updated_at"))] = ModelBase::toJson(m_Updated_at);
    }
    if(m_Created_by.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("created_by"))] = ModelBase::toJson(m_Created_by.get());
    }
    if(m_Updated_by.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("updated_by"))] = ModelBase::toJson(m_Updated_by.get());
    }

    return val;
}

bool DatasetSchema::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("uuid"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("uuid")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setUuid;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUuid);
            setUuid(refVal_setUuid);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setName);
            setName(refVal_setName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("episodes"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("episodes")));
        if(!fieldValue.is_null())
        {
            std::vector<utility::string_t> refVal_setEpisodes;
            ok &= ModelBase::fromJson(fieldValue, refVal_setEpisodes);
            setEpisodes(refVal_setEpisodes);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("metadata"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("metadata")));
        if(!fieldValue.is_null())
        {
            std::map<utility::string_t, std::shared_ptr<AnyType>> refVal_setMetadata;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMetadata);
            setMetadata(refVal_setMetadata);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("processed_datasets"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("processed_datasets")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<ProcessedDatasetSchema>> refVal_setProcessedDatasets;
            ok &= ModelBase::fromJson(fieldValue, refVal_setProcessedDatasets);
            setProcessedDatasets(refVal_setProcessedDatasets);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("processing_status"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("processing_status")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setProcessingStatus;
            ok &= ModelBase::fromJson(fieldValue, refVal_setProcessingStatus);
            setProcessingStatus(refVal_setProcessingStatus);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("is_ready"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("is_ready")));
        if(!fieldValue.is_null())
        {
            bool refVal_setIsReady;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIsReady);
            setIsReady(refVal_setIsReady);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("is_imported"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("is_imported")));
        if(!fieldValue.is_null())
        {
            bool refVal_setIsImported;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIsImported);
            setIsImported(refVal_setIsImported);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("source"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("source")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setSource;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSource);
            setSource(refVal_setSource);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("source_format"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("source_format")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setSourceFormat;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSourceFormat);
            setSourceFormat(refVal_setSourceFormat);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("slug"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("slug")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setSlug;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSlug);
            setSlug(refVal_setSlug);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("visibility"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("visibility")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setVisibility;
            ok &= ModelBase::fromJson(fieldValue, refVal_setVisibility);
            setVisibility(refVal_setVisibility);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("total_episodes"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("total_episodes")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setTotalEpisodes;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTotalEpisodes);
            setTotalEpisodes(refVal_setTotalEpisodes);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("processed_episodes"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("processed_episodes")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setProcessedEpisodes;
            ok &= ModelBase::fromJson(fieldValue, refVal_setProcessedEpisodes);
            setProcessedEpisodes(refVal_setProcessedEpisodes);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("failed_episodes"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("failed_episodes")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setFailedEpisodes;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFailedEpisodes);
            setFailedEpisodes(refVal_setFailedEpisodes);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("failed_episode_uuids"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("failed_episode_uuids")));
        if(!fieldValue.is_null())
        {
            std::vector<utility::string_t> refVal_setFailedEpisodeUuids;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFailedEpisodeUuids);
            setFailedEpisodeUuids(refVal_setFailedEpisodeUuids);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("cameras"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("cameras")));
        if(!fieldValue.is_null())
        {
            std::vector<utility::string_t> refVal_setCameras;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCameras);
            setCameras(refVal_setCameras);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("fps"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("fps")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setFps;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFps);
            setFps(refVal_setFps);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("robot_type"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("robot_type")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setRobotType;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRobotType);
            setRobotType(refVal_setRobotType);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("action_dim"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("action_dim")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setActionDim;
            ok &= ModelBase::fromJson(fieldValue, refVal_setActionDim);
            setActionDim(refVal_setActionDim);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("state_dim"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("state_dim")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setStateDim;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStateDim);
            setStateDim(refVal_setStateDim);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("created_at"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("created_at")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setCreatedAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCreatedAt);
            setCreatedAt(refVal_setCreatedAt);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("updated_at"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("updated_at")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setUpdatedAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUpdatedAt);
            setUpdatedAt(refVal_setUpdatedAt);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("created_by"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("created_by")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCreatedBy;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCreatedBy);
            setCreatedBy(refVal_setCreatedBy);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("updated_by"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("updated_by")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setUpdatedBy;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUpdatedBy);
            setUpdatedBy(refVal_setUpdatedBy);
            
        }
    }
    return ok;
}

void DatasetSchema::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_UuidIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("uuid")), m_Uuid));
    }
    if(m_Name.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("name")), m_Name.get()));
    }
    if(m_EpisodesIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("episodes")), m_Episodes));
    }
    if(m_MetadataIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("metadata")), m_Metadata));
    }
    if(m_Processed_datasetsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("processed_datasets")), m_Processed_datasets));
    }
    if(m_Processing_statusIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("processing_status")), m_Processing_status));
    }
    if(m_Is_readyIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("is_ready")), m_Is_ready));
    }
    if(m_Is_importedIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("is_imported")), m_Is_imported));
    }
    if(m_Source.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("source")), m_Source.get()));
    }
    if(m_Source_format.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("source_format")), m_Source_format.get()));
    }
    if(m_Slug.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("slug")), m_Slug.get()));
    }
    if(m_VisibilityIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("visibility")), m_Visibility));
    }
    if(m_Total_episodesIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("total_episodes")), m_Total_episodes));
    }
    if(m_Processed_episodesIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("processed_episodes")), m_Processed_episodes));
    }
    if(m_Failed_episodesIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("failed_episodes")), m_Failed_episodes));
    }
    if(m_Failed_episode_uuidsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("failed_episode_uuids")), m_Failed_episode_uuids));
    }
    if(m_Cameras.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("cameras")), m_Cameras.get()));
    }
    if(m_Fps.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("fps")), m_Fps.get()));
    }
    if(m_Robot_type.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("robot_type")), m_Robot_type.get()));
    }
    if(m_Action_dim.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("action_dim")), m_Action_dim.get()));
    }
    if(m_State_dim.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("state_dim")), m_State_dim.get()));
    }
    if(m_Created_atIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("created_at")), m_Created_at));
    }
    if(m_Updated_atIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("updated_at")), m_Updated_at));
    }
    if(m_Created_by.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("created_by")), m_Created_by.get()));
    }
    if(m_Updated_by.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("updated_by")), m_Updated_by.get()));
    }
}

bool DatasetSchema::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("uuid"))))
    {
        utility::string_t refVal_setUuid;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("uuid"))), refVal_setUuid );
        setUuid(refVal_setUuid);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        utility::string_t refVal_setName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("name"))), refVal_setName );
        setName(refVal_setName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("episodes"))))
    {
        std::vector<utility::string_t> refVal_setEpisodes;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("episodes"))), refVal_setEpisodes );
        setEpisodes(refVal_setEpisodes);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("metadata"))))
    {
        std::map<utility::string_t, std::shared_ptr<AnyType>> refVal_setMetadata;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("metadata"))), refVal_setMetadata );
        setMetadata(refVal_setMetadata);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("processed_datasets"))))
    {
        std::vector<std::shared_ptr<ProcessedDatasetSchema>> refVal_setProcessedDatasets;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("processed_datasets"))), refVal_setProcessedDatasets );
        setProcessedDatasets(refVal_setProcessedDatasets);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("processing_status"))))
    {
        utility::string_t refVal_setProcessingStatus;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("processing_status"))), refVal_setProcessingStatus );
        setProcessingStatus(refVal_setProcessingStatus);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("is_ready"))))
    {
        bool refVal_setIsReady;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("is_ready"))), refVal_setIsReady );
        setIsReady(refVal_setIsReady);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("is_imported"))))
    {
        bool refVal_setIsImported;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("is_imported"))), refVal_setIsImported );
        setIsImported(refVal_setIsImported);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("source"))))
    {
        utility::string_t refVal_setSource;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("source"))), refVal_setSource );
        setSource(refVal_setSource);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("source_format"))))
    {
        utility::string_t refVal_setSourceFormat;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("source_format"))), refVal_setSourceFormat );
        setSourceFormat(refVal_setSourceFormat);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("slug"))))
    {
        utility::string_t refVal_setSlug;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("slug"))), refVal_setSlug );
        setSlug(refVal_setSlug);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("visibility"))))
    {
        utility::string_t refVal_setVisibility;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("visibility"))), refVal_setVisibility );
        setVisibility(refVal_setVisibility);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("total_episodes"))))
    {
        int32_t refVal_setTotalEpisodes;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("total_episodes"))), refVal_setTotalEpisodes );
        setTotalEpisodes(refVal_setTotalEpisodes);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("processed_episodes"))))
    {
        int32_t refVal_setProcessedEpisodes;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("processed_episodes"))), refVal_setProcessedEpisodes );
        setProcessedEpisodes(refVal_setProcessedEpisodes);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("failed_episodes"))))
    {
        int32_t refVal_setFailedEpisodes;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("failed_episodes"))), refVal_setFailedEpisodes );
        setFailedEpisodes(refVal_setFailedEpisodes);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("failed_episode_uuids"))))
    {
        std::vector<utility::string_t> refVal_setFailedEpisodeUuids;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("failed_episode_uuids"))), refVal_setFailedEpisodeUuids );
        setFailedEpisodeUuids(refVal_setFailedEpisodeUuids);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("cameras"))))
    {
        std::vector<utility::string_t> refVal_setCameras;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("cameras"))), refVal_setCameras );
        setCameras(refVal_setCameras);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("fps"))))
    {
        int32_t refVal_setFps;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("fps"))), refVal_setFps );
        setFps(refVal_setFps);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("robot_type"))))
    {
        utility::string_t refVal_setRobotType;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("robot_type"))), refVal_setRobotType );
        setRobotType(refVal_setRobotType);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("action_dim"))))
    {
        int32_t refVal_setActionDim;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("action_dim"))), refVal_setActionDim );
        setActionDim(refVal_setActionDim);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("state_dim"))))
    {
        int32_t refVal_setStateDim;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("state_dim"))), refVal_setStateDim );
        setStateDim(refVal_setStateDim);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("created_at"))))
    {
        utility::datetime refVal_setCreatedAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("created_at"))), refVal_setCreatedAt );
        setCreatedAt(refVal_setCreatedAt);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("updated_at"))))
    {
        utility::datetime refVal_setUpdatedAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("updated_at"))), refVal_setUpdatedAt );
        setUpdatedAt(refVal_setUpdatedAt);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("created_by"))))
    {
        utility::string_t refVal_setCreatedBy;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("created_by"))), refVal_setCreatedBy );
        setCreatedBy(refVal_setCreatedBy);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("updated_by"))))
    {
        utility::string_t refVal_setUpdatedBy;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("updated_by"))), refVal_setUpdatedBy );
        setUpdatedBy(refVal_setUpdatedBy);
    }
    return ok;
}


utility::string_t DatasetSchema::getUuid() const
{
    return m_Uuid;
}


void DatasetSchema::setUuid(const utility::string_t& value)
{
    m_Uuid = value;
    m_UuidIsSet = true;
}

bool DatasetSchema::uuidIsSet() const
{
    return m_UuidIsSet;
}

void DatasetSchema::unsetUuid()
{
    m_UuidIsSet = false;
}
utility::string_t DatasetSchema::getName() const
{
    return m_Name.get();
}


void DatasetSchema::setName(const utility::string_t& value)
{
    m_Name = value;
}

bool DatasetSchema::nameIsSet() const
{
    return m_Name.has_value();
}

void DatasetSchema::unsetName()
{
    m_Name.reset();
}
std::vector<utility::string_t> DatasetSchema::getEpisodes() const
{
    return m_Episodes;
}


void DatasetSchema::setEpisodes(const std::vector<utility::string_t>& value)
{
    m_Episodes = value;
    m_EpisodesIsSet = true;
}

bool DatasetSchema::episodesIsSet() const
{
    return m_EpisodesIsSet;
}

void DatasetSchema::unsetEpisodes()
{
    m_EpisodesIsSet = false;
}
std::map<utility::string_t, std::shared_ptr<AnyType>> DatasetSchema::getMetadata() const
{
    return m_Metadata;
}


void DatasetSchema::setMetadata(const std::map<utility::string_t, std::shared_ptr<AnyType>>& value)
{
    m_Metadata = value;
    m_MetadataIsSet = true;
}

bool DatasetSchema::metadataIsSet() const
{
    return m_MetadataIsSet;
}

void DatasetSchema::unsetMetadata()
{
    m_MetadataIsSet = false;
}
std::vector<std::shared_ptr<ProcessedDatasetSchema>> DatasetSchema::getProcessedDatasets() const
{
    return m_Processed_datasets;
}


void DatasetSchema::setProcessedDatasets(const std::vector<std::shared_ptr<ProcessedDatasetSchema>>& value)
{
    m_Processed_datasets = value;
    m_Processed_datasetsIsSet = true;
}

bool DatasetSchema::processedDatasetsIsSet() const
{
    return m_Processed_datasetsIsSet;
}

void DatasetSchema::unsetProcessed_datasets()
{
    m_Processed_datasetsIsSet = false;
}
utility::string_t DatasetSchema::getProcessingStatus() const
{
    return m_Processing_status;
}


void DatasetSchema::setProcessingStatus(const utility::string_t& value)
{
    m_Processing_status = value;
    m_Processing_statusIsSet = true;
}

bool DatasetSchema::processingStatusIsSet() const
{
    return m_Processing_statusIsSet;
}

void DatasetSchema::unsetProcessing_status()
{
    m_Processing_statusIsSet = false;
}
bool DatasetSchema::isIsReady() const
{
    return m_Is_ready;
}

void DatasetSchema::setIsReady(bool value)
{
    m_Is_ready = value;
    m_Is_readyIsSet = true;
}

bool DatasetSchema::isReadyIsSet() const
{
    return m_Is_readyIsSet;
}

void DatasetSchema::unsetIs_ready()
{
    m_Is_readyIsSet = false;
}
bool DatasetSchema::isIsImported() const
{
    return m_Is_imported;
}

void DatasetSchema::setIsImported(bool value)
{
    m_Is_imported = value;
    m_Is_importedIsSet = true;
}

bool DatasetSchema::isImportedIsSet() const
{
    return m_Is_importedIsSet;
}

void DatasetSchema::unsetIs_imported()
{
    m_Is_importedIsSet = false;
}
utility::string_t DatasetSchema::getSource() const
{
    return m_Source.get();
}


void DatasetSchema::setSource(const utility::string_t& value)
{
    m_Source = value;
}

bool DatasetSchema::sourceIsSet() const
{
    return m_Source.has_value();
}

void DatasetSchema::unsetSource()
{
    m_Source.reset();
}
utility::string_t DatasetSchema::getSourceFormat() const
{
    return m_Source_format.get();
}


void DatasetSchema::setSourceFormat(const utility::string_t& value)
{
    m_Source_format = value;
}

bool DatasetSchema::sourceFormatIsSet() const
{
    return m_Source_format.has_value();
}

void DatasetSchema::unsetSource_format()
{
    m_Source_format.reset();
}
utility::string_t DatasetSchema::getSlug() const
{
    return m_Slug.get();
}


void DatasetSchema::setSlug(const utility::string_t& value)
{
    m_Slug = value;
}

bool DatasetSchema::slugIsSet() const
{
    return m_Slug.has_value();
}

void DatasetSchema::unsetSlug()
{
    m_Slug.reset();
}
utility::string_t DatasetSchema::getVisibility() const
{
    return m_Visibility;
}


void DatasetSchema::setVisibility(const utility::string_t& value)
{
    m_Visibility = value;
    m_VisibilityIsSet = true;
}

bool DatasetSchema::visibilityIsSet() const
{
    return m_VisibilityIsSet;
}

void DatasetSchema::unsetVisibility()
{
    m_VisibilityIsSet = false;
}
int32_t DatasetSchema::getTotalEpisodes() const
{
    return m_Total_episodes;
}

void DatasetSchema::setTotalEpisodes(int32_t value)
{
    m_Total_episodes = value;
    m_Total_episodesIsSet = true;
}

bool DatasetSchema::totalEpisodesIsSet() const
{
    return m_Total_episodesIsSet;
}

void DatasetSchema::unsetTotal_episodes()
{
    m_Total_episodesIsSet = false;
}
int32_t DatasetSchema::getProcessedEpisodes() const
{
    return m_Processed_episodes;
}

void DatasetSchema::setProcessedEpisodes(int32_t value)
{
    m_Processed_episodes = value;
    m_Processed_episodesIsSet = true;
}

bool DatasetSchema::processedEpisodesIsSet() const
{
    return m_Processed_episodesIsSet;
}

void DatasetSchema::unsetProcessed_episodes()
{
    m_Processed_episodesIsSet = false;
}
int32_t DatasetSchema::getFailedEpisodes() const
{
    return m_Failed_episodes;
}

void DatasetSchema::setFailedEpisodes(int32_t value)
{
    m_Failed_episodes = value;
    m_Failed_episodesIsSet = true;
}

bool DatasetSchema::failedEpisodesIsSet() const
{
    return m_Failed_episodesIsSet;
}

void DatasetSchema::unsetFailed_episodes()
{
    m_Failed_episodesIsSet = false;
}
std::vector<utility::string_t> DatasetSchema::getFailedEpisodeUuids() const
{
    return m_Failed_episode_uuids;
}


void DatasetSchema::setFailedEpisodeUuids(const std::vector<utility::string_t>& value)
{
    m_Failed_episode_uuids = value;
    m_Failed_episode_uuidsIsSet = true;
}

bool DatasetSchema::failedEpisodeUuidsIsSet() const
{
    return m_Failed_episode_uuidsIsSet;
}

void DatasetSchema::unsetFailed_episode_uuids()
{
    m_Failed_episode_uuidsIsSet = false;
}
std::vector<utility::string_t> DatasetSchema::getCameras() const
{
    return m_Cameras.get();
}


void DatasetSchema::setCameras(const std::vector<utility::string_t>& value)
{
    m_Cameras = value;
}

bool DatasetSchema::camerasIsSet() const
{
    return m_Cameras.has_value();
}

void DatasetSchema::unsetCameras()
{
    m_Cameras.reset();
}
int32_t DatasetSchema::getFps() const
{
    return m_Fps.get();
}

void DatasetSchema::setFps(int32_t value)
{
    m_Fps = value;
}

bool DatasetSchema::fpsIsSet() const
{
    return m_Fps.has_value();
}

void DatasetSchema::unsetFps()
{
    m_Fps.reset();
}
utility::string_t DatasetSchema::getRobotType() const
{
    return m_Robot_type.get();
}


void DatasetSchema::setRobotType(const utility::string_t& value)
{
    m_Robot_type = value;
}

bool DatasetSchema::robotTypeIsSet() const
{
    return m_Robot_type.has_value();
}

void DatasetSchema::unsetRobot_type()
{
    m_Robot_type.reset();
}
int32_t DatasetSchema::getActionDim() const
{
    return m_Action_dim.get();
}

void DatasetSchema::setActionDim(int32_t value)
{
    m_Action_dim = value;
}

bool DatasetSchema::actionDimIsSet() const
{
    return m_Action_dim.has_value();
}

void DatasetSchema::unsetAction_dim()
{
    m_Action_dim.reset();
}
int32_t DatasetSchema::getStateDim() const
{
    return m_State_dim.get();
}

void DatasetSchema::setStateDim(int32_t value)
{
    m_State_dim = value;
}

bool DatasetSchema::stateDimIsSet() const
{
    return m_State_dim.has_value();
}

void DatasetSchema::unsetState_dim()
{
    m_State_dim.reset();
}
utility::datetime DatasetSchema::getCreatedAt() const
{
    return m_Created_at;
}


void DatasetSchema::setCreatedAt(const utility::datetime& value)
{
    m_Created_at = value;
    m_Created_atIsSet = true;
}

bool DatasetSchema::createdAtIsSet() const
{
    return m_Created_atIsSet;
}

void DatasetSchema::unsetCreated_at()
{
    m_Created_atIsSet = false;
}
utility::datetime DatasetSchema::getUpdatedAt() const
{
    return m_Updated_at;
}


void DatasetSchema::setUpdatedAt(const utility::datetime& value)
{
    m_Updated_at = value;
    m_Updated_atIsSet = true;
}

bool DatasetSchema::updatedAtIsSet() const
{
    return m_Updated_atIsSet;
}

void DatasetSchema::unsetUpdated_at()
{
    m_Updated_atIsSet = false;
}
utility::string_t DatasetSchema::getCreatedBy() const
{
    return m_Created_by.get();
}


void DatasetSchema::setCreatedBy(const utility::string_t& value)
{
    m_Created_by = value;
}

bool DatasetSchema::createdByIsSet() const
{
    return m_Created_by.has_value();
}

void DatasetSchema::unsetCreated_by()
{
    m_Created_by.reset();
}
utility::string_t DatasetSchema::getUpdatedBy() const
{
    return m_Updated_by.get();
}


void DatasetSchema::setUpdatedBy(const utility::string_t& value)
{
    m_Updated_by = value;
}

bool DatasetSchema::updatedByIsSet() const
{
    return m_Updated_by.has_value();
}

void DatasetSchema::unsetUpdated_by()
{
    m_Updated_by.reset();
}

}
}
}
}


