/**
 * Cyberwave API
 * Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/EnvironmentSnapshotSchema.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

EnvironmentSnapshotSchema::EnvironmentSnapshotSchema()
{
    m_Uuid = utility::conversions::to_string_t("");
    m_UuidIsSet = false;
    m_Name = utility::conversions::to_string_t("");
    m_NameIsSet = false;
    m_Description = utility::conversions::to_string_t("");
    m_DescriptionIsSet = false;
    m_Created_at = utility::datetime();
    m_Created_atIsSet = false;
    m_Updated_at = utility::datetime();
    m_Updated_atIsSet = false;
    m_Created_by = utility::conversions::to_string_t("");
    m_Created_byIsSet = false;
    m_Updated_by = utility::conversions::to_string_t("");
    m_Updated_byIsSet = false;
    m_Environment = utility::conversions::to_string_t("");
    m_EnvironmentIsSet = false;
    m_SnapshotIsSet = false;
    m_Snapshot_hash_key = utility::conversions::to_string_t("");
    m_Snapshot_hash_keyIsSet = false;
}

EnvironmentSnapshotSchema::~EnvironmentSnapshotSchema()
{
}

void EnvironmentSnapshotSchema::validate()
{
    // TODO: implement validation
}

web::json::value EnvironmentSnapshotSchema::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_UuidIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("uuid"))] = ModelBase::toJson(m_Uuid);
    }
    if(m_NameIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("name"))] = ModelBase::toJson(m_Name);
    }
    if(m_DescriptionIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("description"))] = ModelBase::toJson(m_Description);
    }
    if(m_Created_atIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("created_at"))] = ModelBase::toJson(m_Created_at);
    }
    if(m_Updated_atIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("updated_at"))] = ModelBase::toJson(m_Updated_at);
    }
    if(m_Created_byIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("created_by"))] = ModelBase::toJson(m_Created_by);
    }
    if(m_Updated_byIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("updated_by"))] = ModelBase::toJson(m_Updated_by);
    }
    if(m_EnvironmentIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("environment"))] = ModelBase::toJson(m_Environment);
    }
    if(m_SnapshotIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("snapshot"))] = ModelBase::toJson(m_Snapshot);
    }
    if(m_Snapshot_hash_keyIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("snapshot_hash_key"))] = ModelBase::toJson(m_Snapshot_hash_key);
    }

    return val;
}

bool EnvironmentSnapshotSchema::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("uuid"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("uuid")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setUuid;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUuid);
            setUuid(refVal_setUuid);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setName);
            setName(refVal_setName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("description"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("description")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setDescription;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDescription);
            setDescription(refVal_setDescription);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("created_at"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("created_at")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setCreatedAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCreatedAt);
            setCreatedAt(refVal_setCreatedAt);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("updated_at"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("updated_at")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setUpdatedAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUpdatedAt);
            setUpdatedAt(refVal_setUpdatedAt);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("created_by"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("created_by")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCreatedBy;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCreatedBy);
            setCreatedBy(refVal_setCreatedBy);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("updated_by"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("updated_by")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setUpdatedBy;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUpdatedBy);
            setUpdatedBy(refVal_setUpdatedBy);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("environment"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("environment")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setEnvironment;
            ok &= ModelBase::fromJson(fieldValue, refVal_setEnvironment);
            setEnvironment(refVal_setEnvironment);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("snapshot"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("snapshot")));
        if(!fieldValue.is_null())
        {
            std::map<utility::string_t, std::shared_ptr<AnyType>> refVal_setSnapshot;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSnapshot);
            setSnapshot(refVal_setSnapshot);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("snapshot_hash_key"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("snapshot_hash_key")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setSnapshotHashKey;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSnapshotHashKey);
            setSnapshotHashKey(refVal_setSnapshotHashKey);
            
        }
    }
    return ok;
}

void EnvironmentSnapshotSchema::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_UuidIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("uuid")), m_Uuid));
    }
    if(m_NameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("name")), m_Name));
    }
    if(m_DescriptionIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("description")), m_Description));
    }
    if(m_Created_atIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("created_at")), m_Created_at));
    }
    if(m_Updated_atIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("updated_at")), m_Updated_at));
    }
    if(m_Created_byIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("created_by")), m_Created_by));
    }
    if(m_Updated_byIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("updated_by")), m_Updated_by));
    }
    if(m_EnvironmentIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("environment")), m_Environment));
    }
    if(m_SnapshotIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("snapshot")), m_Snapshot));
    }
    if(m_Snapshot_hash_keyIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("snapshot_hash_key")), m_Snapshot_hash_key));
    }
}

bool EnvironmentSnapshotSchema::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("uuid"))))
    {
        utility::string_t refVal_setUuid;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("uuid"))), refVal_setUuid );
        setUuid(refVal_setUuid);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        utility::string_t refVal_setName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("name"))), refVal_setName );
        setName(refVal_setName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("description"))))
    {
        utility::string_t refVal_setDescription;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("description"))), refVal_setDescription );
        setDescription(refVal_setDescription);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("created_at"))))
    {
        utility::datetime refVal_setCreatedAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("created_at"))), refVal_setCreatedAt );
        setCreatedAt(refVal_setCreatedAt);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("updated_at"))))
    {
        utility::datetime refVal_setUpdatedAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("updated_at"))), refVal_setUpdatedAt );
        setUpdatedAt(refVal_setUpdatedAt);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("created_by"))))
    {
        utility::string_t refVal_setCreatedBy;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("created_by"))), refVal_setCreatedBy );
        setCreatedBy(refVal_setCreatedBy);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("updated_by"))))
    {
        utility::string_t refVal_setUpdatedBy;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("updated_by"))), refVal_setUpdatedBy );
        setUpdatedBy(refVal_setUpdatedBy);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("environment"))))
    {
        utility::string_t refVal_setEnvironment;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("environment"))), refVal_setEnvironment );
        setEnvironment(refVal_setEnvironment);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("snapshot"))))
    {
        std::map<utility::string_t, std::shared_ptr<AnyType>> refVal_setSnapshot;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("snapshot"))), refVal_setSnapshot );
        setSnapshot(refVal_setSnapshot);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("snapshot_hash_key"))))
    {
        utility::string_t refVal_setSnapshotHashKey;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("snapshot_hash_key"))), refVal_setSnapshotHashKey );
        setSnapshotHashKey(refVal_setSnapshotHashKey);
    }
    return ok;
}


utility::string_t EnvironmentSnapshotSchema::getUuid() const
{
    return m_Uuid;
}


void EnvironmentSnapshotSchema::setUuid(const utility::string_t& value)
{
    m_Uuid = value;
    m_UuidIsSet = true;
}

bool EnvironmentSnapshotSchema::uuidIsSet() const
{
    return m_UuidIsSet;
}

void EnvironmentSnapshotSchema::unsetUuid()
{
    m_UuidIsSet = false;
}
utility::string_t EnvironmentSnapshotSchema::getName() const
{
    return m_Name;
}


void EnvironmentSnapshotSchema::setName(const utility::string_t& value)
{
    m_Name = value;
    m_NameIsSet = true;
}

bool EnvironmentSnapshotSchema::nameIsSet() const
{
    return m_NameIsSet;
}

void EnvironmentSnapshotSchema::unsetName()
{
    m_NameIsSet = false;
}
utility::string_t EnvironmentSnapshotSchema::getDescription() const
{
    return m_Description;
}


void EnvironmentSnapshotSchema::setDescription(const utility::string_t& value)
{
    m_Description = value;
    m_DescriptionIsSet = true;
}

bool EnvironmentSnapshotSchema::descriptionIsSet() const
{
    return m_DescriptionIsSet;
}

void EnvironmentSnapshotSchema::unsetDescription()
{
    m_DescriptionIsSet = false;
}
utility::datetime EnvironmentSnapshotSchema::getCreatedAt() const
{
    return m_Created_at;
}


void EnvironmentSnapshotSchema::setCreatedAt(const utility::datetime& value)
{
    m_Created_at = value;
    m_Created_atIsSet = true;
}

bool EnvironmentSnapshotSchema::createdAtIsSet() const
{
    return m_Created_atIsSet;
}

void EnvironmentSnapshotSchema::unsetCreated_at()
{
    m_Created_atIsSet = false;
}
utility::datetime EnvironmentSnapshotSchema::getUpdatedAt() const
{
    return m_Updated_at;
}


void EnvironmentSnapshotSchema::setUpdatedAt(const utility::datetime& value)
{
    m_Updated_at = value;
    m_Updated_atIsSet = true;
}

bool EnvironmentSnapshotSchema::updatedAtIsSet() const
{
    return m_Updated_atIsSet;
}

void EnvironmentSnapshotSchema::unsetUpdated_at()
{
    m_Updated_atIsSet = false;
}
utility::string_t EnvironmentSnapshotSchema::getCreatedBy() const
{
    return m_Created_by;
}


void EnvironmentSnapshotSchema::setCreatedBy(const utility::string_t& value)
{
    m_Created_by = value;
    m_Created_byIsSet = true;
}

bool EnvironmentSnapshotSchema::createdByIsSet() const
{
    return m_Created_byIsSet;
}

void EnvironmentSnapshotSchema::unsetCreated_by()
{
    m_Created_byIsSet = false;
}
utility::string_t EnvironmentSnapshotSchema::getUpdatedBy() const
{
    return m_Updated_by;
}


void EnvironmentSnapshotSchema::setUpdatedBy(const utility::string_t& value)
{
    m_Updated_by = value;
    m_Updated_byIsSet = true;
}

bool EnvironmentSnapshotSchema::updatedByIsSet() const
{
    return m_Updated_byIsSet;
}

void EnvironmentSnapshotSchema::unsetUpdated_by()
{
    m_Updated_byIsSet = false;
}
utility::string_t EnvironmentSnapshotSchema::getEnvironment() const
{
    return m_Environment;
}


void EnvironmentSnapshotSchema::setEnvironment(const utility::string_t& value)
{
    m_Environment = value;
    m_EnvironmentIsSet = true;
}

bool EnvironmentSnapshotSchema::environmentIsSet() const
{
    return m_EnvironmentIsSet;
}

void EnvironmentSnapshotSchema::unsetEnvironment()
{
    m_EnvironmentIsSet = false;
}
std::map<utility::string_t, std::shared_ptr<AnyType>> EnvironmentSnapshotSchema::getSnapshot() const
{
    return m_Snapshot;
}


void EnvironmentSnapshotSchema::setSnapshot(const std::map<utility::string_t, std::shared_ptr<AnyType>>& value)
{
    m_Snapshot = value;
    m_SnapshotIsSet = true;
}

bool EnvironmentSnapshotSchema::snapshotIsSet() const
{
    return m_SnapshotIsSet;
}

void EnvironmentSnapshotSchema::unsetSnapshot()
{
    m_SnapshotIsSet = false;
}
utility::string_t EnvironmentSnapshotSchema::getSnapshotHashKey() const
{
    return m_Snapshot_hash_key;
}


void EnvironmentSnapshotSchema::setSnapshotHashKey(const utility::string_t& value)
{
    m_Snapshot_hash_key = value;
    m_Snapshot_hash_keyIsSet = true;
}

bool EnvironmentSnapshotSchema::snapshotHashKeyIsSet() const
{
    return m_Snapshot_hash_keyIsSet;
}

void EnvironmentSnapshotSchema::unsetSnapshot_hash_key()
{
    m_Snapshot_hash_keyIsSet = false;
}

}
}
}
}


