/**
 * Cyberwave API
 * Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.24.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/HardwareOrderLineItemCreateSchema.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

HardwareOrderLineItemCreateSchema::HardwareOrderLineItemCreateSchema()
{
    m_Asset_uuid = utility::conversions::to_string_t("");
    m_Asset_uuidIsSet = false;
    m_Quantity = 0;
    m_QuantityIsSet = false;
}

HardwareOrderLineItemCreateSchema::~HardwareOrderLineItemCreateSchema()
{
}

void HardwareOrderLineItemCreateSchema::validate()
{
    // TODO: implement validation
}

web::json::value HardwareOrderLineItemCreateSchema::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_Asset_uuidIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("asset_uuid"))] = ModelBase::toJson(m_Asset_uuid);
    }
    if(m_QuantityIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("quantity"))] = ModelBase::toJson(m_Quantity);
    }

    return val;
}

bool HardwareOrderLineItemCreateSchema::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("asset_uuid"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("asset_uuid")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setAssetUuid;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAssetUuid);
            setAssetUuid(refVal_setAssetUuid);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("quantity"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("quantity")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setQuantity;
            ok &= ModelBase::fromJson(fieldValue, refVal_setQuantity);
            setQuantity(refVal_setQuantity);
            
        }
    }
    return ok;
}

void HardwareOrderLineItemCreateSchema::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_Asset_uuidIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("asset_uuid")), m_Asset_uuid));
    }
    if(m_QuantityIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("quantity")), m_Quantity));
    }
}

bool HardwareOrderLineItemCreateSchema::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("asset_uuid"))))
    {
        utility::string_t refVal_setAssetUuid;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("asset_uuid"))), refVal_setAssetUuid );
        setAssetUuid(refVal_setAssetUuid);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("quantity"))))
    {
        int32_t refVal_setQuantity;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("quantity"))), refVal_setQuantity );
        setQuantity(refVal_setQuantity);
    }
    return ok;
}


utility::string_t HardwareOrderLineItemCreateSchema::getAssetUuid() const
{
    return m_Asset_uuid;
}


void HardwareOrderLineItemCreateSchema::setAssetUuid(const utility::string_t& value)
{
    m_Asset_uuid = value;
    m_Asset_uuidIsSet = true;
}

bool HardwareOrderLineItemCreateSchema::assetUuidIsSet() const
{
    return m_Asset_uuidIsSet;
}

void HardwareOrderLineItemCreateSchema::unsetAsset_uuid()
{
    m_Asset_uuidIsSet = false;
}
int32_t HardwareOrderLineItemCreateSchema::getQuantity() const
{
    return m_Quantity;
}

void HardwareOrderLineItemCreateSchema::setQuantity(int32_t value)
{
    m_Quantity = value;
    m_QuantityIsSet = true;
}

bool HardwareOrderLineItemCreateSchema::quantityIsSet() const
{
    return m_QuantityIsSet;
}

void HardwareOrderLineItemCreateSchema::unsetQuantity()
{
    m_QuantityIsSet = false;
}

}
}
}
}


