/**
 * Cyberwave API
 * Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.26.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/ItemInput.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

ItemInput::ItemInput()
{
    m_Workspace_uuid = utility::conversions::to_string_t("");
    m_Workspace_uuidIsSet = false;
    m_Name = utility::conversions::to_string_t("");
    m_NameIsSet = false;
    m_Serial_number = utility::conversions::to_string_t("");
    m_Serial_numberIsSet = false;
    m_Location = utility::conversions::to_string_t("");
    m_LocationIsSet = false;
    m_Condition = utility::conversions::to_string_t("");
    m_ConditionIsSet = false;
    m_StatusIsSet = false;
}

ItemInput::~ItemInput()
{
}

void ItemInput::validate()
{
    // TODO: implement validation
}

web::json::value ItemInput::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_Workspace_uuidIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("workspace_uuid"))] = ModelBase::toJson(m_Workspace_uuid);
    }
    if(m_NameIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("name"))] = ModelBase::toJson(m_Name);
    }
    if(m_Serial_numberIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("serial_number"))] = ModelBase::toJson(m_Serial_number);
    }
    if(m_LocationIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("location"))] = ModelBase::toJson(m_Location);
    }
    if(m_ConditionIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("condition"))] = ModelBase::toJson(m_Condition);
    }
    if(m_StatusIsSet)
    {
        
        utility::string_t refVal = fromStatusEnum(m_Status);
        val[utility::conversions::to_string_t(_XPLATSTR("status"))] = ModelBase::toJson(refVal);
        
    }
    if(m_Delivery_uuid.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("delivery_uuid"))] = ModelBase::toJson(m_Delivery_uuid.get());
    }
    if(m_Environment_uuid.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("environment_uuid"))] = ModelBase::toJson(m_Environment_uuid.get());
    }
    if(m_Custodian_uuid.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("custodian_uuid"))] = ModelBase::toJson(m_Custodian_uuid.get());
    }

    return val;
}

bool ItemInput::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("workspace_uuid"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("workspace_uuid")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setWorkspaceUuid;
            ok &= ModelBase::fromJson(fieldValue, refVal_setWorkspaceUuid);
            setWorkspaceUuid(refVal_setWorkspaceUuid);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setName);
            setName(refVal_setName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("serial_number"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("serial_number")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setSerialNumber;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSerialNumber);
            setSerialNumber(refVal_setSerialNumber);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("location"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("location")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setLocation;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLocation);
            setLocation(refVal_setLocation);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("condition"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("condition")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCondition;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCondition);
            setCondition(refVal_setCondition);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("status")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setStatus;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStatus);
            
            setStatus(toStatusEnum(refVal_setStatus));
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("delivery_uuid"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("delivery_uuid")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setDeliveryUuid;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDeliveryUuid);
            setDeliveryUuid(refVal_setDeliveryUuid);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("environment_uuid"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("environment_uuid")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setEnvironmentUuid;
            ok &= ModelBase::fromJson(fieldValue, refVal_setEnvironmentUuid);
            setEnvironmentUuid(refVal_setEnvironmentUuid);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("custodian_uuid"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("custodian_uuid")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCustodianUuid;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCustodianUuid);
            setCustodianUuid(refVal_setCustodianUuid);
            
        }
    }
    return ok;
}

void ItemInput::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_Workspace_uuidIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("workspace_uuid")), m_Workspace_uuid));
    }
    if(m_NameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("name")), m_Name));
    }
    if(m_Serial_numberIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("serial_number")), m_Serial_number));
    }
    if(m_LocationIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("location")), m_Location));
    }
    if(m_ConditionIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("condition")), m_Condition));
    }
    if(m_StatusIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("status")), fromStatusEnum(m_Status)));
    }
    if(m_Delivery_uuid.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("delivery_uuid")), m_Delivery_uuid.get()));
    }
    if(m_Environment_uuid.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("environment_uuid")), m_Environment_uuid.get()));
    }
    if(m_Custodian_uuid.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("custodian_uuid")), m_Custodian_uuid.get()));
    }
}

bool ItemInput::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("workspace_uuid"))))
    {
        utility::string_t refVal_setWorkspaceUuid;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("workspace_uuid"))), refVal_setWorkspaceUuid );
        setWorkspaceUuid(refVal_setWorkspaceUuid);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        utility::string_t refVal_setName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("name"))), refVal_setName );
        setName(refVal_setName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("serial_number"))))
    {
        utility::string_t refVal_setSerialNumber;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("serial_number"))), refVal_setSerialNumber );
        setSerialNumber(refVal_setSerialNumber);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("location"))))
    {
        utility::string_t refVal_setLocation;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("location"))), refVal_setLocation );
        setLocation(refVal_setLocation);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("condition"))))
    {
        utility::string_t refVal_setCondition;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("condition"))), refVal_setCondition );
        setCondition(refVal_setCondition);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        utility::string_t refVal_setStatus;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("status"))), refVal_setStatus );
        setStatus(toStatusEnum(refVal_setStatus));
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("delivery_uuid"))))
    {
        utility::string_t refVal_setDeliveryUuid;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("delivery_uuid"))), refVal_setDeliveryUuid );
        setDeliveryUuid(refVal_setDeliveryUuid);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("environment_uuid"))))
    {
        utility::string_t refVal_setEnvironmentUuid;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("environment_uuid"))), refVal_setEnvironmentUuid );
        setEnvironmentUuid(refVal_setEnvironmentUuid);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("custodian_uuid"))))
    {
        utility::string_t refVal_setCustodianUuid;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("custodian_uuid"))), refVal_setCustodianUuid );
        setCustodianUuid(refVal_setCustodianUuid);
    }
    return ok;
}

ItemInput::StatusEnum ItemInput::toStatusEnum(const utility::string_t& value) const
{
    
    if (value == utility::conversions::to_string_t("available")) {
        return StatusEnum::AVAILABLE;
    }
    
    if (value == utility::conversions::to_string_t("assigned")) {
        return StatusEnum::ASSIGNED;
    }
    
    if (value == utility::conversions::to_string_t("maintenance")) {
        return StatusEnum::MAINTENANCE;
    }
    
    if (value == utility::conversions::to_string_t("retired")) {
        return StatusEnum::RETIRED;
    }
    
    throw std::invalid_argument("Invalid value for conversion to StatusEnum");
}


const utility::string_t ItemInput::fromStatusEnum(const StatusEnum value) const
{
    switch(value)
    {
        
        case StatusEnum::AVAILABLE: return utility::conversions::to_string_t("available");
        
        case StatusEnum::ASSIGNED: return utility::conversions::to_string_t("assigned");
        
        case StatusEnum::MAINTENANCE: return utility::conversions::to_string_t("maintenance");
        
        case StatusEnum::RETIRED: return utility::conversions::to_string_t("retired");
        
    }
}


utility::string_t ItemInput::getWorkspaceUuid() const
{
    return m_Workspace_uuid;
}


void ItemInput::setWorkspaceUuid(const utility::string_t& value)
{
    m_Workspace_uuid = value;
    m_Workspace_uuidIsSet = true;
}

bool ItemInput::workspaceUuidIsSet() const
{
    return m_Workspace_uuidIsSet;
}

void ItemInput::unsetWorkspace_uuid()
{
    m_Workspace_uuidIsSet = false;
}
utility::string_t ItemInput::getName() const
{
    return m_Name;
}


void ItemInput::setName(const utility::string_t& value)
{
    m_Name = value;
    m_NameIsSet = true;
}

bool ItemInput::nameIsSet() const
{
    return m_NameIsSet;
}

void ItemInput::unsetName()
{
    m_NameIsSet = false;
}
utility::string_t ItemInput::getSerialNumber() const
{
    return m_Serial_number;
}


void ItemInput::setSerialNumber(const utility::string_t& value)
{
    m_Serial_number = value;
    m_Serial_numberIsSet = true;
}

bool ItemInput::serialNumberIsSet() const
{
    return m_Serial_numberIsSet;
}

void ItemInput::unsetSerial_number()
{
    m_Serial_numberIsSet = false;
}
utility::string_t ItemInput::getLocation() const
{
    return m_Location;
}


void ItemInput::setLocation(const utility::string_t& value)
{
    m_Location = value;
    m_LocationIsSet = true;
}

bool ItemInput::locationIsSet() const
{
    return m_LocationIsSet;
}

void ItemInput::unsetLocation()
{
    m_LocationIsSet = false;
}
utility::string_t ItemInput::getCondition() const
{
    return m_Condition;
}


void ItemInput::setCondition(const utility::string_t& value)
{
    m_Condition = value;
    m_ConditionIsSet = true;
}

bool ItemInput::conditionIsSet() const
{
    return m_ConditionIsSet;
}

void ItemInput::unsetCondition()
{
    m_ConditionIsSet = false;
}
ItemInput::StatusEnum ItemInput::getStatus() const
{
    return m_Status;
}


void ItemInput::setStatus(const StatusEnum value)
{
    m_Status = value;
    m_StatusIsSet = true;
}

bool ItemInput::statusIsSet() const
{
    return m_StatusIsSet;
}

void ItemInput::unsetStatus()
{
    m_StatusIsSet = false;
}
utility::string_t ItemInput::getDeliveryUuid() const
{
    return m_Delivery_uuid.get();
}


void ItemInput::setDeliveryUuid(const utility::string_t& value)
{
    m_Delivery_uuid = value;
}

bool ItemInput::deliveryUuidIsSet() const
{
    return m_Delivery_uuid.has_value();
}

void ItemInput::unsetDelivery_uuid()
{
    m_Delivery_uuid.reset();
}
utility::string_t ItemInput::getEnvironmentUuid() const
{
    return m_Environment_uuid.get();
}


void ItemInput::setEnvironmentUuid(const utility::string_t& value)
{
    m_Environment_uuid = value;
}

bool ItemInput::environmentUuidIsSet() const
{
    return m_Environment_uuid.has_value();
}

void ItemInput::unsetEnvironment_uuid()
{
    m_Environment_uuid.reset();
}
utility::string_t ItemInput::getCustodianUuid() const
{
    return m_Custodian_uuid.get();
}


void ItemInput::setCustodianUuid(const utility::string_t& value)
{
    m_Custodian_uuid = value;
}

bool ItemInput::custodianUuidIsSet() const
{
    return m_Custodian_uuid.has_value();
}

void ItemInput::unsetCustodian_uuid()
{
    m_Custodian_uuid.reset();
}

}
}
}
}


