/**
 * Cyberwave API
 * Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/LinkShareCreateSchema.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

LinkShareCreateSchema::LinkShareCreateSchema()
{
    m_Role_cap = utility::conversions::to_string_t("");
    m_Role_capIsSet = false;
}

LinkShareCreateSchema::~LinkShareCreateSchema()
{
}

void LinkShareCreateSchema::validate()
{
    // TODO: implement validation
}

web::json::value LinkShareCreateSchema::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_Role_capIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("role_cap"))] = ModelBase::toJson(m_Role_cap);
    }
    if(m_Expires_at.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("expires_at"))] = ModelBase::toJson(m_Expires_at.get());
    }

    return val;
}

bool LinkShareCreateSchema::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("role_cap"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("role_cap")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setRoleCap;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRoleCap);
            setRoleCap(refVal_setRoleCap);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("expires_at"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("expires_at")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setExpiresAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setExpiresAt);
            setExpiresAt(refVal_setExpiresAt);
            
        }
    }
    return ok;
}

void LinkShareCreateSchema::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_Role_capIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("role_cap")), m_Role_cap));
    }
    if(m_Expires_at.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("expires_at")), m_Expires_at.get()));
    }
}

bool LinkShareCreateSchema::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("role_cap"))))
    {
        utility::string_t refVal_setRoleCap;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("role_cap"))), refVal_setRoleCap );
        setRoleCap(refVal_setRoleCap);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("expires_at"))))
    {
        utility::string_t refVal_setExpiresAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("expires_at"))), refVal_setExpiresAt );
        setExpiresAt(refVal_setExpiresAt);
    }
    return ok;
}


utility::string_t LinkShareCreateSchema::getRoleCap() const
{
    return m_Role_cap;
}


void LinkShareCreateSchema::setRoleCap(const utility::string_t& value)
{
    m_Role_cap = value;
    m_Role_capIsSet = true;
}

bool LinkShareCreateSchema::roleCapIsSet() const
{
    return m_Role_capIsSet;
}

void LinkShareCreateSchema::unsetRole_cap()
{
    m_Role_capIsSet = false;
}
utility::string_t LinkShareCreateSchema::getExpiresAt() const
{
    return m_Expires_at.get();
}


void LinkShareCreateSchema::setExpiresAt(const utility::string_t& value)
{
    m_Expires_at = value;
}

bool LinkShareCreateSchema::expiresAtIsSet() const
{
    return m_Expires_at.has_value();
}

void LinkShareCreateSchema::unsetExpires_at()
{
    m_Expires_at.reset();
}

}
}
}
}


