/**
 * Cyberwave API
 * Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.26.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/MapCreateSchema.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

MapCreateSchema::MapCreateSchema()
{
    m_Map_typeIsSet = false;
}

MapCreateSchema::~MapCreateSchema()
{
}

void MapCreateSchema::validate()
{
    // TODO: implement validation
}

web::json::value MapCreateSchema::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_Twin_uuid.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("twin_uuid"))] = ModelBase::toJson(m_Twin_uuid.get());
    }
    if(m_Environment_uuid.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("environment_uuid"))] = ModelBase::toJson(m_Environment_uuid.get());
    }
    if(m_Map_typeIsSet)
    {
        
        utility::string_t refVal = fromMap_typeEnum(m_Map_type);
        val[utility::conversions::to_string_t(_XPLATSTR("map_type"))] = ModelBase::toJson(refVal);
        
    }
    if(m_Resolution.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("resolution"))] = ModelBase::toJson(m_Resolution.get());
    }
    if(m_Origin_x.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("origin_x"))] = ModelBase::toJson(m_Origin_x.get());
    }
    if(m_Origin_y.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("origin_y"))] = ModelBase::toJson(m_Origin_y.get());
    }
    if(m_Origin_z.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("origin_z"))] = ModelBase::toJson(m_Origin_z.get());
    }
    if(m_Origin_roll.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("origin_roll"))] = ModelBase::toJson(m_Origin_roll.get());
    }
    if(m_Origin_pitch.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("origin_pitch"))] = ModelBase::toJson(m_Origin_pitch.get());
    }
    if(m_Origin_yaw.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("origin_yaw"))] = ModelBase::toJson(m_Origin_yaw.get());
    }
    if(m_Metadata.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("metadata"))] = ModelBase::toJson(m_Metadata.get());
    }

    return val;
}

bool MapCreateSchema::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("twin_uuid"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("twin_uuid")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setTwinUuid;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTwinUuid);
            setTwinUuid(refVal_setTwinUuid);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("environment_uuid"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("environment_uuid")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setEnvironmentUuid;
            ok &= ModelBase::fromJson(fieldValue, refVal_setEnvironmentUuid);
            setEnvironmentUuid(refVal_setEnvironmentUuid);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("map_type"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("map_type")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setMapType;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMapType);
            
            setMapType(toMap_typeEnum(refVal_setMapType));
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("resolution"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("resolution")));
        if(!fieldValue.is_null())
        {
            double refVal_setResolution;
            ok &= ModelBase::fromJson(fieldValue, refVal_setResolution);
            setResolution(refVal_setResolution);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("origin_x"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("origin_x")));
        if(!fieldValue.is_null())
        {
            double refVal_setOriginX;
            ok &= ModelBase::fromJson(fieldValue, refVal_setOriginX);
            setOriginX(refVal_setOriginX);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("origin_y"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("origin_y")));
        if(!fieldValue.is_null())
        {
            double refVal_setOriginY;
            ok &= ModelBase::fromJson(fieldValue, refVal_setOriginY);
            setOriginY(refVal_setOriginY);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("origin_z"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("origin_z")));
        if(!fieldValue.is_null())
        {
            double refVal_setOriginZ;
            ok &= ModelBase::fromJson(fieldValue, refVal_setOriginZ);
            setOriginZ(refVal_setOriginZ);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("origin_roll"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("origin_roll")));
        if(!fieldValue.is_null())
        {
            double refVal_setOriginRoll;
            ok &= ModelBase::fromJson(fieldValue, refVal_setOriginRoll);
            setOriginRoll(refVal_setOriginRoll);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("origin_pitch"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("origin_pitch")));
        if(!fieldValue.is_null())
        {
            double refVal_setOriginPitch;
            ok &= ModelBase::fromJson(fieldValue, refVal_setOriginPitch);
            setOriginPitch(refVal_setOriginPitch);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("origin_yaw"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("origin_yaw")));
        if(!fieldValue.is_null())
        {
            double refVal_setOriginYaw;
            ok &= ModelBase::fromJson(fieldValue, refVal_setOriginYaw);
            setOriginYaw(refVal_setOriginYaw);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("metadata"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("metadata")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setMetadata;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMetadata);
            setMetadata(refVal_setMetadata);
            
        }
    }
    return ok;
}

void MapCreateSchema::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_Twin_uuid.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("twin_uuid")), m_Twin_uuid.get()));
    }
    if(m_Environment_uuid.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("environment_uuid")), m_Environment_uuid.get()));
    }
    if(m_Map_typeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("map_type")), fromMap_typeEnum(m_Map_type)));
    }
    if(m_Resolution.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("resolution")), m_Resolution.get()));
    }
    if(m_Origin_x.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("origin_x")), m_Origin_x.get()));
    }
    if(m_Origin_y.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("origin_y")), m_Origin_y.get()));
    }
    if(m_Origin_z.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("origin_z")), m_Origin_z.get()));
    }
    if(m_Origin_roll.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("origin_roll")), m_Origin_roll.get()));
    }
    if(m_Origin_pitch.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("origin_pitch")), m_Origin_pitch.get()));
    }
    if(m_Origin_yaw.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("origin_yaw")), m_Origin_yaw.get()));
    }
    if(m_Metadata.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("metadata")), m_Metadata.get()));
    }
}

bool MapCreateSchema::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("twin_uuid"))))
    {
        utility::string_t refVal_setTwinUuid;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("twin_uuid"))), refVal_setTwinUuid );
        setTwinUuid(refVal_setTwinUuid);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("environment_uuid"))))
    {
        utility::string_t refVal_setEnvironmentUuid;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("environment_uuid"))), refVal_setEnvironmentUuid );
        setEnvironmentUuid(refVal_setEnvironmentUuid);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("map_type"))))
    {
        utility::string_t refVal_setMapType;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("map_type"))), refVal_setMapType );
        setMapType(toMap_typeEnum(refVal_setMapType));
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("resolution"))))
    {
        double refVal_setResolution;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("resolution"))), refVal_setResolution );
        setResolution(refVal_setResolution);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("origin_x"))))
    {
        double refVal_setOriginX;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("origin_x"))), refVal_setOriginX );
        setOriginX(refVal_setOriginX);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("origin_y"))))
    {
        double refVal_setOriginY;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("origin_y"))), refVal_setOriginY );
        setOriginY(refVal_setOriginY);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("origin_z"))))
    {
        double refVal_setOriginZ;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("origin_z"))), refVal_setOriginZ );
        setOriginZ(refVal_setOriginZ);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("origin_roll"))))
    {
        double refVal_setOriginRoll;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("origin_roll"))), refVal_setOriginRoll );
        setOriginRoll(refVal_setOriginRoll);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("origin_pitch"))))
    {
        double refVal_setOriginPitch;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("origin_pitch"))), refVal_setOriginPitch );
        setOriginPitch(refVal_setOriginPitch);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("origin_yaw"))))
    {
        double refVal_setOriginYaw;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("origin_yaw"))), refVal_setOriginYaw );
        setOriginYaw(refVal_setOriginYaw);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("metadata"))))
    {
        utility::string_t refVal_setMetadata;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("metadata"))), refVal_setMetadata );
        setMetadata(refVal_setMetadata);
    }
    return ok;
}

MapCreateSchema::Map_typeEnum MapCreateSchema::toMap_typeEnum(const utility::string_t& value) const
{
    
    if (value == utility::conversions::to_string_t("occupancy_grid")) {
        return Map_typeEnum::OCCUPANCY_GRID;
    }
    
    if (value == utility::conversions::to_string_t("point_cloud")) {
        return Map_typeEnum::POINT_CLOUD;
    }
    
    throw std::invalid_argument("Invalid value for conversion to Map_typeEnum");
}


const utility::string_t MapCreateSchema::fromMap_typeEnum(const Map_typeEnum value) const
{
    switch(value)
    {
        
        case Map_typeEnum::OCCUPANCY_GRID: return utility::conversions::to_string_t("occupancy_grid");
        
        case Map_typeEnum::POINT_CLOUD: return utility::conversions::to_string_t("point_cloud");
        
    }
}


utility::string_t MapCreateSchema::getTwinUuid() const
{
    return m_Twin_uuid.get();
}


void MapCreateSchema::setTwinUuid(const utility::string_t& value)
{
    m_Twin_uuid = value;
}

bool MapCreateSchema::twinUuidIsSet() const
{
    return m_Twin_uuid.has_value();
}

void MapCreateSchema::unsetTwin_uuid()
{
    m_Twin_uuid.reset();
}
utility::string_t MapCreateSchema::getEnvironmentUuid() const
{
    return m_Environment_uuid.get();
}


void MapCreateSchema::setEnvironmentUuid(const utility::string_t& value)
{
    m_Environment_uuid = value;
}

bool MapCreateSchema::environmentUuidIsSet() const
{
    return m_Environment_uuid.has_value();
}

void MapCreateSchema::unsetEnvironment_uuid()
{
    m_Environment_uuid.reset();
}
MapCreateSchema::Map_typeEnum MapCreateSchema::getMapType() const
{
    return m_Map_type;
}


void MapCreateSchema::setMapType(const Map_typeEnum value)
{
    m_Map_type = value;
    m_Map_typeIsSet = true;
}

bool MapCreateSchema::mapTypeIsSet() const
{
    return m_Map_typeIsSet;
}

void MapCreateSchema::unsetMap_type()
{
    m_Map_typeIsSet = false;
}
double MapCreateSchema::getResolution() const
{
    return m_Resolution.get();
}

void MapCreateSchema::setResolution(double value)
{
    m_Resolution = value;
}

bool MapCreateSchema::resolutionIsSet() const
{
    return m_Resolution.has_value();
}

void MapCreateSchema::unsetResolution()
{
    m_Resolution.reset();
}
double MapCreateSchema::getOriginX() const
{
    return m_Origin_x.get();
}

void MapCreateSchema::setOriginX(double value)
{
    m_Origin_x = value;
}

bool MapCreateSchema::originXIsSet() const
{
    return m_Origin_x.has_value();
}

void MapCreateSchema::unsetOrigin_x()
{
    m_Origin_x.reset();
}
double MapCreateSchema::getOriginY() const
{
    return m_Origin_y.get();
}

void MapCreateSchema::setOriginY(double value)
{
    m_Origin_y = value;
}

bool MapCreateSchema::originYIsSet() const
{
    return m_Origin_y.has_value();
}

void MapCreateSchema::unsetOrigin_y()
{
    m_Origin_y.reset();
}
double MapCreateSchema::getOriginZ() const
{
    return m_Origin_z.get();
}

void MapCreateSchema::setOriginZ(double value)
{
    m_Origin_z = value;
}

bool MapCreateSchema::originZIsSet() const
{
    return m_Origin_z.has_value();
}

void MapCreateSchema::unsetOrigin_z()
{
    m_Origin_z.reset();
}
double MapCreateSchema::getOriginRoll() const
{
    return m_Origin_roll.get();
}

void MapCreateSchema::setOriginRoll(double value)
{
    m_Origin_roll = value;
}

bool MapCreateSchema::originRollIsSet() const
{
    return m_Origin_roll.has_value();
}

void MapCreateSchema::unsetOrigin_roll()
{
    m_Origin_roll.reset();
}
double MapCreateSchema::getOriginPitch() const
{
    return m_Origin_pitch.get();
}

void MapCreateSchema::setOriginPitch(double value)
{
    m_Origin_pitch = value;
}

bool MapCreateSchema::originPitchIsSet() const
{
    return m_Origin_pitch.has_value();
}

void MapCreateSchema::unsetOrigin_pitch()
{
    m_Origin_pitch.reset();
}
double MapCreateSchema::getOriginYaw() const
{
    return m_Origin_yaw.get();
}

void MapCreateSchema::setOriginYaw(double value)
{
    m_Origin_yaw = value;
}

bool MapCreateSchema::originYawIsSet() const
{
    return m_Origin_yaw.has_value();
}

void MapCreateSchema::unsetOrigin_yaw()
{
    m_Origin_yaw.reset();
}
utility::string_t MapCreateSchema::getMetadata() const
{
    return m_Metadata.get();
}


void MapCreateSchema::setMetadata(const utility::string_t& value)
{
    m_Metadata = value;
}

bool MapCreateSchema::metadataIsSet() const
{
    return m_Metadata.has_value();
}

void MapCreateSchema::unsetMetadata()
{
    m_Metadata.reset();
}

}
}
}
}


