/**
 * Cyberwave API
 * Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.24.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/NotificationSettingsUpdateSchema.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

NotificationSettingsUpdateSchema::NotificationSettingsUpdateSchema()
{
}

NotificationSettingsUpdateSchema::~NotificationSettingsUpdateSchema()
{
}

void NotificationSettingsUpdateSchema::validate()
{
    // TODO: implement validation
}

web::json::value NotificationSettingsUpdateSchema::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_Email_notification.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("email_notification"))] = ModelBase::toJson(m_Email_notification.get());
    }
    if(m_Notify_on_marketing.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("notify_on_marketing"))] = ModelBase::toJson(m_Notify_on_marketing.get());
    }

    return val;
}

bool NotificationSettingsUpdateSchema::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("email_notification"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("email_notification")));
        if(!fieldValue.is_null())
        {
            bool refVal_setEmailNotification;
            ok &= ModelBase::fromJson(fieldValue, refVal_setEmailNotification);
            setEmailNotification(refVal_setEmailNotification);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("notify_on_marketing"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("notify_on_marketing")));
        if(!fieldValue.is_null())
        {
            bool refVal_setNotifyOnMarketing;
            ok &= ModelBase::fromJson(fieldValue, refVal_setNotifyOnMarketing);
            setNotifyOnMarketing(refVal_setNotifyOnMarketing);
            
        }
    }
    return ok;
}

void NotificationSettingsUpdateSchema::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_Email_notification.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("email_notification")), m_Email_notification.get()));
    }
    if(m_Notify_on_marketing.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("notify_on_marketing")), m_Notify_on_marketing.get()));
    }
}

bool NotificationSettingsUpdateSchema::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("email_notification"))))
    {
        bool refVal_setEmailNotification;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("email_notification"))), refVal_setEmailNotification );
        setEmailNotification(refVal_setEmailNotification);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("notify_on_marketing"))))
    {
        bool refVal_setNotifyOnMarketing;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("notify_on_marketing"))), refVal_setNotifyOnMarketing );
        setNotifyOnMarketing(refVal_setNotifyOnMarketing);
    }
    return ok;
}


bool NotificationSettingsUpdateSchema::isEmailNotification() const
{
    return m_Email_notification.get();
}

void NotificationSettingsUpdateSchema::setEmailNotification(bool value)
{
    m_Email_notification = value;
}

bool NotificationSettingsUpdateSchema::emailNotificationIsSet() const
{
    return m_Email_notification.has_value();
}

void NotificationSettingsUpdateSchema::unsetEmail_notification()
{
    m_Email_notification.reset();
}
bool NotificationSettingsUpdateSchema::isNotifyOnMarketing() const
{
    return m_Notify_on_marketing.get();
}

void NotificationSettingsUpdateSchema::setNotifyOnMarketing(bool value)
{
    m_Notify_on_marketing = value;
}

bool NotificationSettingsUpdateSchema::notifyOnMarketingIsSet() const
{
    return m_Notify_on_marketing.has_value();
}

void NotificationSettingsUpdateSchema::unsetNotify_on_marketing()
{
    m_Notify_on_marketing.reset();
}

}
}
}
}


