/**
 * Cyberwave API
 * Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.26.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/OrganizationWithWorkspacesSchema.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

OrganizationWithWorkspacesSchema::OrganizationWithWorkspacesSchema()
{
    m_Uuid = utility::conversions::to_string_t("");
    m_UuidIsSet = false;
    m_Name = utility::conversions::to_string_t("");
    m_NameIsSet = false;
    m_WorkspacesIsSet = false;
    m_Runs_today = 0;
    m_Runs_todayIsSet = false;
}

OrganizationWithWorkspacesSchema::~OrganizationWithWorkspacesSchema()
{
}

void OrganizationWithWorkspacesSchema::validate()
{
    // TODO: implement validation
}

web::json::value OrganizationWithWorkspacesSchema::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_UuidIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("uuid"))] = ModelBase::toJson(m_Uuid);
    }
    if(m_NameIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("name"))] = ModelBase::toJson(m_Name);
    }
    if(m_WorkspacesIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("workspaces"))] = ModelBase::toJson(m_Workspaces);
    }
    if(m_Runs_todayIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("runs_today"))] = ModelBase::toJson(m_Runs_today);
    }

    return val;
}

bool OrganizationWithWorkspacesSchema::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("uuid"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("uuid")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setUuid;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUuid);
            setUuid(refVal_setUuid);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setName);
            setName(refVal_setName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("workspaces"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("workspaces")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<WorkspaceSchema>> refVal_setWorkspaces;
            ok &= ModelBase::fromJson(fieldValue, refVal_setWorkspaces);
            setWorkspaces(refVal_setWorkspaces);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("runs_today"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("runs_today")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setRunsToday;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRunsToday);
            setRunsToday(refVal_setRunsToday);
            
        }
    }
    return ok;
}

void OrganizationWithWorkspacesSchema::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_UuidIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("uuid")), m_Uuid));
    }
    if(m_NameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("name")), m_Name));
    }
    if(m_WorkspacesIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("workspaces")), m_Workspaces));
    }
    if(m_Runs_todayIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("runs_today")), m_Runs_today));
    }
}

bool OrganizationWithWorkspacesSchema::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("uuid"))))
    {
        utility::string_t refVal_setUuid;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("uuid"))), refVal_setUuid );
        setUuid(refVal_setUuid);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        utility::string_t refVal_setName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("name"))), refVal_setName );
        setName(refVal_setName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("workspaces"))))
    {
        std::vector<std::shared_ptr<WorkspaceSchema>> refVal_setWorkspaces;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("workspaces"))), refVal_setWorkspaces );
        setWorkspaces(refVal_setWorkspaces);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("runs_today"))))
    {
        int32_t refVal_setRunsToday;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("runs_today"))), refVal_setRunsToday );
        setRunsToday(refVal_setRunsToday);
    }
    return ok;
}


utility::string_t OrganizationWithWorkspacesSchema::getUuid() const
{
    return m_Uuid;
}


void OrganizationWithWorkspacesSchema::setUuid(const utility::string_t& value)
{
    m_Uuid = value;
    m_UuidIsSet = true;
}

bool OrganizationWithWorkspacesSchema::uuidIsSet() const
{
    return m_UuidIsSet;
}

void OrganizationWithWorkspacesSchema::unsetUuid()
{
    m_UuidIsSet = false;
}
utility::string_t OrganizationWithWorkspacesSchema::getName() const
{
    return m_Name;
}


void OrganizationWithWorkspacesSchema::setName(const utility::string_t& value)
{
    m_Name = value;
    m_NameIsSet = true;
}

bool OrganizationWithWorkspacesSchema::nameIsSet() const
{
    return m_NameIsSet;
}

void OrganizationWithWorkspacesSchema::unsetName()
{
    m_NameIsSet = false;
}
std::vector<std::shared_ptr<WorkspaceSchema>> OrganizationWithWorkspacesSchema::getWorkspaces() const
{
    return m_Workspaces;
}


void OrganizationWithWorkspacesSchema::setWorkspaces(const std::vector<std::shared_ptr<WorkspaceSchema>>& value)
{
    m_Workspaces = value;
    m_WorkspacesIsSet = true;
}

bool OrganizationWithWorkspacesSchema::workspacesIsSet() const
{
    return m_WorkspacesIsSet;
}

void OrganizationWithWorkspacesSchema::unsetWorkspaces()
{
    m_WorkspacesIsSet = false;
}
int32_t OrganizationWithWorkspacesSchema::getRunsToday() const
{
    return m_Runs_today;
}

void OrganizationWithWorkspacesSchema::setRunsToday(int32_t value)
{
    m_Runs_today = value;
    m_Runs_todayIsSet = true;
}

bool OrganizationWithWorkspacesSchema::runsTodayIsSet() const
{
    return m_Runs_todayIsSet;
}

void OrganizationWithWorkspacesSchema::unsetRuns_today()
{
    m_Runs_todayIsSet = false;
}

}
}
}
}


