/**
 * Cyberwave API
 * Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.24.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/OrganizationCreditBlockResponseSchema.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

OrganizationCreditBlockResponseSchema::OrganizationCreditBlockResponseSchema()
{
    m_Organization_uuid = utility::conversions::to_string_t("");
    m_Organization_uuidIsSet = false;
    m_Status = utility::conversions::to_string_t("");
    m_StatusIsSet = false;
    m_Balance_credits = utility::conversions::to_string_t("");
    m_Balance_creditsIsSet = false;
    m_Manual_block = false;
    m_Manual_blockIsSet = false;
    m_Manual_block_reason = utility::conversions::to_string_t("");
    m_Manual_block_reasonIsSet = false;
}

OrganizationCreditBlockResponseSchema::~OrganizationCreditBlockResponseSchema()
{
}

void OrganizationCreditBlockResponseSchema::validate()
{
    // TODO: implement validation
}

web::json::value OrganizationCreditBlockResponseSchema::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_Organization_uuidIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("organization_uuid"))] = ModelBase::toJson(m_Organization_uuid);
    }
    if(m_StatusIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("status"))] = ModelBase::toJson(m_Status);
    }
    if(m_Balance_creditsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("balance_credits"))] = ModelBase::toJson(m_Balance_credits);
    }
    if(m_Manual_blockIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("manual_block"))] = ModelBase::toJson(m_Manual_block);
    }
    if(m_Manual_block_reasonIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("manual_block_reason"))] = ModelBase::toJson(m_Manual_block_reason);
    }

    return val;
}

bool OrganizationCreditBlockResponseSchema::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("organization_uuid"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("organization_uuid")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setOrganizationUuid;
            ok &= ModelBase::fromJson(fieldValue, refVal_setOrganizationUuid);
            setOrganizationUuid(refVal_setOrganizationUuid);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("status")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setStatus;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStatus);
            setStatus(refVal_setStatus);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("balance_credits"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("balance_credits")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setBalanceCredits;
            ok &= ModelBase::fromJson(fieldValue, refVal_setBalanceCredits);
            setBalanceCredits(refVal_setBalanceCredits);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("manual_block"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("manual_block")));
        if(!fieldValue.is_null())
        {
            bool refVal_setManualBlock;
            ok &= ModelBase::fromJson(fieldValue, refVal_setManualBlock);
            setManualBlock(refVal_setManualBlock);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("manual_block_reason"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("manual_block_reason")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setManualBlockReason;
            ok &= ModelBase::fromJson(fieldValue, refVal_setManualBlockReason);
            setManualBlockReason(refVal_setManualBlockReason);
            
        }
    }
    return ok;
}

void OrganizationCreditBlockResponseSchema::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_Organization_uuidIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("organization_uuid")), m_Organization_uuid));
    }
    if(m_StatusIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("status")), m_Status));
    }
    if(m_Balance_creditsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("balance_credits")), m_Balance_credits));
    }
    if(m_Manual_blockIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("manual_block")), m_Manual_block));
    }
    if(m_Manual_block_reasonIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("manual_block_reason")), m_Manual_block_reason));
    }
}

bool OrganizationCreditBlockResponseSchema::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("organization_uuid"))))
    {
        utility::string_t refVal_setOrganizationUuid;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("organization_uuid"))), refVal_setOrganizationUuid );
        setOrganizationUuid(refVal_setOrganizationUuid);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        utility::string_t refVal_setStatus;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("status"))), refVal_setStatus );
        setStatus(refVal_setStatus);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("balance_credits"))))
    {
        utility::string_t refVal_setBalanceCredits;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("balance_credits"))), refVal_setBalanceCredits );
        setBalanceCredits(refVal_setBalanceCredits);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("manual_block"))))
    {
        bool refVal_setManualBlock;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("manual_block"))), refVal_setManualBlock );
        setManualBlock(refVal_setManualBlock);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("manual_block_reason"))))
    {
        utility::string_t refVal_setManualBlockReason;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("manual_block_reason"))), refVal_setManualBlockReason );
        setManualBlockReason(refVal_setManualBlockReason);
    }
    return ok;
}


utility::string_t OrganizationCreditBlockResponseSchema::getOrganizationUuid() const
{
    return m_Organization_uuid;
}


void OrganizationCreditBlockResponseSchema::setOrganizationUuid(const utility::string_t& value)
{
    m_Organization_uuid = value;
    m_Organization_uuidIsSet = true;
}

bool OrganizationCreditBlockResponseSchema::organizationUuidIsSet() const
{
    return m_Organization_uuidIsSet;
}

void OrganizationCreditBlockResponseSchema::unsetOrganization_uuid()
{
    m_Organization_uuidIsSet = false;
}
utility::string_t OrganizationCreditBlockResponseSchema::getStatus() const
{
    return m_Status;
}


void OrganizationCreditBlockResponseSchema::setStatus(const utility::string_t& value)
{
    m_Status = value;
    m_StatusIsSet = true;
}

bool OrganizationCreditBlockResponseSchema::statusIsSet() const
{
    return m_StatusIsSet;
}

void OrganizationCreditBlockResponseSchema::unsetStatus()
{
    m_StatusIsSet = false;
}
utility::string_t OrganizationCreditBlockResponseSchema::getBalanceCredits() const
{
    return m_Balance_credits;
}


void OrganizationCreditBlockResponseSchema::setBalanceCredits(const utility::string_t& value)
{
    m_Balance_credits = value;
    m_Balance_creditsIsSet = true;
}

bool OrganizationCreditBlockResponseSchema::balanceCreditsIsSet() const
{
    return m_Balance_creditsIsSet;
}

void OrganizationCreditBlockResponseSchema::unsetBalance_credits()
{
    m_Balance_creditsIsSet = false;
}
bool OrganizationCreditBlockResponseSchema::isManualBlock() const
{
    return m_Manual_block;
}

void OrganizationCreditBlockResponseSchema::setManualBlock(bool value)
{
    m_Manual_block = value;
    m_Manual_blockIsSet = true;
}

bool OrganizationCreditBlockResponseSchema::manualBlockIsSet() const
{
    return m_Manual_blockIsSet;
}

void OrganizationCreditBlockResponseSchema::unsetManual_block()
{
    m_Manual_blockIsSet = false;
}
utility::string_t OrganizationCreditBlockResponseSchema::getManualBlockReason() const
{
    return m_Manual_block_reason;
}


void OrganizationCreditBlockResponseSchema::setManualBlockReason(const utility::string_t& value)
{
    m_Manual_block_reason = value;
    m_Manual_block_reasonIsSet = true;
}

bool OrganizationCreditBlockResponseSchema::manualBlockReasonIsSet() const
{
    return m_Manual_block_reasonIsSet;
}

void OrganizationCreditBlockResponseSchema::unsetManual_block_reason()
{
    m_Manual_block_reasonIsSet = false;
}

}
}
}
}


