/**
 * Cyberwave API
 * Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/OrganizationCreditAccountSchema.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

OrganizationCreditAccountSchema::OrganizationCreditAccountSchema()
{
    m_Organization_uuid = utility::conversions::to_string_t("");
    m_Organization_uuidIsSet = false;
    m_Balance_credits = utility::conversions::to_string_t("");
    m_Balance_creditsIsSet = false;
    m_Status = utility::conversions::to_string_t("");
    m_StatusIsSet = false;
    m_Warning_threshold_credits = utility::conversions::to_string_t("");
    m_Warning_threshold_creditsIsSet = false;
    m_Enforcement_enabled = false;
    m_Enforcement_enabledIsSet = false;
    m_RatesIsSet = false;
    m_Manual_block = false;
    m_Manual_blockIsSet = false;
    m_Manual_block_reason = utility::conversions::to_string_t("");
    m_Manual_block_reasonIsSet = false;
}

OrganizationCreditAccountSchema::~OrganizationCreditAccountSchema()
{
}

void OrganizationCreditAccountSchema::validate()
{
    // TODO: implement validation
}

web::json::value OrganizationCreditAccountSchema::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_Organization_uuidIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("organization_uuid"))] = ModelBase::toJson(m_Organization_uuid);
    }
    if(m_Balance_creditsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("balance_credits"))] = ModelBase::toJson(m_Balance_credits);
    }
    if(m_StatusIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("status"))] = ModelBase::toJson(m_Status);
    }
    if(m_Warning_threshold_creditsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("warning_threshold_credits"))] = ModelBase::toJson(m_Warning_threshold_credits);
    }
    if(m_Enforcement_enabledIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("enforcement_enabled"))] = ModelBase::toJson(m_Enforcement_enabled);
    }
    if(m_RatesIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("rates"))] = ModelBase::toJson(m_Rates);
    }
    if(m_Manual_blockIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("manual_block"))] = ModelBase::toJson(m_Manual_block);
    }
    if(m_Manual_block_reasonIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("manual_block_reason"))] = ModelBase::toJson(m_Manual_block_reason);
    }

    return val;
}

bool OrganizationCreditAccountSchema::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("organization_uuid"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("organization_uuid")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setOrganizationUuid;
            ok &= ModelBase::fromJson(fieldValue, refVal_setOrganizationUuid);
            setOrganizationUuid(refVal_setOrganizationUuid);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("balance_credits"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("balance_credits")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setBalanceCredits;
            ok &= ModelBase::fromJson(fieldValue, refVal_setBalanceCredits);
            setBalanceCredits(refVal_setBalanceCredits);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("status")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setStatus;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStatus);
            setStatus(refVal_setStatus);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("warning_threshold_credits"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("warning_threshold_credits")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setWarningThresholdCredits;
            ok &= ModelBase::fromJson(fieldValue, refVal_setWarningThresholdCredits);
            setWarningThresholdCredits(refVal_setWarningThresholdCredits);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("enforcement_enabled"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("enforcement_enabled")));
        if(!fieldValue.is_null())
        {
            bool refVal_setEnforcementEnabled;
            ok &= ModelBase::fromJson(fieldValue, refVal_setEnforcementEnabled);
            setEnforcementEnabled(refVal_setEnforcementEnabled);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("rates"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("rates")));
        if(!fieldValue.is_null())
        {
            std::map<utility::string_t, std::map<utility::string_t, std::shared_ptr<Rates_value_value>>> refVal_setRates;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRates);
            setRates(refVal_setRates);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("manual_block"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("manual_block")));
        if(!fieldValue.is_null())
        {
            bool refVal_setManualBlock;
            ok &= ModelBase::fromJson(fieldValue, refVal_setManualBlock);
            setManualBlock(refVal_setManualBlock);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("manual_block_reason"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("manual_block_reason")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setManualBlockReason;
            ok &= ModelBase::fromJson(fieldValue, refVal_setManualBlockReason);
            setManualBlockReason(refVal_setManualBlockReason);
            
        }
    }
    return ok;
}

void OrganizationCreditAccountSchema::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_Organization_uuidIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("organization_uuid")), m_Organization_uuid));
    }
    if(m_Balance_creditsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("balance_credits")), m_Balance_credits));
    }
    if(m_StatusIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("status")), m_Status));
    }
    if(m_Warning_threshold_creditsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("warning_threshold_credits")), m_Warning_threshold_credits));
    }
    if(m_Enforcement_enabledIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("enforcement_enabled")), m_Enforcement_enabled));
    }
    if(m_RatesIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("rates")), m_Rates));
    }
    if(m_Manual_blockIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("manual_block")), m_Manual_block));
    }
    if(m_Manual_block_reasonIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("manual_block_reason")), m_Manual_block_reason));
    }
}

bool OrganizationCreditAccountSchema::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("organization_uuid"))))
    {
        utility::string_t refVal_setOrganizationUuid;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("organization_uuid"))), refVal_setOrganizationUuid );
        setOrganizationUuid(refVal_setOrganizationUuid);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("balance_credits"))))
    {
        utility::string_t refVal_setBalanceCredits;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("balance_credits"))), refVal_setBalanceCredits );
        setBalanceCredits(refVal_setBalanceCredits);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        utility::string_t refVal_setStatus;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("status"))), refVal_setStatus );
        setStatus(refVal_setStatus);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("warning_threshold_credits"))))
    {
        utility::string_t refVal_setWarningThresholdCredits;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("warning_threshold_credits"))), refVal_setWarningThresholdCredits );
        setWarningThresholdCredits(refVal_setWarningThresholdCredits);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("enforcement_enabled"))))
    {
        bool refVal_setEnforcementEnabled;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("enforcement_enabled"))), refVal_setEnforcementEnabled );
        setEnforcementEnabled(refVal_setEnforcementEnabled);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("rates"))))
    {
        std::map<utility::string_t, std::map<utility::string_t, std::shared_ptr<Rates_value_value>>> refVal_setRates;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("rates"))), refVal_setRates );
        setRates(refVal_setRates);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("manual_block"))))
    {
        bool refVal_setManualBlock;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("manual_block"))), refVal_setManualBlock );
        setManualBlock(refVal_setManualBlock);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("manual_block_reason"))))
    {
        utility::string_t refVal_setManualBlockReason;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("manual_block_reason"))), refVal_setManualBlockReason );
        setManualBlockReason(refVal_setManualBlockReason);
    }
    return ok;
}


utility::string_t OrganizationCreditAccountSchema::getOrganizationUuid() const
{
    return m_Organization_uuid;
}


void OrganizationCreditAccountSchema::setOrganizationUuid(const utility::string_t& value)
{
    m_Organization_uuid = value;
    m_Organization_uuidIsSet = true;
}

bool OrganizationCreditAccountSchema::organizationUuidIsSet() const
{
    return m_Organization_uuidIsSet;
}

void OrganizationCreditAccountSchema::unsetOrganization_uuid()
{
    m_Organization_uuidIsSet = false;
}
utility::string_t OrganizationCreditAccountSchema::getBalanceCredits() const
{
    return m_Balance_credits;
}


void OrganizationCreditAccountSchema::setBalanceCredits(const utility::string_t& value)
{
    m_Balance_credits = value;
    m_Balance_creditsIsSet = true;
}

bool OrganizationCreditAccountSchema::balanceCreditsIsSet() const
{
    return m_Balance_creditsIsSet;
}

void OrganizationCreditAccountSchema::unsetBalance_credits()
{
    m_Balance_creditsIsSet = false;
}
utility::string_t OrganizationCreditAccountSchema::getStatus() const
{
    return m_Status;
}


void OrganizationCreditAccountSchema::setStatus(const utility::string_t& value)
{
    m_Status = value;
    m_StatusIsSet = true;
}

bool OrganizationCreditAccountSchema::statusIsSet() const
{
    return m_StatusIsSet;
}

void OrganizationCreditAccountSchema::unsetStatus()
{
    m_StatusIsSet = false;
}
utility::string_t OrganizationCreditAccountSchema::getWarningThresholdCredits() const
{
    return m_Warning_threshold_credits;
}


void OrganizationCreditAccountSchema::setWarningThresholdCredits(const utility::string_t& value)
{
    m_Warning_threshold_credits = value;
    m_Warning_threshold_creditsIsSet = true;
}

bool OrganizationCreditAccountSchema::warningThresholdCreditsIsSet() const
{
    return m_Warning_threshold_creditsIsSet;
}

void OrganizationCreditAccountSchema::unsetWarning_threshold_credits()
{
    m_Warning_threshold_creditsIsSet = false;
}
bool OrganizationCreditAccountSchema::isEnforcementEnabled() const
{
    return m_Enforcement_enabled;
}

void OrganizationCreditAccountSchema::setEnforcementEnabled(bool value)
{
    m_Enforcement_enabled = value;
    m_Enforcement_enabledIsSet = true;
}

bool OrganizationCreditAccountSchema::enforcementEnabledIsSet() const
{
    return m_Enforcement_enabledIsSet;
}

void OrganizationCreditAccountSchema::unsetEnforcement_enabled()
{
    m_Enforcement_enabledIsSet = false;
}
std::map<utility::string_t, std::map<utility::string_t, std::shared_ptr<Rates_value_value>>> OrganizationCreditAccountSchema::getRates() const
{
    return m_Rates;
}


void OrganizationCreditAccountSchema::setRates(const std::map<utility::string_t, std::map<utility::string_t, std::shared_ptr<Rates_value_value>>>& value)
{
    m_Rates = value;
    m_RatesIsSet = true;
}

bool OrganizationCreditAccountSchema::ratesIsSet() const
{
    return m_RatesIsSet;
}

void OrganizationCreditAccountSchema::unsetRates()
{
    m_RatesIsSet = false;
}
bool OrganizationCreditAccountSchema::isManualBlock() const
{
    return m_Manual_block;
}

void OrganizationCreditAccountSchema::setManualBlock(bool value)
{
    m_Manual_block = value;
    m_Manual_blockIsSet = true;
}

bool OrganizationCreditAccountSchema::manualBlockIsSet() const
{
    return m_Manual_blockIsSet;
}

void OrganizationCreditAccountSchema::unsetManual_block()
{
    m_Manual_blockIsSet = false;
}
utility::string_t OrganizationCreditAccountSchema::getManualBlockReason() const
{
    return m_Manual_block_reason;
}


void OrganizationCreditAccountSchema::setManualBlockReason(const utility::string_t& value)
{
    m_Manual_block_reason = value;
    m_Manual_block_reasonIsSet = true;
}

bool OrganizationCreditAccountSchema::manualBlockReasonIsSet() const
{
    return m_Manual_block_reasonIsSet;
}

void OrganizationCreditAccountSchema::unsetManual_block_reason()
{
    m_Manual_block_reasonIsSet = false;
}

}
}
}
}


