/**
 * Cyberwave API
 * Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.23.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/OrgMemberSchema.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

OrgMemberSchema::OrgMemberSchema()
{
    m_UserIsSet = false;
    m_Role = utility::conversions::to_string_t("");
    m_RoleIsSet = false;
    m_Is_owner = false;
    m_Is_ownerIsSet = false;
}

OrgMemberSchema::~OrgMemberSchema()
{
}

void OrgMemberSchema::validate()
{
    // TODO: implement validation
}

web::json::value OrgMemberSchema::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_UserIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("user"))] = ModelBase::toJson(m_User);
    }
    if(m_RoleIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("role"))] = ModelBase::toJson(m_Role);
    }
    if(m_Is_ownerIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("is_owner"))] = ModelBase::toJson(m_Is_owner);
    }

    return val;
}

bool OrgMemberSchema::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("user"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("user")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<OrgMemberUserSchema> refVal_setUser;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUser);
            setUser(refVal_setUser);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("role"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("role")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setRole;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRole);
            setRole(refVal_setRole);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("is_owner"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("is_owner")));
        if(!fieldValue.is_null())
        {
            bool refVal_setIsOwner;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIsOwner);
            setIsOwner(refVal_setIsOwner);
            
        }
    }
    return ok;
}

void OrgMemberSchema::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_UserIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("user")), m_User));
    }
    if(m_RoleIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("role")), m_Role));
    }
    if(m_Is_ownerIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("is_owner")), m_Is_owner));
    }
}

bool OrgMemberSchema::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("user"))))
    {
        std::shared_ptr<OrgMemberUserSchema> refVal_setUser;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("user"))), refVal_setUser );
        setUser(refVal_setUser);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("role"))))
    {
        utility::string_t refVal_setRole;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("role"))), refVal_setRole );
        setRole(refVal_setRole);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("is_owner"))))
    {
        bool refVal_setIsOwner;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("is_owner"))), refVal_setIsOwner );
        setIsOwner(refVal_setIsOwner);
    }
    return ok;
}


std::shared_ptr<OrgMemberUserSchema> OrgMemberSchema::getUser() const
{
    return m_User;
}


void OrgMemberSchema::setUser(const std::shared_ptr<OrgMemberUserSchema>& value)
{
    m_User = value;
    m_UserIsSet = true;
}

bool OrgMemberSchema::userIsSet() const
{
    return m_UserIsSet;
}

void OrgMemberSchema::unsetUser()
{
    m_UserIsSet = false;
}
utility::string_t OrgMemberSchema::getRole() const
{
    return m_Role;
}


void OrgMemberSchema::setRole(const utility::string_t& value)
{
    m_Role = value;
    m_RoleIsSet = true;
}

bool OrgMemberSchema::roleIsSet() const
{
    return m_RoleIsSet;
}

void OrgMemberSchema::unsetRole()
{
    m_RoleIsSet = false;
}
bool OrgMemberSchema::isIsOwner() const
{
    return m_Is_owner;
}

void OrgMemberSchema::setIsOwner(bool value)
{
    m_Is_owner = value;
    m_Is_ownerIsSet = true;
}

bool OrgMemberSchema::isOwnerIsSet() const
{
    return m_Is_ownerIsSet;
}

void OrgMemberSchema::unsetIs_owner()
{
    m_Is_ownerIsSet = false;
}

}
}
}
}


