/**
 * Cyberwave API
 * Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.26.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/PinnedWorkspaceMapViewSchema.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

PinnedWorkspaceMapViewSchema::PinnedWorkspaceMapViewSchema()
{
    m_KindIsSet = false;
    m_MapUuid = utility::conversions::to_string_t("");
    m_MapUuidIsSet = false;
}

PinnedWorkspaceMapViewSchema::~PinnedWorkspaceMapViewSchema()
{
}

void PinnedWorkspaceMapViewSchema::validate()
{
    // TODO: implement validation
}

web::json::value PinnedWorkspaceMapViewSchema::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_KindIsSet)
    {
        
        utility::string_t refVal = fromKindEnum(m_Kind);
        val[utility::conversions::to_string_t(_XPLATSTR("kind"))] = ModelBase::toJson(refVal);
        
    }
    if(m_MapUuidIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("mapUuid"))] = ModelBase::toJson(m_MapUuid);
    }

    return val;
}

bool PinnedWorkspaceMapViewSchema::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("kind"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("kind")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setKind;
            ok &= ModelBase::fromJson(fieldValue, refVal_setKind);
            
            setKind(toKindEnum(refVal_setKind));
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("mapUuid"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("mapUuid")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setMapUuid;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMapUuid);
            setMapUuid(refVal_setMapUuid);
            
        }
    }
    return ok;
}

void PinnedWorkspaceMapViewSchema::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_KindIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("kind")), fromKindEnum(m_Kind)));
    }
    if(m_MapUuidIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("mapUuid")), m_MapUuid));
    }
}

bool PinnedWorkspaceMapViewSchema::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("kind"))))
    {
        utility::string_t refVal_setKind;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("kind"))), refVal_setKind );
        setKind(toKindEnum(refVal_setKind));
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("mapUuid"))))
    {
        utility::string_t refVal_setMapUuid;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("mapUuid"))), refVal_setMapUuid );
        setMapUuid(refVal_setMapUuid);
    }
    return ok;
}

PinnedWorkspaceMapViewSchema::KindEnum PinnedWorkspaceMapViewSchema::toKindEnum(const utility::string_t& value) const
{
    
    if (value == utility::conversions::to_string_t("map")) {
        return KindEnum::MAP;
    }
    
    throw std::invalid_argument("Invalid value for conversion to KindEnum");
}


const utility::string_t PinnedWorkspaceMapViewSchema::fromKindEnum(const KindEnum value) const
{
    switch(value)
    {
        
        case KindEnum::MAP: return utility::conversions::to_string_t("map");
        
    }
}


PinnedWorkspaceMapViewSchema::KindEnum PinnedWorkspaceMapViewSchema::getKind() const
{
    return m_Kind;
}


void PinnedWorkspaceMapViewSchema::setKind(const KindEnum value)
{
    m_Kind = value;
    m_KindIsSet = true;
}

bool PinnedWorkspaceMapViewSchema::kindIsSet() const
{
    return m_KindIsSet;
}

void PinnedWorkspaceMapViewSchema::unsetKind()
{
    m_KindIsSet = false;
}
utility::string_t PinnedWorkspaceMapViewSchema::getMapUuid() const
{
    return m_MapUuid;
}


void PinnedWorkspaceMapViewSchema::setMapUuid(const utility::string_t& value)
{
    m_MapUuid = value;
    m_MapUuidIsSet = true;
}

bool PinnedWorkspaceMapViewSchema::mapUuidIsSet() const
{
    return m_MapUuidIsSet;
}

void PinnedWorkspaceMapViewSchema::unsetMapUuid()
{
    m_MapUuidIsSet = false;
}

}
}
}
}


