/**
 * Cyberwave API
 * Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.26.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/RecordingAvailabilityResponse.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

RecordingAvailabilityResponse::RecordingAvailabilityResponse()
{
    m_DaysIsSet = false;
    m_Total_count = 0;
    m_Total_countIsSet = false;
    m_FacetsIsSet = false;
    m_Timezone = utility::conversions::to_string_t("");
    m_TimezoneIsSet = false;
}

RecordingAvailabilityResponse::~RecordingAvailabilityResponse()
{
}

void RecordingAvailabilityResponse::validate()
{
    // TODO: implement validation
}

web::json::value RecordingAvailabilityResponse::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_First_date.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("first_date"))] = ModelBase::toJson(m_First_date.get());
    }
    if(m_Last_date.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("last_date"))] = ModelBase::toJson(m_Last_date.get());
    }
    if(m_DaysIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("days"))] = ModelBase::toJson(m_Days);
    }
    if(m_Total_countIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("total_count"))] = ModelBase::toJson(m_Total_count);
    }
    if(m_FacetsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("facets"))] = ModelBase::toJson(m_Facets);
    }
    if(m_TimezoneIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("timezone"))] = ModelBase::toJson(m_Timezone);
    }

    return val;
}

bool RecordingAvailabilityResponse::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("first_date"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("first_date")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setFirstDate;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFirstDate);
            setFirstDate(refVal_setFirstDate);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("last_date"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("last_date")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setLastDate;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLastDate);
            setLastDate(refVal_setLastDate);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("days"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("days")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<RecordingAvailabilityDay>> refVal_setDays;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDays);
            setDays(refVal_setDays);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("total_count"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("total_count")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setTotalCount;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTotalCount);
            setTotalCount(refVal_setTotalCount);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("facets"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("facets")));
        if(!fieldValue.is_null())
        {
            std::map<utility::string_t, std::map<utility::string_t, int32_t>> refVal_setFacets;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFacets);
            setFacets(refVal_setFacets);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("timezone"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("timezone")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setTimezone;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTimezone);
            setTimezone(refVal_setTimezone);
            
        }
    }
    return ok;
}

void RecordingAvailabilityResponse::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_First_date.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("first_date")), m_First_date.get()));
    }
    if(m_Last_date.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("last_date")), m_Last_date.get()));
    }
    if(m_DaysIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("days")), m_Days));
    }
    if(m_Total_countIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("total_count")), m_Total_count));
    }
    if(m_FacetsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("facets")), m_Facets));
    }
    if(m_TimezoneIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("timezone")), m_Timezone));
    }
}

bool RecordingAvailabilityResponse::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("first_date"))))
    {
        utility::string_t refVal_setFirstDate;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("first_date"))), refVal_setFirstDate );
        setFirstDate(refVal_setFirstDate);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("last_date"))))
    {
        utility::string_t refVal_setLastDate;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("last_date"))), refVal_setLastDate );
        setLastDate(refVal_setLastDate);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("days"))))
    {
        std::vector<std::shared_ptr<RecordingAvailabilityDay>> refVal_setDays;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("days"))), refVal_setDays );
        setDays(refVal_setDays);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("total_count"))))
    {
        int32_t refVal_setTotalCount;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("total_count"))), refVal_setTotalCount );
        setTotalCount(refVal_setTotalCount);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("facets"))))
    {
        std::map<utility::string_t, std::map<utility::string_t, int32_t>> refVal_setFacets;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("facets"))), refVal_setFacets );
        setFacets(refVal_setFacets);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("timezone"))))
    {
        utility::string_t refVal_setTimezone;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("timezone"))), refVal_setTimezone );
        setTimezone(refVal_setTimezone);
    }
    return ok;
}


utility::string_t RecordingAvailabilityResponse::getFirstDate() const
{
    return m_First_date.get();
}


void RecordingAvailabilityResponse::setFirstDate(const utility::string_t& value)
{
    m_First_date = value;
}

bool RecordingAvailabilityResponse::firstDateIsSet() const
{
    return m_First_date.has_value();
}

void RecordingAvailabilityResponse::unsetFirst_date()
{
    m_First_date.reset();
}
utility::string_t RecordingAvailabilityResponse::getLastDate() const
{
    return m_Last_date.get();
}


void RecordingAvailabilityResponse::setLastDate(const utility::string_t& value)
{
    m_Last_date = value;
}

bool RecordingAvailabilityResponse::lastDateIsSet() const
{
    return m_Last_date.has_value();
}

void RecordingAvailabilityResponse::unsetLast_date()
{
    m_Last_date.reset();
}
std::vector<std::shared_ptr<RecordingAvailabilityDay>> RecordingAvailabilityResponse::getDays() const
{
    return m_Days;
}


void RecordingAvailabilityResponse::setDays(const std::vector<std::shared_ptr<RecordingAvailabilityDay>>& value)
{
    m_Days = value;
    m_DaysIsSet = true;
}

bool RecordingAvailabilityResponse::daysIsSet() const
{
    return m_DaysIsSet;
}

void RecordingAvailabilityResponse::unsetDays()
{
    m_DaysIsSet = false;
}
int32_t RecordingAvailabilityResponse::getTotalCount() const
{
    return m_Total_count;
}

void RecordingAvailabilityResponse::setTotalCount(int32_t value)
{
    m_Total_count = value;
    m_Total_countIsSet = true;
}

bool RecordingAvailabilityResponse::totalCountIsSet() const
{
    return m_Total_countIsSet;
}

void RecordingAvailabilityResponse::unsetTotal_count()
{
    m_Total_countIsSet = false;
}
std::map<utility::string_t, std::map<utility::string_t, int32_t>> RecordingAvailabilityResponse::getFacets() const
{
    return m_Facets;
}


void RecordingAvailabilityResponse::setFacets(const std::map<utility::string_t, std::map<utility::string_t, int32_t>>& value)
{
    m_Facets = value;
    m_FacetsIsSet = true;
}

bool RecordingAvailabilityResponse::facetsIsSet() const
{
    return m_FacetsIsSet;
}

void RecordingAvailabilityResponse::unsetFacets()
{
    m_FacetsIsSet = false;
}
utility::string_t RecordingAvailabilityResponse::getTimezone() const
{
    return m_Timezone;
}


void RecordingAvailabilityResponse::setTimezone(const utility::string_t& value)
{
    m_Timezone = value;
    m_TimezoneIsSet = true;
}

bool RecordingAvailabilityResponse::timezoneIsSet() const
{
    return m_TimezoneIsSet;
}

void RecordingAvailabilityResponse::unsetTimezone()
{
    m_TimezoneIsSet = false;
}

}
}
}
}


