/**
 * Cyberwave API
 * Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.26.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/RequirementInput.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

RequirementInput::RequirementInput()
{
    m_Name = utility::conversions::to_string_t("");
    m_NameIsSet = false;
    m_Description = utility::conversions::to_string_t("");
    m_DescriptionIsSet = false;
    m_Acceptance_criteria = utility::conversions::to_string_t("");
    m_Acceptance_criteriaIsSet = false;
    m_PriorityIsSet = false;
    m_StatusIsSet = false;
    m_Linear_url = utility::conversions::to_string_t("");
    m_Linear_urlIsSet = false;
}

RequirementInput::~RequirementInput()
{
}

void RequirementInput::validate()
{
    // TODO: implement validation
}

web::json::value RequirementInput::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_NameIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("name"))] = ModelBase::toJson(m_Name);
    }
    if(m_DescriptionIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("description"))] = ModelBase::toJson(m_Description);
    }
    if(m_Acceptance_criteriaIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("acceptance_criteria"))] = ModelBase::toJson(m_Acceptance_criteria);
    }
    if(m_PriorityIsSet)
    {
        
        utility::string_t refVal = fromPriorityEnum(m_Priority);
        val[utility::conversions::to_string_t(_XPLATSTR("priority"))] = ModelBase::toJson(refVal);
        
    }
    if(m_StatusIsSet)
    {
        
        utility::string_t refVal = fromStatusEnum(m_Status);
        val[utility::conversions::to_string_t(_XPLATSTR("status"))] = ModelBase::toJson(refVal);
        
    }
    if(m_Deliverable_uuid.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("deliverable_uuid"))] = ModelBase::toJson(m_Deliverable_uuid.get());
    }
    if(m_Linear_urlIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("linear_url"))] = ModelBase::toJson(m_Linear_url);
    }

    return val;
}

bool RequirementInput::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setName);
            setName(refVal_setName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("description"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("description")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setDescription;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDescription);
            setDescription(refVal_setDescription);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("acceptance_criteria"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("acceptance_criteria")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setAcceptanceCriteria;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAcceptanceCriteria);
            setAcceptanceCriteria(refVal_setAcceptanceCriteria);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("priority"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("priority")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setPriority;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPriority);
            
            setPriority(toPriorityEnum(refVal_setPriority));
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("status")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setStatus;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStatus);
            
            setStatus(toStatusEnum(refVal_setStatus));
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("deliverable_uuid"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("deliverable_uuid")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setDeliverableUuid;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDeliverableUuid);
            setDeliverableUuid(refVal_setDeliverableUuid);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("linear_url"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("linear_url")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setLinearUrl;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLinearUrl);
            setLinearUrl(refVal_setLinearUrl);
            
        }
    }
    return ok;
}

void RequirementInput::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_NameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("name")), m_Name));
    }
    if(m_DescriptionIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("description")), m_Description));
    }
    if(m_Acceptance_criteriaIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("acceptance_criteria")), m_Acceptance_criteria));
    }
    if(m_PriorityIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("priority")), fromPriorityEnum(m_Priority)));
    }
    if(m_StatusIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("status")), fromStatusEnum(m_Status)));
    }
    if(m_Deliverable_uuid.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("deliverable_uuid")), m_Deliverable_uuid.get()));
    }
    if(m_Linear_urlIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("linear_url")), m_Linear_url));
    }
}

bool RequirementInput::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        utility::string_t refVal_setName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("name"))), refVal_setName );
        setName(refVal_setName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("description"))))
    {
        utility::string_t refVal_setDescription;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("description"))), refVal_setDescription );
        setDescription(refVal_setDescription);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("acceptance_criteria"))))
    {
        utility::string_t refVal_setAcceptanceCriteria;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("acceptance_criteria"))), refVal_setAcceptanceCriteria );
        setAcceptanceCriteria(refVal_setAcceptanceCriteria);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("priority"))))
    {
        utility::string_t refVal_setPriority;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("priority"))), refVal_setPriority );
        setPriority(toPriorityEnum(refVal_setPriority));
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        utility::string_t refVal_setStatus;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("status"))), refVal_setStatus );
        setStatus(toStatusEnum(refVal_setStatus));
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("deliverable_uuid"))))
    {
        utility::string_t refVal_setDeliverableUuid;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("deliverable_uuid"))), refVal_setDeliverableUuid );
        setDeliverableUuid(refVal_setDeliverableUuid);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("linear_url"))))
    {
        utility::string_t refVal_setLinearUrl;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("linear_url"))), refVal_setLinearUrl );
        setLinearUrl(refVal_setLinearUrl);
    }
    return ok;
}

RequirementInput::PriorityEnum RequirementInput::toPriorityEnum(const utility::string_t& value) const
{
    
    if (value == utility::conversions::to_string_t("must")) {
        return PriorityEnum::MUST;
    }
    
    if (value == utility::conversions::to_string_t("should")) {
        return PriorityEnum::SHOULD;
    }
    
    if (value == utility::conversions::to_string_t("could")) {
        return PriorityEnum::COULD;
    }
    
    if (value == utility::conversions::to_string_t("wont")) {
        return PriorityEnum::WONT;
    }
    
    throw std::invalid_argument("Invalid value for conversion to PriorityEnum");
}


const utility::string_t RequirementInput::fromPriorityEnum(const PriorityEnum value) const
{
    switch(value)
    {
        
        case PriorityEnum::MUST: return utility::conversions::to_string_t("must");
        
        case PriorityEnum::SHOULD: return utility::conversions::to_string_t("should");
        
        case PriorityEnum::COULD: return utility::conversions::to_string_t("could");
        
        case PriorityEnum::WONT: return utility::conversions::to_string_t("wont");
        
    }
}

RequirementInput::StatusEnum RequirementInput::toStatusEnum(const utility::string_t& value) const
{
    
    if (value == utility::conversions::to_string_t("draft")) {
        return StatusEnum::DRAFT;
    }
    
    if (value == utility::conversions::to_string_t("agreed")) {
        return StatusEnum::AGREED;
    }
    
    if (value == utility::conversions::to_string_t("in_progress")) {
        return StatusEnum::IN_PROGRESS;
    }
    
    if (value == utility::conversions::to_string_t("accepted")) {
        return StatusEnum::ACCEPTED;
    }
    
    if (value == utility::conversions::to_string_t("dropped")) {
        return StatusEnum::DROPPED;
    }
    
    throw std::invalid_argument("Invalid value for conversion to StatusEnum");
}


const utility::string_t RequirementInput::fromStatusEnum(const StatusEnum value) const
{
    switch(value)
    {
        
        case StatusEnum::DRAFT: return utility::conversions::to_string_t("draft");
        
        case StatusEnum::AGREED: return utility::conversions::to_string_t("agreed");
        
        case StatusEnum::IN_PROGRESS: return utility::conversions::to_string_t("in_progress");
        
        case StatusEnum::ACCEPTED: return utility::conversions::to_string_t("accepted");
        
        case StatusEnum::DROPPED: return utility::conversions::to_string_t("dropped");
        
    }
}


utility::string_t RequirementInput::getName() const
{
    return m_Name;
}


void RequirementInput::setName(const utility::string_t& value)
{
    m_Name = value;
    m_NameIsSet = true;
}

bool RequirementInput::nameIsSet() const
{
    return m_NameIsSet;
}

void RequirementInput::unsetName()
{
    m_NameIsSet = false;
}
utility::string_t RequirementInput::getDescription() const
{
    return m_Description;
}


void RequirementInput::setDescription(const utility::string_t& value)
{
    m_Description = value;
    m_DescriptionIsSet = true;
}

bool RequirementInput::descriptionIsSet() const
{
    return m_DescriptionIsSet;
}

void RequirementInput::unsetDescription()
{
    m_DescriptionIsSet = false;
}
utility::string_t RequirementInput::getAcceptanceCriteria() const
{
    return m_Acceptance_criteria;
}


void RequirementInput::setAcceptanceCriteria(const utility::string_t& value)
{
    m_Acceptance_criteria = value;
    m_Acceptance_criteriaIsSet = true;
}

bool RequirementInput::acceptanceCriteriaIsSet() const
{
    return m_Acceptance_criteriaIsSet;
}

void RequirementInput::unsetAcceptance_criteria()
{
    m_Acceptance_criteriaIsSet = false;
}
RequirementInput::PriorityEnum RequirementInput::getPriority() const
{
    return m_Priority;
}


void RequirementInput::setPriority(const PriorityEnum value)
{
    m_Priority = value;
    m_PriorityIsSet = true;
}

bool RequirementInput::priorityIsSet() const
{
    return m_PriorityIsSet;
}

void RequirementInput::unsetPriority()
{
    m_PriorityIsSet = false;
}
RequirementInput::StatusEnum RequirementInput::getStatus() const
{
    return m_Status;
}


void RequirementInput::setStatus(const StatusEnum value)
{
    m_Status = value;
    m_StatusIsSet = true;
}

bool RequirementInput::statusIsSet() const
{
    return m_StatusIsSet;
}

void RequirementInput::unsetStatus()
{
    m_StatusIsSet = false;
}
utility::string_t RequirementInput::getDeliverableUuid() const
{
    return m_Deliverable_uuid.get();
}


void RequirementInput::setDeliverableUuid(const utility::string_t& value)
{
    m_Deliverable_uuid = value;
}

bool RequirementInput::deliverableUuidIsSet() const
{
    return m_Deliverable_uuid.has_value();
}

void RequirementInput::unsetDeliverable_uuid()
{
    m_Deliverable_uuid.reset();
}
utility::string_t RequirementInput::getLinearUrl() const
{
    return m_Linear_url;
}


void RequirementInput::setLinearUrl(const utility::string_t& value)
{
    m_Linear_url = value;
    m_Linear_urlIsSet = true;
}

bool RequirementInput::linearUrlIsSet() const
{
    return m_Linear_urlIsSet;
}

void RequirementInput::unsetLinear_url()
{
    m_Linear_urlIsSet = false;
}

}
}
}
}


