/**
 * Cyberwave API
 * Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/RevokeUserFeatureRequest.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

RevokeUserFeatureRequest::RevokeUserFeatureRequest()
{
    m_User_uuid = utility::conversions::to_string_t("");
    m_User_uuidIsSet = false;
    m_Feature = utility::conversions::to_string_t("");
    m_FeatureIsSet = false;
}

RevokeUserFeatureRequest::~RevokeUserFeatureRequest()
{
}

void RevokeUserFeatureRequest::validate()
{
    // TODO: implement validation
}

web::json::value RevokeUserFeatureRequest::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_User_uuidIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("user_uuid"))] = ModelBase::toJson(m_User_uuid);
    }
    if(m_FeatureIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("feature"))] = ModelBase::toJson(m_Feature);
    }

    return val;
}

bool RevokeUserFeatureRequest::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("user_uuid"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("user_uuid")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setUserUuid;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUserUuid);
            setUserUuid(refVal_setUserUuid);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("feature"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("feature")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setFeature;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFeature);
            setFeature(refVal_setFeature);
            
        }
    }
    return ok;
}

void RevokeUserFeatureRequest::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_User_uuidIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("user_uuid")), m_User_uuid));
    }
    if(m_FeatureIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("feature")), m_Feature));
    }
}

bool RevokeUserFeatureRequest::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("user_uuid"))))
    {
        utility::string_t refVal_setUserUuid;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("user_uuid"))), refVal_setUserUuid );
        setUserUuid(refVal_setUserUuid);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("feature"))))
    {
        utility::string_t refVal_setFeature;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("feature"))), refVal_setFeature );
        setFeature(refVal_setFeature);
    }
    return ok;
}


utility::string_t RevokeUserFeatureRequest::getUserUuid() const
{
    return m_User_uuid;
}


void RevokeUserFeatureRequest::setUserUuid(const utility::string_t& value)
{
    m_User_uuid = value;
    m_User_uuidIsSet = true;
}

bool RevokeUserFeatureRequest::userUuidIsSet() const
{
    return m_User_uuidIsSet;
}

void RevokeUserFeatureRequest::unsetUser_uuid()
{
    m_User_uuidIsSet = false;
}
utility::string_t RevokeUserFeatureRequest::getFeature() const
{
    return m_Feature;
}


void RevokeUserFeatureRequest::setFeature(const utility::string_t& value)
{
    m_Feature = value;
    m_FeatureIsSet = true;
}

bool RevokeUserFeatureRequest::featureIsSet() const
{
    return m_FeatureIsSet;
}

void RevokeUserFeatureRequest::unsetFeature()
{
    m_FeatureIsSet = false;
}

}
}
}
}


