/**
 * Cyberwave API
 * Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/RLTaskSceneEntityDockedTwinSchema.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

RLTaskSceneEntityDockedTwinSchema::RLTaskSceneEntityDockedTwinSchema()
{
    m_Uuid = utility::conversions::to_string_t("");
    m_UuidIsSet = false;
    m_Name = utility::conversions::to_string_t("");
    m_NameIsSet = false;
    m_Hex_prefix = utility::conversions::to_string_t("");
    m_Hex_prefixIsSet = false;
}

RLTaskSceneEntityDockedTwinSchema::~RLTaskSceneEntityDockedTwinSchema()
{
}

void RLTaskSceneEntityDockedTwinSchema::validate()
{
    // TODO: implement validation
}

web::json::value RLTaskSceneEntityDockedTwinSchema::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_UuidIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("uuid"))] = ModelBase::toJson(m_Uuid);
    }
    if(m_NameIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("name"))] = ModelBase::toJson(m_Name);
    }
    if(m_Hex_prefixIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("hex_prefix"))] = ModelBase::toJson(m_Hex_prefix);
    }

    return val;
}

bool RLTaskSceneEntityDockedTwinSchema::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("uuid"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("uuid")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setUuid;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUuid);
            setUuid(refVal_setUuid);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setName);
            setName(refVal_setName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("hex_prefix"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("hex_prefix")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setHexPrefix;
            ok &= ModelBase::fromJson(fieldValue, refVal_setHexPrefix);
            setHexPrefix(refVal_setHexPrefix);
            
        }
    }
    return ok;
}

void RLTaskSceneEntityDockedTwinSchema::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_UuidIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("uuid")), m_Uuid));
    }
    if(m_NameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("name")), m_Name));
    }
    if(m_Hex_prefixIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("hex_prefix")), m_Hex_prefix));
    }
}

bool RLTaskSceneEntityDockedTwinSchema::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("uuid"))))
    {
        utility::string_t refVal_setUuid;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("uuid"))), refVal_setUuid );
        setUuid(refVal_setUuid);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        utility::string_t refVal_setName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("name"))), refVal_setName );
        setName(refVal_setName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("hex_prefix"))))
    {
        utility::string_t refVal_setHexPrefix;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("hex_prefix"))), refVal_setHexPrefix );
        setHexPrefix(refVal_setHexPrefix);
    }
    return ok;
}


utility::string_t RLTaskSceneEntityDockedTwinSchema::getUuid() const
{
    return m_Uuid;
}


void RLTaskSceneEntityDockedTwinSchema::setUuid(const utility::string_t& value)
{
    m_Uuid = value;
    m_UuidIsSet = true;
}

bool RLTaskSceneEntityDockedTwinSchema::uuidIsSet() const
{
    return m_UuidIsSet;
}

void RLTaskSceneEntityDockedTwinSchema::unsetUuid()
{
    m_UuidIsSet = false;
}
utility::string_t RLTaskSceneEntityDockedTwinSchema::getName() const
{
    return m_Name;
}


void RLTaskSceneEntityDockedTwinSchema::setName(const utility::string_t& value)
{
    m_Name = value;
    m_NameIsSet = true;
}

bool RLTaskSceneEntityDockedTwinSchema::nameIsSet() const
{
    return m_NameIsSet;
}

void RLTaskSceneEntityDockedTwinSchema::unsetName()
{
    m_NameIsSet = false;
}
utility::string_t RLTaskSceneEntityDockedTwinSchema::getHexPrefix() const
{
    return m_Hex_prefix;
}


void RLTaskSceneEntityDockedTwinSchema::setHexPrefix(const utility::string_t& value)
{
    m_Hex_prefix = value;
    m_Hex_prefixIsSet = true;
}

bool RLTaskSceneEntityDockedTwinSchema::hexPrefixIsSet() const
{
    return m_Hex_prefixIsSet;
}

void RLTaskSceneEntityDockedTwinSchema::unsetHex_prefix()
{
    m_Hex_prefixIsSet = false;
}

}
}
}
}


