/**
 * Cyberwave API
 * Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.24.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/RLTaskGenerateEnvCfgSchema.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

RLTaskGenerateEnvCfgSchema::RLTaskGenerateEnvCfgSchema()
{
    m_Overwrite = false;
    m_OverwriteIsSet = false;
}

RLTaskGenerateEnvCfgSchema::~RLTaskGenerateEnvCfgSchema()
{
}

void RLTaskGenerateEnvCfgSchema::validate()
{
    // TODO: implement validation
}

web::json::value RLTaskGenerateEnvCfgSchema::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_OverwriteIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("overwrite"))] = ModelBase::toJson(m_Overwrite);
    }

    return val;
}

bool RLTaskGenerateEnvCfgSchema::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("overwrite"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("overwrite")));
        if(!fieldValue.is_null())
        {
            bool refVal_setOverwrite;
            ok &= ModelBase::fromJson(fieldValue, refVal_setOverwrite);
            setOverwrite(refVal_setOverwrite);
            
        }
    }
    return ok;
}

void RLTaskGenerateEnvCfgSchema::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_OverwriteIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("overwrite")), m_Overwrite));
    }
}

bool RLTaskGenerateEnvCfgSchema::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("overwrite"))))
    {
        bool refVal_setOverwrite;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("overwrite"))), refVal_setOverwrite );
        setOverwrite(refVal_setOverwrite);
    }
    return ok;
}


bool RLTaskGenerateEnvCfgSchema::isOverwrite() const
{
    return m_Overwrite;
}

void RLTaskGenerateEnvCfgSchema::setOverwrite(bool value)
{
    m_Overwrite = value;
    m_OverwriteIsSet = true;
}

bool RLTaskGenerateEnvCfgSchema::overwriteIsSet() const
{
    return m_OverwriteIsSet;
}

void RLTaskGenerateEnvCfgSchema::unsetOverwrite()
{
    m_OverwriteIsSet = false;
}

}
}
}
}


