/**
 * Cyberwave API
 * Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.24.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/RLTaskSceneEntityCameraMemberSchema.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

RLTaskSceneEntityCameraMemberSchema::RLTaskSceneEntityCameraMemberSchema()
{
    m_Schema_sensor_name = utility::conversions::to_string_t("");
    m_Schema_sensor_nameIsSet = false;
    m_Schema_typeIsSet = false;
    m_Parent_link = utility::conversions::to_string_t("");
    m_Parent_linkIsSet = false;
}

RLTaskSceneEntityCameraMemberSchema::~RLTaskSceneEntityCameraMemberSchema()
{
}

void RLTaskSceneEntityCameraMemberSchema::validate()
{
    // TODO: implement validation
}

web::json::value RLTaskSceneEntityCameraMemberSchema::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_Schema_sensor_nameIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("schema_sensor_name"))] = ModelBase::toJson(m_Schema_sensor_name);
    }
    if(m_Schema_typeIsSet)
    {
        
        utility::string_t refVal = fromSchema_typeEnum(m_Schema_type);
        val[utility::conversions::to_string_t(_XPLATSTR("schema_type"))] = ModelBase::toJson(refVal);
        
    }
    if(m_Parent_linkIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("parent_link"))] = ModelBase::toJson(m_Parent_link);
    }
    if(m_Width.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("width"))] = ModelBase::toJson(m_Width.get());
    }
    if(m_Height.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("height"))] = ModelBase::toJson(m_Height.get());
    }
    if(m_Fovy.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("fovy"))] = ModelBase::toJson(m_Fovy.get());
    }
    if(m_Min_depth.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("min_depth"))] = ModelBase::toJson(m_Min_depth.get());
    }
    if(m_Max_depth.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("max_depth"))] = ModelBase::toJson(m_Max_depth.get());
    }
    if(m_Update_rate.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("update_rate"))] = ModelBase::toJson(m_Update_rate.get());
    }

    return val;
}

bool RLTaskSceneEntityCameraMemberSchema::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("schema_sensor_name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("schema_sensor_name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setSchemaSensorName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSchemaSensorName);
            setSchemaSensorName(refVal_setSchemaSensorName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("schema_type"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("schema_type")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setSchemaType;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSchemaType);
            
            setSchemaType(toSchema_typeEnum(refVal_setSchemaType));
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("parent_link"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("parent_link")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setParentLink;
            ok &= ModelBase::fromJson(fieldValue, refVal_setParentLink);
            setParentLink(refVal_setParentLink);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("width"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("width")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setWidth;
            ok &= ModelBase::fromJson(fieldValue, refVal_setWidth);
            setWidth(refVal_setWidth);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("height"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("height")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setHeight;
            ok &= ModelBase::fromJson(fieldValue, refVal_setHeight);
            setHeight(refVal_setHeight);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("fovy"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("fovy")));
        if(!fieldValue.is_null())
        {
            double refVal_setFovy;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFovy);
            setFovy(refVal_setFovy);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("min_depth"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("min_depth")));
        if(!fieldValue.is_null())
        {
            double refVal_setMinDepth;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMinDepth);
            setMinDepth(refVal_setMinDepth);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("max_depth"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("max_depth")));
        if(!fieldValue.is_null())
        {
            double refVal_setMaxDepth;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMaxDepth);
            setMaxDepth(refVal_setMaxDepth);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("update_rate"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("update_rate")));
        if(!fieldValue.is_null())
        {
            double refVal_setUpdateRate;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUpdateRate);
            setUpdateRate(refVal_setUpdateRate);
            
        }
    }
    return ok;
}

void RLTaskSceneEntityCameraMemberSchema::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_Schema_sensor_nameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("schema_sensor_name")), m_Schema_sensor_name));
    }
    if(m_Schema_typeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("schema_type")), fromSchema_typeEnum(m_Schema_type)));
    }
    if(m_Parent_linkIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("parent_link")), m_Parent_link));
    }
    if(m_Width.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("width")), m_Width.get()));
    }
    if(m_Height.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("height")), m_Height.get()));
    }
    if(m_Fovy.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("fovy")), m_Fovy.get()));
    }
    if(m_Min_depth.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("min_depth")), m_Min_depth.get()));
    }
    if(m_Max_depth.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("max_depth")), m_Max_depth.get()));
    }
    if(m_Update_rate.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("update_rate")), m_Update_rate.get()));
    }
}

bool RLTaskSceneEntityCameraMemberSchema::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("schema_sensor_name"))))
    {
        utility::string_t refVal_setSchemaSensorName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("schema_sensor_name"))), refVal_setSchemaSensorName );
        setSchemaSensorName(refVal_setSchemaSensorName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("schema_type"))))
    {
        utility::string_t refVal_setSchemaType;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("schema_type"))), refVal_setSchemaType );
        setSchemaType(toSchema_typeEnum(refVal_setSchemaType));
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("parent_link"))))
    {
        utility::string_t refVal_setParentLink;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("parent_link"))), refVal_setParentLink );
        setParentLink(refVal_setParentLink);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("width"))))
    {
        int32_t refVal_setWidth;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("width"))), refVal_setWidth );
        setWidth(refVal_setWidth);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("height"))))
    {
        int32_t refVal_setHeight;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("height"))), refVal_setHeight );
        setHeight(refVal_setHeight);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("fovy"))))
    {
        double refVal_setFovy;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("fovy"))), refVal_setFovy );
        setFovy(refVal_setFovy);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("min_depth"))))
    {
        double refVal_setMinDepth;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("min_depth"))), refVal_setMinDepth );
        setMinDepth(refVal_setMinDepth);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("max_depth"))))
    {
        double refVal_setMaxDepth;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("max_depth"))), refVal_setMaxDepth );
        setMaxDepth(refVal_setMaxDepth);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("update_rate"))))
    {
        double refVal_setUpdateRate;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("update_rate"))), refVal_setUpdateRate );
        setUpdateRate(refVal_setUpdateRate);
    }
    return ok;
}

RLTaskSceneEntityCameraMemberSchema::Schema_typeEnum RLTaskSceneEntityCameraMemberSchema::toSchema_typeEnum(const utility::string_t& value) const
{
    
    if (value == utility::conversions::to_string_t("camera")) {
        return Schema_typeEnum::CAMERA;
    }
    
    if (value == utility::conversions::to_string_t("depth_camera")) {
        return Schema_typeEnum::DEPTH_CAMERA;
    }
    
    throw std::invalid_argument("Invalid value for conversion to Schema_typeEnum");
}


const utility::string_t RLTaskSceneEntityCameraMemberSchema::fromSchema_typeEnum(const Schema_typeEnum value) const
{
    switch(value)
    {
        
        case Schema_typeEnum::CAMERA: return utility::conversions::to_string_t("camera");
        
        case Schema_typeEnum::DEPTH_CAMERA: return utility::conversions::to_string_t("depth_camera");
        
    }
}


utility::string_t RLTaskSceneEntityCameraMemberSchema::getSchemaSensorName() const
{
    return m_Schema_sensor_name;
}


void RLTaskSceneEntityCameraMemberSchema::setSchemaSensorName(const utility::string_t& value)
{
    m_Schema_sensor_name = value;
    m_Schema_sensor_nameIsSet = true;
}

bool RLTaskSceneEntityCameraMemberSchema::schemaSensorNameIsSet() const
{
    return m_Schema_sensor_nameIsSet;
}

void RLTaskSceneEntityCameraMemberSchema::unsetSchema_sensor_name()
{
    m_Schema_sensor_nameIsSet = false;
}
RLTaskSceneEntityCameraMemberSchema::Schema_typeEnum RLTaskSceneEntityCameraMemberSchema::getSchemaType() const
{
    return m_Schema_type;
}


void RLTaskSceneEntityCameraMemberSchema::setSchemaType(const Schema_typeEnum value)
{
    m_Schema_type = value;
    m_Schema_typeIsSet = true;
}

bool RLTaskSceneEntityCameraMemberSchema::schemaTypeIsSet() const
{
    return m_Schema_typeIsSet;
}

void RLTaskSceneEntityCameraMemberSchema::unsetSchema_type()
{
    m_Schema_typeIsSet = false;
}
utility::string_t RLTaskSceneEntityCameraMemberSchema::getParentLink() const
{
    return m_Parent_link;
}


void RLTaskSceneEntityCameraMemberSchema::setParentLink(const utility::string_t& value)
{
    m_Parent_link = value;
    m_Parent_linkIsSet = true;
}

bool RLTaskSceneEntityCameraMemberSchema::parentLinkIsSet() const
{
    return m_Parent_linkIsSet;
}

void RLTaskSceneEntityCameraMemberSchema::unsetParent_link()
{
    m_Parent_linkIsSet = false;
}
int32_t RLTaskSceneEntityCameraMemberSchema::getWidth() const
{
    return m_Width.get();
}

void RLTaskSceneEntityCameraMemberSchema::setWidth(int32_t value)
{
    m_Width = value;
}

bool RLTaskSceneEntityCameraMemberSchema::widthIsSet() const
{
    return m_Width.has_value();
}

void RLTaskSceneEntityCameraMemberSchema::unsetWidth()
{
    m_Width.reset();
}
int32_t RLTaskSceneEntityCameraMemberSchema::getHeight() const
{
    return m_Height.get();
}

void RLTaskSceneEntityCameraMemberSchema::setHeight(int32_t value)
{
    m_Height = value;
}

bool RLTaskSceneEntityCameraMemberSchema::heightIsSet() const
{
    return m_Height.has_value();
}

void RLTaskSceneEntityCameraMemberSchema::unsetHeight()
{
    m_Height.reset();
}
double RLTaskSceneEntityCameraMemberSchema::getFovy() const
{
    return m_Fovy.get();
}

void RLTaskSceneEntityCameraMemberSchema::setFovy(double value)
{
    m_Fovy = value;
}

bool RLTaskSceneEntityCameraMemberSchema::fovyIsSet() const
{
    return m_Fovy.has_value();
}

void RLTaskSceneEntityCameraMemberSchema::unsetFovy()
{
    m_Fovy.reset();
}
double RLTaskSceneEntityCameraMemberSchema::getMinDepth() const
{
    return m_Min_depth.get();
}

void RLTaskSceneEntityCameraMemberSchema::setMinDepth(double value)
{
    m_Min_depth = value;
}

bool RLTaskSceneEntityCameraMemberSchema::minDepthIsSet() const
{
    return m_Min_depth.has_value();
}

void RLTaskSceneEntityCameraMemberSchema::unsetMin_depth()
{
    m_Min_depth.reset();
}
double RLTaskSceneEntityCameraMemberSchema::getMaxDepth() const
{
    return m_Max_depth.get();
}

void RLTaskSceneEntityCameraMemberSchema::setMaxDepth(double value)
{
    m_Max_depth = value;
}

bool RLTaskSceneEntityCameraMemberSchema::maxDepthIsSet() const
{
    return m_Max_depth.has_value();
}

void RLTaskSceneEntityCameraMemberSchema::unsetMax_depth()
{
    m_Max_depth.reset();
}
double RLTaskSceneEntityCameraMemberSchema::getUpdateRate() const
{
    return m_Update_rate.get();
}

void RLTaskSceneEntityCameraMemberSchema::setUpdateRate(double value)
{
    m_Update_rate = value;
}

bool RLTaskSceneEntityCameraMemberSchema::updateRateIsSet() const
{
    return m_Update_rate.has_value();
}

void RLTaskSceneEntityCameraMemberSchema::unsetUpdate_rate()
{
    m_Update_rate.reset();
}

}
}
}
}


