/**
 * Cyberwave API
 * Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.26.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/SceneWaypointCollectionPatchSchema.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

SceneWaypointCollectionPatchSchema::SceneWaypointCollectionPatchSchema()
{
    m_Id = utility::conversions::to_string_t("");
    m_IdIsSet = false;
}

SceneWaypointCollectionPatchSchema::~SceneWaypointCollectionPatchSchema()
{
}

void SceneWaypointCollectionPatchSchema::validate()
{
    // TODO: implement validation
}

web::json::value SceneWaypointCollectionPatchSchema::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_IdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_Collection.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("collection"))] = ModelBase::toJson(m_Collection.get());
    }

    return val;
}

bool SceneWaypointCollectionPatchSchema::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("collection"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("collection")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCollection;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCollection);
            setCollection(refVal_setCollection);
            
        }
    }
    return ok;
}

void SceneWaypointCollectionPatchSchema::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("id")), m_Id));
    }
    if(m_Collection.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("collection")), m_Collection.get()));
    }
}

bool SceneWaypointCollectionPatchSchema::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        utility::string_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("collection"))))
    {
        utility::string_t refVal_setCollection;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("collection"))), refVal_setCollection );
        setCollection(refVal_setCollection);
    }
    return ok;
}


utility::string_t SceneWaypointCollectionPatchSchema::getId() const
{
    return m_Id;
}


void SceneWaypointCollectionPatchSchema::setId(const utility::string_t& value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool SceneWaypointCollectionPatchSchema::idIsSet() const
{
    return m_IdIsSet;
}

void SceneWaypointCollectionPatchSchema::unsetId()
{
    m_IdIsSet = false;
}
utility::string_t SceneWaypointCollectionPatchSchema::getCollection() const
{
    return m_Collection.get();
}


void SceneWaypointCollectionPatchSchema::setCollection(const utility::string_t& value)
{
    m_Collection = value;
}

bool SceneWaypointCollectionPatchSchema::collectionIsSet() const
{
    return m_Collection.has_value();
}

void SceneWaypointCollectionPatchSchema::unsetCollection()
{
    m_Collection.reset();
}

}
}
}
}


