/**
 * Cyberwave API
 * Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.26.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/SensorMergePatchSchema.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

SensorMergePatchSchema::SensorMergePatchSchema()
{
    m_PatchIsSet = false;
}

SensorMergePatchSchema::~SensorMergePatchSchema()
{
}

void SensorMergePatchSchema::validate()
{
    // TODO: implement validation
}

web::json::value SensorMergePatchSchema::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_PatchIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("patch"))] = ModelBase::toJson(m_Patch);
    }
    if(m_Expected_schema_hash.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("expected_schema_hash"))] = ModelBase::toJson(m_Expected_schema_hash.get());
    }

    return val;
}

bool SensorMergePatchSchema::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("patch"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("patch")));
        if(!fieldValue.is_null())
        {
            std::map<utility::string_t, std::shared_ptr<AnyType>> refVal_setPatch;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPatch);
            setPatch(refVal_setPatch);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("expected_schema_hash"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("expected_schema_hash")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setExpectedSchemaHash;
            ok &= ModelBase::fromJson(fieldValue, refVal_setExpectedSchemaHash);
            setExpectedSchemaHash(refVal_setExpectedSchemaHash);
            
        }
    }
    return ok;
}

void SensorMergePatchSchema::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_PatchIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("patch")), m_Patch));
    }
    if(m_Expected_schema_hash.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("expected_schema_hash")), m_Expected_schema_hash.get()));
    }
}

bool SensorMergePatchSchema::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("patch"))))
    {
        std::map<utility::string_t, std::shared_ptr<AnyType>> refVal_setPatch;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("patch"))), refVal_setPatch );
        setPatch(refVal_setPatch);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("expected_schema_hash"))))
    {
        utility::string_t refVal_setExpectedSchemaHash;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("expected_schema_hash"))), refVal_setExpectedSchemaHash );
        setExpectedSchemaHash(refVal_setExpectedSchemaHash);
    }
    return ok;
}


std::map<utility::string_t, std::shared_ptr<AnyType>> SensorMergePatchSchema::getPatch() const
{
    return m_Patch;
}


void SensorMergePatchSchema::setPatch(const std::map<utility::string_t, std::shared_ptr<AnyType>>& value)
{
    m_Patch = value;
    m_PatchIsSet = true;
}

bool SensorMergePatchSchema::patchIsSet() const
{
    return m_PatchIsSet;
}

void SensorMergePatchSchema::unsetPatch()
{
    m_PatchIsSet = false;
}
utility::string_t SensorMergePatchSchema::getExpectedSchemaHash() const
{
    return m_Expected_schema_hash.get();
}


void SensorMergePatchSchema::setExpectedSchemaHash(const utility::string_t& value)
{
    m_Expected_schema_hash = value;
}

bool SensorMergePatchSchema::expectedSchemaHashIsSet() const
{
    return m_Expected_schema_hash.has_value();
}

void SensorMergePatchSchema::unsetExpected_schema_hash()
{
    m_Expected_schema_hash.reset();
}

}
}
}
}


