/**
 * Cyberwave API
 * Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.24.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/SlugCheckSchema.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

SlugCheckSchema::SlugCheckSchema()
{
    m_Available = false;
    m_AvailableIsSet = false;
    m_Slug = utility::conversions::to_string_t("");
    m_SlugIsSet = false;
}

SlugCheckSchema::~SlugCheckSchema()
{
}

void SlugCheckSchema::validate()
{
    // TODO: implement validation
}

web::json::value SlugCheckSchema::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_AvailableIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("available"))] = ModelBase::toJson(m_Available);
    }
    if(m_SlugIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("slug"))] = ModelBase::toJson(m_Slug);
    }
    if(m_Suggestion.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("suggestion"))] = ModelBase::toJson(m_Suggestion.get());
    }

    return val;
}

bool SlugCheckSchema::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("available"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("available")));
        if(!fieldValue.is_null())
        {
            bool refVal_setAvailable;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAvailable);
            setAvailable(refVal_setAvailable);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("slug"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("slug")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setSlug;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSlug);
            setSlug(refVal_setSlug);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("suggestion"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("suggestion")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setSuggestion;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSuggestion);
            setSuggestion(refVal_setSuggestion);
            
        }
    }
    return ok;
}

void SlugCheckSchema::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_AvailableIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("available")), m_Available));
    }
    if(m_SlugIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("slug")), m_Slug));
    }
    if(m_Suggestion.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("suggestion")), m_Suggestion.get()));
    }
}

bool SlugCheckSchema::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("available"))))
    {
        bool refVal_setAvailable;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("available"))), refVal_setAvailable );
        setAvailable(refVal_setAvailable);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("slug"))))
    {
        utility::string_t refVal_setSlug;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("slug"))), refVal_setSlug );
        setSlug(refVal_setSlug);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("suggestion"))))
    {
        utility::string_t refVal_setSuggestion;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("suggestion"))), refVal_setSuggestion );
        setSuggestion(refVal_setSuggestion);
    }
    return ok;
}


bool SlugCheckSchema::isAvailable() const
{
    return m_Available;
}

void SlugCheckSchema::setAvailable(bool value)
{
    m_Available = value;
    m_AvailableIsSet = true;
}

bool SlugCheckSchema::availableIsSet() const
{
    return m_AvailableIsSet;
}

void SlugCheckSchema::unsetAvailable()
{
    m_AvailableIsSet = false;
}
utility::string_t SlugCheckSchema::getSlug() const
{
    return m_Slug;
}


void SlugCheckSchema::setSlug(const utility::string_t& value)
{
    m_Slug = value;
    m_SlugIsSet = true;
}

bool SlugCheckSchema::slugIsSet() const
{
    return m_SlugIsSet;
}

void SlugCheckSchema::unsetSlug()
{
    m_SlugIsSet = false;
}
utility::string_t SlugCheckSchema::getSuggestion() const
{
    return m_Suggestion.get();
}


void SlugCheckSchema::setSuggestion(const utility::string_t& value)
{
    m_Suggestion = value;
}

bool SlugCheckSchema::suggestionIsSet() const
{
    return m_Suggestion.has_value();
}

void SlugCheckSchema::unsetSuggestion()
{
    m_Suggestion.reset();
}

}
}
}
}


