/**
 * Cyberwave API
 * Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.23.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/StorageMetricsSchema.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

StorageMetricsSchema::StorageMetricsSchema()
{
    m_WindowIsSet = false;
    m_TotalsIsSet = false;
    m_By_bucketIsSet = false;
    m_By_source_typeIsSet = false;
    m_By_dayIsSet = false;
}

StorageMetricsSchema::~StorageMetricsSchema()
{
}

void StorageMetricsSchema::validate()
{
    // TODO: implement validation
}

web::json::value StorageMetricsSchema::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_Workspace_uuid.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("workspace_uuid"))] = ModelBase::toJson(m_Workspace_uuid.get());
    }
    if(m_Organization_uuid.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("organization_uuid"))] = ModelBase::toJson(m_Organization_uuid.get());
    }
    if(m_WindowIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("window"))] = ModelBase::toJson(m_Window);
    }
    if(m_Snapshot_time.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("snapshot_time"))] = ModelBase::toJson(m_Snapshot_time.get());
    }
    if(m_TotalsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("totals"))] = ModelBase::toJson(m_Totals);
    }
    if(m_By_bucketIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("by_bucket"))] = ModelBase::toJson(m_By_bucket);
    }
    if(m_By_source_typeIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("by_source_type"))] = ModelBase::toJson(m_By_source_type);
    }
    if(m_By_dayIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("by_day"))] = ModelBase::toJson(m_By_day);
    }

    return val;
}

bool StorageMetricsSchema::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("workspace_uuid"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("workspace_uuid")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setWorkspaceUuid;
            ok &= ModelBase::fromJson(fieldValue, refVal_setWorkspaceUuid);
            setWorkspaceUuid(refVal_setWorkspaceUuid);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("organization_uuid"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("organization_uuid")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setOrganizationUuid;
            ok &= ModelBase::fromJson(fieldValue, refVal_setOrganizationUuid);
            setOrganizationUuid(refVal_setOrganizationUuid);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("window"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("window")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<MetricsWindowSchema> refVal_setWindow;
            ok &= ModelBase::fromJson(fieldValue, refVal_setWindow);
            setWindow(refVal_setWindow);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("snapshot_time"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("snapshot_time")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setSnapshotTime;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSnapshotTime);
            setSnapshotTime(refVal_setSnapshotTime);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("totals"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("totals")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<StorageUsageSummary> refVal_setTotals;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTotals);
            setTotals(refVal_setTotals);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("by_bucket"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("by_bucket")));
        if(!fieldValue.is_null())
        {
            std::map<utility::string_t, std::shared_ptr<StorageUsageSummary>> refVal_setByBucket;
            ok &= ModelBase::fromJson(fieldValue, refVal_setByBucket);
            setByBucket(refVal_setByBucket);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("by_source_type"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("by_source_type")));
        if(!fieldValue.is_null())
        {
            std::map<utility::string_t, std::shared_ptr<StorageUsageSummary>> refVal_setBySourceType;
            ok &= ModelBase::fromJson(fieldValue, refVal_setBySourceType);
            setBySourceType(refVal_setBySourceType);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("by_day"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("by_day")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<StorageUsageDayBucket>> refVal_setByDay;
            ok &= ModelBase::fromJson(fieldValue, refVal_setByDay);
            setByDay(refVal_setByDay);
            
        }
    }
    return ok;
}

void StorageMetricsSchema::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_Workspace_uuid.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("workspace_uuid")), m_Workspace_uuid.get()));
    }
    if(m_Organization_uuid.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("organization_uuid")), m_Organization_uuid.get()));
    }
    if(m_WindowIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("window")), m_Window));
    }
    if(m_Snapshot_time.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("snapshot_time")), m_Snapshot_time.get()));
    }
    if(m_TotalsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("totals")), m_Totals));
    }
    if(m_By_bucketIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("by_bucket")), m_By_bucket));
    }
    if(m_By_source_typeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("by_source_type")), m_By_source_type));
    }
    if(m_By_dayIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("by_day")), m_By_day));
    }
}

bool StorageMetricsSchema::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("workspace_uuid"))))
    {
        utility::string_t refVal_setWorkspaceUuid;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("workspace_uuid"))), refVal_setWorkspaceUuid );
        setWorkspaceUuid(refVal_setWorkspaceUuid);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("organization_uuid"))))
    {
        utility::string_t refVal_setOrganizationUuid;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("organization_uuid"))), refVal_setOrganizationUuid );
        setOrganizationUuid(refVal_setOrganizationUuid);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("window"))))
    {
        std::shared_ptr<MetricsWindowSchema> refVal_setWindow;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("window"))), refVal_setWindow );
        setWindow(refVal_setWindow);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("snapshot_time"))))
    {
        utility::datetime refVal_setSnapshotTime;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("snapshot_time"))), refVal_setSnapshotTime );
        setSnapshotTime(refVal_setSnapshotTime);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("totals"))))
    {
        std::shared_ptr<StorageUsageSummary> refVal_setTotals;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("totals"))), refVal_setTotals );
        setTotals(refVal_setTotals);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("by_bucket"))))
    {
        std::map<utility::string_t, std::shared_ptr<StorageUsageSummary>> refVal_setByBucket;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("by_bucket"))), refVal_setByBucket );
        setByBucket(refVal_setByBucket);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("by_source_type"))))
    {
        std::map<utility::string_t, std::shared_ptr<StorageUsageSummary>> refVal_setBySourceType;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("by_source_type"))), refVal_setBySourceType );
        setBySourceType(refVal_setBySourceType);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("by_day"))))
    {
        std::vector<std::shared_ptr<StorageUsageDayBucket>> refVal_setByDay;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("by_day"))), refVal_setByDay );
        setByDay(refVal_setByDay);
    }
    return ok;
}


utility::string_t StorageMetricsSchema::getWorkspaceUuid() const
{
    return m_Workspace_uuid.get();
}


void StorageMetricsSchema::setWorkspaceUuid(const utility::string_t& value)
{
    m_Workspace_uuid = value;
}

bool StorageMetricsSchema::workspaceUuidIsSet() const
{
    return m_Workspace_uuid.has_value();
}

void StorageMetricsSchema::unsetWorkspace_uuid()
{
    m_Workspace_uuid.reset();
}
utility::string_t StorageMetricsSchema::getOrganizationUuid() const
{
    return m_Organization_uuid.get();
}


void StorageMetricsSchema::setOrganizationUuid(const utility::string_t& value)
{
    m_Organization_uuid = value;
}

bool StorageMetricsSchema::organizationUuidIsSet() const
{
    return m_Organization_uuid.has_value();
}

void StorageMetricsSchema::unsetOrganization_uuid()
{
    m_Organization_uuid.reset();
}
std::shared_ptr<MetricsWindowSchema> StorageMetricsSchema::getWindow() const
{
    return m_Window;
}


void StorageMetricsSchema::setWindow(const std::shared_ptr<MetricsWindowSchema>& value)
{
    m_Window = value;
    m_WindowIsSet = true;
}

bool StorageMetricsSchema::windowIsSet() const
{
    return m_WindowIsSet;
}

void StorageMetricsSchema::unsetWindow()
{
    m_WindowIsSet = false;
}
utility::datetime StorageMetricsSchema::getSnapshotTime() const
{
    return m_Snapshot_time.get();
}


void StorageMetricsSchema::setSnapshotTime(const utility::datetime& value)
{
    m_Snapshot_time = value;
}

bool StorageMetricsSchema::snapshotTimeIsSet() const
{
    return m_Snapshot_time.has_value();
}

void StorageMetricsSchema::unsetSnapshot_time()
{
    m_Snapshot_time.reset();
}
std::shared_ptr<StorageUsageSummary> StorageMetricsSchema::getTotals() const
{
    return m_Totals;
}


void StorageMetricsSchema::setTotals(const std::shared_ptr<StorageUsageSummary>& value)
{
    m_Totals = value;
    m_TotalsIsSet = true;
}

bool StorageMetricsSchema::totalsIsSet() const
{
    return m_TotalsIsSet;
}

void StorageMetricsSchema::unsetTotals()
{
    m_TotalsIsSet = false;
}
std::map<utility::string_t, std::shared_ptr<StorageUsageSummary>> StorageMetricsSchema::getByBucket() const
{
    return m_By_bucket;
}


void StorageMetricsSchema::setByBucket(const std::map<utility::string_t, std::shared_ptr<StorageUsageSummary>>& value)
{
    m_By_bucket = value;
    m_By_bucketIsSet = true;
}

bool StorageMetricsSchema::byBucketIsSet() const
{
    return m_By_bucketIsSet;
}

void StorageMetricsSchema::unsetBy_bucket()
{
    m_By_bucketIsSet = false;
}
std::map<utility::string_t, std::shared_ptr<StorageUsageSummary>> StorageMetricsSchema::getBySourceType() const
{
    return m_By_source_type;
}


void StorageMetricsSchema::setBySourceType(const std::map<utility::string_t, std::shared_ptr<StorageUsageSummary>>& value)
{
    m_By_source_type = value;
    m_By_source_typeIsSet = true;
}

bool StorageMetricsSchema::bySourceTypeIsSet() const
{
    return m_By_source_typeIsSet;
}

void StorageMetricsSchema::unsetBy_source_type()
{
    m_By_source_typeIsSet = false;
}
std::vector<std::shared_ptr<StorageUsageDayBucket>> StorageMetricsSchema::getByDay() const
{
    return m_By_day;
}


void StorageMetricsSchema::setByDay(const std::vector<std::shared_ptr<StorageUsageDayBucket>>& value)
{
    m_By_day = value;
    m_By_dayIsSet = true;
}

bool StorageMetricsSchema::byDayIsSet() const
{
    return m_By_dayIsSet;
}

void StorageMetricsSchema::unsetBy_day()
{
    m_By_dayIsSet = false;
}

}
}
}
}


