/**
 * Cyberwave API
 * Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.23.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/TargetPoseSchema.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

TargetPoseSchema::TargetPoseSchema()
{
    m_PositionIsSet = false;
    m_QuaternionIsSet = false;
}

TargetPoseSchema::~TargetPoseSchema()
{
}

void TargetPoseSchema::validate()
{
    // TODO: implement validation
}

web::json::value TargetPoseSchema::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_PositionIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("position"))] = ModelBase::toJson(m_Position);
    }
    if(m_QuaternionIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("quaternion"))] = ModelBase::toJson(m_Quaternion);
    }

    return val;
}

bool TargetPoseSchema::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("position"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("position")));
        if(!fieldValue.is_null())
        {
            std::vector<double> refVal_setPosition;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPosition);
            setPosition(refVal_setPosition);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("quaternion"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("quaternion")));
        if(!fieldValue.is_null())
        {
            std::vector<double> refVal_setQuaternion;
            ok &= ModelBase::fromJson(fieldValue, refVal_setQuaternion);
            setQuaternion(refVal_setQuaternion);
            
        }
    }
    return ok;
}

void TargetPoseSchema::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_PositionIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("position")), m_Position));
    }
    if(m_QuaternionIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("quaternion")), m_Quaternion));
    }
}

bool TargetPoseSchema::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("position"))))
    {
        std::vector<double> refVal_setPosition;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("position"))), refVal_setPosition );
        setPosition(refVal_setPosition);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("quaternion"))))
    {
        std::vector<double> refVal_setQuaternion;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("quaternion"))), refVal_setQuaternion );
        setQuaternion(refVal_setQuaternion);
    }
    return ok;
}


std::vector<double> TargetPoseSchema::getPosition() const
{
    return m_Position;
}

void TargetPoseSchema::setPosition(std::vector<double> value)
{
    m_Position = value;
    m_PositionIsSet = true;
}

bool TargetPoseSchema::positionIsSet() const
{
    return m_PositionIsSet;
}

void TargetPoseSchema::unsetPosition()
{
    m_PositionIsSet = false;
}
std::vector<double> TargetPoseSchema::getQuaternion() const
{
    return m_Quaternion;
}

void TargetPoseSchema::setQuaternion(std::vector<double> value)
{
    m_Quaternion = value;
    m_QuaternionIsSet = true;
}

bool TargetPoseSchema::quaternionIsSet() const
{
    return m_QuaternionIsSet;
}

void TargetPoseSchema::unsetQuaternion()
{
    m_QuaternionIsSet = false;
}

}
}
}
}


