/**
 * Cyberwave API
 * Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.24.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/TransactionInvoiceSchema.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

TransactionInvoiceSchema::TransactionInvoiceSchema()
{
    m_Invoice_id = utility::conversions::to_string_t("");
    m_Invoice_idIsSet = false;
}

TransactionInvoiceSchema::~TransactionInvoiceSchema()
{
}

void TransactionInvoiceSchema::validate()
{
    // TODO: implement validation
}

web::json::value TransactionInvoiceSchema::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_Invoice_idIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("invoice_id"))] = ModelBase::toJson(m_Invoice_id);
    }
    if(m_number.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("number"))] = ModelBase::toJson(m_number.get());
    }
    if(m_Hosted_invoice_url.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("hosted_invoice_url"))] = ModelBase::toJson(m_Hosted_invoice_url.get());
    }
    if(m_Invoice_pdf.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("invoice_pdf"))] = ModelBase::toJson(m_Invoice_pdf.get());
    }

    return val;
}

bool TransactionInvoiceSchema::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("invoice_id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("invoice_id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setInvoiceId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setInvoiceId);
            setInvoiceId(refVal_setInvoiceId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("number"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("number")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setNumber;
            ok &= ModelBase::fromJson(fieldValue, refVal_setNumber);
            setNumber(refVal_setNumber);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("hosted_invoice_url"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("hosted_invoice_url")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setHostedInvoiceUrl;
            ok &= ModelBase::fromJson(fieldValue, refVal_setHostedInvoiceUrl);
            setHostedInvoiceUrl(refVal_setHostedInvoiceUrl);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("invoice_pdf"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("invoice_pdf")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setInvoicePdf;
            ok &= ModelBase::fromJson(fieldValue, refVal_setInvoicePdf);
            setInvoicePdf(refVal_setInvoicePdf);
            
        }
    }
    return ok;
}

void TransactionInvoiceSchema::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_Invoice_idIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("invoice_id")), m_Invoice_id));
    }
    if(m_number.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("number")), m_number.get()));
    }
    if(m_Hosted_invoice_url.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("hosted_invoice_url")), m_Hosted_invoice_url.get()));
    }
    if(m_Invoice_pdf.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("invoice_pdf")), m_Invoice_pdf.get()));
    }
}

bool TransactionInvoiceSchema::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("invoice_id"))))
    {
        utility::string_t refVal_setInvoiceId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("invoice_id"))), refVal_setInvoiceId );
        setInvoiceId(refVal_setInvoiceId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("number"))))
    {
        utility::string_t refVal_setNumber;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("number"))), refVal_setNumber );
        setNumber(refVal_setNumber);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("hosted_invoice_url"))))
    {
        utility::string_t refVal_setHostedInvoiceUrl;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("hosted_invoice_url"))), refVal_setHostedInvoiceUrl );
        setHostedInvoiceUrl(refVal_setHostedInvoiceUrl);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("invoice_pdf"))))
    {
        utility::string_t refVal_setInvoicePdf;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("invoice_pdf"))), refVal_setInvoicePdf );
        setInvoicePdf(refVal_setInvoicePdf);
    }
    return ok;
}


utility::string_t TransactionInvoiceSchema::getInvoiceId() const
{
    return m_Invoice_id;
}


void TransactionInvoiceSchema::setInvoiceId(const utility::string_t& value)
{
    m_Invoice_id = value;
    m_Invoice_idIsSet = true;
}

bool TransactionInvoiceSchema::invoiceIdIsSet() const
{
    return m_Invoice_idIsSet;
}

void TransactionInvoiceSchema::unsetInvoice_id()
{
    m_Invoice_idIsSet = false;
}
utility::string_t TransactionInvoiceSchema::getNumber() const
{
    return m_number.get();
}


void TransactionInvoiceSchema::setNumber(const utility::string_t& value)
{
    m_number = value;
}

bool TransactionInvoiceSchema::numberIsSet() const
{
    return m_number.has_value();
}

void TransactionInvoiceSchema::unsetnumber()
{
    m_number.reset();
}
utility::string_t TransactionInvoiceSchema::getHostedInvoiceUrl() const
{
    return m_Hosted_invoice_url.get();
}


void TransactionInvoiceSchema::setHostedInvoiceUrl(const utility::string_t& value)
{
    m_Hosted_invoice_url = value;
}

bool TransactionInvoiceSchema::hostedInvoiceUrlIsSet() const
{
    return m_Hosted_invoice_url.has_value();
}

void TransactionInvoiceSchema::unsetHosted_invoice_url()
{
    m_Hosted_invoice_url.reset();
}
utility::string_t TransactionInvoiceSchema::getInvoicePdf() const
{
    return m_Invoice_pdf.get();
}


void TransactionInvoiceSchema::setInvoicePdf(const utility::string_t& value)
{
    m_Invoice_pdf = value;
}

bool TransactionInvoiceSchema::invoicePdfIsSet() const
{
    return m_Invoice_pdf.has_value();
}

void TransactionInvoiceSchema::unsetInvoice_pdf()
{
    m_Invoice_pdf.reset();
}

}
}
}
}


