/**
 * Cyberwave API
 * Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.23.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/URDFProjectSchema.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

URDFProjectSchema::URDFProjectSchema()
{
    m_Uuid = utility::conversions::to_string_t("");
    m_UuidIsSet = false;
    m_Slug = utility::conversions::to_string_t("");
    m_SlugIsSet = false;
    m_Asset_uuid = utility::conversions::to_string_t("");
    m_Asset_uuidIsSet = false;
    m_Created_at = utility::datetime();
    m_Created_atIsSet = false;
    m_Updated_at = utility::datetime();
    m_Updated_atIsSet = false;
    m_Created_by = utility::conversions::to_string_t("");
    m_Created_byIsSet = false;
    m_Updated_by = utility::conversions::to_string_t("");
    m_Updated_byIsSet = false;
}

URDFProjectSchema::~URDFProjectSchema()
{
}

void URDFProjectSchema::validate()
{
    // TODO: implement validation
}

web::json::value URDFProjectSchema::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_UuidIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("uuid"))] = ModelBase::toJson(m_Uuid);
    }
    if(m_SlugIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("slug"))] = ModelBase::toJson(m_Slug);
    }
    if(m_Asset_uuidIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("asset_uuid"))] = ModelBase::toJson(m_Asset_uuid);
    }
    if(m_Main_file_path.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("main_file_path"))] = ModelBase::toJson(m_Main_file_path.get());
    }
    if(m_Created_atIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("created_at"))] = ModelBase::toJson(m_Created_at);
    }
    if(m_Updated_atIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("updated_at"))] = ModelBase::toJson(m_Updated_at);
    }
    if(m_Created_byIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("created_by"))] = ModelBase::toJson(m_Created_by);
    }
    if(m_Updated_byIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("updated_by"))] = ModelBase::toJson(m_Updated_by);
    }

    return val;
}

bool URDFProjectSchema::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("uuid"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("uuid")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setUuid;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUuid);
            setUuid(refVal_setUuid);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("slug"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("slug")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setSlug;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSlug);
            setSlug(refVal_setSlug);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("asset_uuid"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("asset_uuid")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setAssetUuid;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAssetUuid);
            setAssetUuid(refVal_setAssetUuid);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("main_file_path"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("main_file_path")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setMainFilePath;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMainFilePath);
            setMainFilePath(refVal_setMainFilePath);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("created_at"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("created_at")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setCreatedAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCreatedAt);
            setCreatedAt(refVal_setCreatedAt);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("updated_at"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("updated_at")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setUpdatedAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUpdatedAt);
            setUpdatedAt(refVal_setUpdatedAt);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("created_by"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("created_by")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCreatedBy;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCreatedBy);
            setCreatedBy(refVal_setCreatedBy);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("updated_by"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("updated_by")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setUpdatedBy;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUpdatedBy);
            setUpdatedBy(refVal_setUpdatedBy);
            
        }
    }
    return ok;
}

void URDFProjectSchema::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_UuidIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("uuid")), m_Uuid));
    }
    if(m_SlugIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("slug")), m_Slug));
    }
    if(m_Asset_uuidIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("asset_uuid")), m_Asset_uuid));
    }
    if(m_Main_file_path.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("main_file_path")), m_Main_file_path.get()));
    }
    if(m_Created_atIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("created_at")), m_Created_at));
    }
    if(m_Updated_atIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("updated_at")), m_Updated_at));
    }
    if(m_Created_byIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("created_by")), m_Created_by));
    }
    if(m_Updated_byIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("updated_by")), m_Updated_by));
    }
}

bool URDFProjectSchema::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("uuid"))))
    {
        utility::string_t refVal_setUuid;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("uuid"))), refVal_setUuid );
        setUuid(refVal_setUuid);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("slug"))))
    {
        utility::string_t refVal_setSlug;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("slug"))), refVal_setSlug );
        setSlug(refVal_setSlug);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("asset_uuid"))))
    {
        utility::string_t refVal_setAssetUuid;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("asset_uuid"))), refVal_setAssetUuid );
        setAssetUuid(refVal_setAssetUuid);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("main_file_path"))))
    {
        utility::string_t refVal_setMainFilePath;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("main_file_path"))), refVal_setMainFilePath );
        setMainFilePath(refVal_setMainFilePath);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("created_at"))))
    {
        utility::datetime refVal_setCreatedAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("created_at"))), refVal_setCreatedAt );
        setCreatedAt(refVal_setCreatedAt);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("updated_at"))))
    {
        utility::datetime refVal_setUpdatedAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("updated_at"))), refVal_setUpdatedAt );
        setUpdatedAt(refVal_setUpdatedAt);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("created_by"))))
    {
        utility::string_t refVal_setCreatedBy;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("created_by"))), refVal_setCreatedBy );
        setCreatedBy(refVal_setCreatedBy);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("updated_by"))))
    {
        utility::string_t refVal_setUpdatedBy;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("updated_by"))), refVal_setUpdatedBy );
        setUpdatedBy(refVal_setUpdatedBy);
    }
    return ok;
}


utility::string_t URDFProjectSchema::getUuid() const
{
    return m_Uuid;
}


void URDFProjectSchema::setUuid(const utility::string_t& value)
{
    m_Uuid = value;
    m_UuidIsSet = true;
}

bool URDFProjectSchema::uuidIsSet() const
{
    return m_UuidIsSet;
}

void URDFProjectSchema::unsetUuid()
{
    m_UuidIsSet = false;
}
utility::string_t URDFProjectSchema::getSlug() const
{
    return m_Slug;
}


void URDFProjectSchema::setSlug(const utility::string_t& value)
{
    m_Slug = value;
    m_SlugIsSet = true;
}

bool URDFProjectSchema::slugIsSet() const
{
    return m_SlugIsSet;
}

void URDFProjectSchema::unsetSlug()
{
    m_SlugIsSet = false;
}
utility::string_t URDFProjectSchema::getAssetUuid() const
{
    return m_Asset_uuid;
}


void URDFProjectSchema::setAssetUuid(const utility::string_t& value)
{
    m_Asset_uuid = value;
    m_Asset_uuidIsSet = true;
}

bool URDFProjectSchema::assetUuidIsSet() const
{
    return m_Asset_uuidIsSet;
}

void URDFProjectSchema::unsetAsset_uuid()
{
    m_Asset_uuidIsSet = false;
}
utility::string_t URDFProjectSchema::getMainFilePath() const
{
    return m_Main_file_path.get();
}


void URDFProjectSchema::setMainFilePath(const utility::string_t& value)
{
    m_Main_file_path = value;
}

bool URDFProjectSchema::mainFilePathIsSet() const
{
    return m_Main_file_path.has_value();
}

void URDFProjectSchema::unsetMain_file_path()
{
    m_Main_file_path.reset();
}
utility::datetime URDFProjectSchema::getCreatedAt() const
{
    return m_Created_at;
}


void URDFProjectSchema::setCreatedAt(const utility::datetime& value)
{
    m_Created_at = value;
    m_Created_atIsSet = true;
}

bool URDFProjectSchema::createdAtIsSet() const
{
    return m_Created_atIsSet;
}

void URDFProjectSchema::unsetCreated_at()
{
    m_Created_atIsSet = false;
}
utility::datetime URDFProjectSchema::getUpdatedAt() const
{
    return m_Updated_at;
}


void URDFProjectSchema::setUpdatedAt(const utility::datetime& value)
{
    m_Updated_at = value;
    m_Updated_atIsSet = true;
}

bool URDFProjectSchema::updatedAtIsSet() const
{
    return m_Updated_atIsSet;
}

void URDFProjectSchema::unsetUpdated_at()
{
    m_Updated_atIsSet = false;
}
utility::string_t URDFProjectSchema::getCreatedBy() const
{
    return m_Created_by;
}


void URDFProjectSchema::setCreatedBy(const utility::string_t& value)
{
    m_Created_by = value;
    m_Created_byIsSet = true;
}

bool URDFProjectSchema::createdByIsSet() const
{
    return m_Created_byIsSet;
}

void URDFProjectSchema::unsetCreated_by()
{
    m_Created_byIsSet = false;
}
utility::string_t URDFProjectSchema::getUpdatedBy() const
{
    return m_Updated_by;
}


void URDFProjectSchema::setUpdatedBy(const utility::string_t& value)
{
    m_Updated_by = value;
    m_Updated_byIsSet = true;
}

bool URDFProjectSchema::updatedByIsSet() const
{
    return m_Updated_byIsSet;
}

void URDFProjectSchema::unsetUpdated_by()
{
    m_Updated_byIsSet = false;
}

}
}
}
}


