/**
 * Cyberwave API
 * Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.24.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/WorkflowExecuteSchema.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

WorkflowExecuteSchema::WorkflowExecuteSchema()
{
}

WorkflowExecuteSchema::~WorkflowExecuteSchema()
{
}

void WorkflowExecuteSchema::validate()
{
    // TODO: implement validation
}

web::json::value WorkflowExecuteSchema::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_Trigger_data.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("trigger_data"))] = ModelBase::toJson(m_Trigger_data.get());
    }

    return val;
}

bool WorkflowExecuteSchema::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("trigger_data"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("trigger_data")));
        if(!fieldValue.is_null())
        {
            std::map<utility::string_t, std::shared_ptr<AnyType>> refVal_setTriggerData;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTriggerData);
            setTriggerData(refVal_setTriggerData);
            
        }
    }
    return ok;
}

void WorkflowExecuteSchema::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_Trigger_data.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("trigger_data")), m_Trigger_data.get()));
    }
}

bool WorkflowExecuteSchema::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("trigger_data"))))
    {
        std::map<utility::string_t, std::shared_ptr<AnyType>> refVal_setTriggerData;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("trigger_data"))), refVal_setTriggerData );
        setTriggerData(refVal_setTriggerData);
    }
    return ok;
}


std::map<utility::string_t, std::shared_ptr<AnyType>> WorkflowExecuteSchema::getTriggerData() const
{
    return m_Trigger_data.get();
}


void WorkflowExecuteSchema::setTriggerData(const std::map<utility::string_t, std::shared_ptr<AnyType>>& value)
{
    m_Trigger_data = value;
}

bool WorkflowExecuteSchema::triggerDataIsSet() const
{
    return m_Trigger_data.has_value();
}

void WorkflowExecuteSchema::unsetTrigger_data()
{
    m_Trigger_data.reset();
}

}
}
}
}


