/**
 * Cyberwave API
 * Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.23.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/WorkflowUpdateSchema.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

WorkflowUpdateSchema::WorkflowUpdateSchema()
{
}

WorkflowUpdateSchema::~WorkflowUpdateSchema()
{
}

void WorkflowUpdateSchema::validate()
{
    // TODO: implement validation
}

web::json::value WorkflowUpdateSchema::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_Name.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("name"))] = ModelBase::toJson(m_Name.get());
    }
    if(m_Slug.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("slug"))] = ModelBase::toJson(m_Slug.get());
    }
    if(m_Description.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("description"))] = ModelBase::toJson(m_Description.get());
    }
    if(m_Is_active.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("is_active"))] = ModelBase::toJson(m_Is_active.get());
    }
    if(m_Visibility.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("visibility"))] = ModelBase::toJson(m_Visibility.get());
    }
    if(m_Environment_uuid.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("environment_uuid"))] = ModelBase::toJson(m_Environment_uuid.get());
    }
    if(m_Run_on_edge.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("run_on_edge"))] = ModelBase::toJson(m_Run_on_edge.get());
    }
    if(m_Execution_target.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("execution_target"))] = ModelBase::toJson(m_Execution_target.get());
    }
    if(m_Metadata.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("metadata"))] = ModelBase::toJson(m_Metadata.get());
    }
    if(m_Tags.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("tags"))] = ModelBase::toJson(m_Tags.get());
    }
    if(m_Is_template.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("is_template"))] = ModelBase::toJson(m_Is_template.get());
    }

    return val;
}

bool WorkflowUpdateSchema::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setName);
            setName(refVal_setName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("slug"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("slug")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setSlug;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSlug);
            setSlug(refVal_setSlug);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("description"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("description")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setDescription;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDescription);
            setDescription(refVal_setDescription);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("is_active"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("is_active")));
        if(!fieldValue.is_null())
        {
            bool refVal_setIsActive;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIsActive);
            setIsActive(refVal_setIsActive);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("visibility"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("visibility")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setVisibility;
            ok &= ModelBase::fromJson(fieldValue, refVal_setVisibility);
            setVisibility(refVal_setVisibility);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("environment_uuid"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("environment_uuid")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setEnvironmentUuid;
            ok &= ModelBase::fromJson(fieldValue, refVal_setEnvironmentUuid);
            setEnvironmentUuid(refVal_setEnvironmentUuid);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("run_on_edge"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("run_on_edge")));
        if(!fieldValue.is_null())
        {
            bool refVal_setRunOnEdge;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRunOnEdge);
            setRunOnEdge(refVal_setRunOnEdge);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("execution_target"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("execution_target")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setExecutionTarget;
            ok &= ModelBase::fromJson(fieldValue, refVal_setExecutionTarget);
            setExecutionTarget(refVal_setExecutionTarget);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("metadata"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("metadata")));
        if(!fieldValue.is_null())
        {
            std::map<utility::string_t, std::shared_ptr<AnyType>> refVal_setMetadata;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMetadata);
            setMetadata(refVal_setMetadata);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("tags"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("tags")));
        if(!fieldValue.is_null())
        {
            std::vector<utility::string_t> refVal_setTags;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTags);
            setTags(refVal_setTags);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("is_template"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("is_template")));
        if(!fieldValue.is_null())
        {
            bool refVal_setIsTemplate;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIsTemplate);
            setIsTemplate(refVal_setIsTemplate);
            
        }
    }
    return ok;
}

void WorkflowUpdateSchema::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_Name.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("name")), m_Name.get()));
    }
    if(m_Slug.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("slug")), m_Slug.get()));
    }
    if(m_Description.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("description")), m_Description.get()));
    }
    if(m_Is_active.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("is_active")), m_Is_active.get()));
    }
    if(m_Visibility.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("visibility")), m_Visibility.get()));
    }
    if(m_Environment_uuid.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("environment_uuid")), m_Environment_uuid.get()));
    }
    if(m_Run_on_edge.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("run_on_edge")), m_Run_on_edge.get()));
    }
    if(m_Execution_target.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("execution_target")), m_Execution_target.get()));
    }
    if(m_Metadata.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("metadata")), m_Metadata.get()));
    }
    if(m_Tags.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("tags")), m_Tags.get()));
    }
    if(m_Is_template.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("is_template")), m_Is_template.get()));
    }
}

bool WorkflowUpdateSchema::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        utility::string_t refVal_setName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("name"))), refVal_setName );
        setName(refVal_setName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("slug"))))
    {
        utility::string_t refVal_setSlug;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("slug"))), refVal_setSlug );
        setSlug(refVal_setSlug);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("description"))))
    {
        utility::string_t refVal_setDescription;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("description"))), refVal_setDescription );
        setDescription(refVal_setDescription);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("is_active"))))
    {
        bool refVal_setIsActive;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("is_active"))), refVal_setIsActive );
        setIsActive(refVal_setIsActive);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("visibility"))))
    {
        utility::string_t refVal_setVisibility;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("visibility"))), refVal_setVisibility );
        setVisibility(refVal_setVisibility);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("environment_uuid"))))
    {
        utility::string_t refVal_setEnvironmentUuid;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("environment_uuid"))), refVal_setEnvironmentUuid );
        setEnvironmentUuid(refVal_setEnvironmentUuid);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("run_on_edge"))))
    {
        bool refVal_setRunOnEdge;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("run_on_edge"))), refVal_setRunOnEdge );
        setRunOnEdge(refVal_setRunOnEdge);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("execution_target"))))
    {
        utility::string_t refVal_setExecutionTarget;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("execution_target"))), refVal_setExecutionTarget );
        setExecutionTarget(refVal_setExecutionTarget);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("metadata"))))
    {
        std::map<utility::string_t, std::shared_ptr<AnyType>> refVal_setMetadata;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("metadata"))), refVal_setMetadata );
        setMetadata(refVal_setMetadata);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("tags"))))
    {
        std::vector<utility::string_t> refVal_setTags;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("tags"))), refVal_setTags );
        setTags(refVal_setTags);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("is_template"))))
    {
        bool refVal_setIsTemplate;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("is_template"))), refVal_setIsTemplate );
        setIsTemplate(refVal_setIsTemplate);
    }
    return ok;
}


utility::string_t WorkflowUpdateSchema::getName() const
{
    return m_Name.get();
}


void WorkflowUpdateSchema::setName(const utility::string_t& value)
{
    m_Name = value;
}

bool WorkflowUpdateSchema::nameIsSet() const
{
    return m_Name.has_value();
}

void WorkflowUpdateSchema::unsetName()
{
    m_Name.reset();
}
utility::string_t WorkflowUpdateSchema::getSlug() const
{
    return m_Slug.get();
}


void WorkflowUpdateSchema::setSlug(const utility::string_t& value)
{
    m_Slug = value;
}

bool WorkflowUpdateSchema::slugIsSet() const
{
    return m_Slug.has_value();
}

void WorkflowUpdateSchema::unsetSlug()
{
    m_Slug.reset();
}
utility::string_t WorkflowUpdateSchema::getDescription() const
{
    return m_Description.get();
}


void WorkflowUpdateSchema::setDescription(const utility::string_t& value)
{
    m_Description = value;
}

bool WorkflowUpdateSchema::descriptionIsSet() const
{
    return m_Description.has_value();
}

void WorkflowUpdateSchema::unsetDescription()
{
    m_Description.reset();
}
bool WorkflowUpdateSchema::isIsActive() const
{
    return m_Is_active.get();
}

void WorkflowUpdateSchema::setIsActive(bool value)
{
    m_Is_active = value;
}

bool WorkflowUpdateSchema::isActiveIsSet() const
{
    return m_Is_active.has_value();
}

void WorkflowUpdateSchema::unsetIs_active()
{
    m_Is_active.reset();
}
utility::string_t WorkflowUpdateSchema::getVisibility() const
{
    return m_Visibility.get();
}


void WorkflowUpdateSchema::setVisibility(const utility::string_t& value)
{
    m_Visibility = value;
}

bool WorkflowUpdateSchema::visibilityIsSet() const
{
    return m_Visibility.has_value();
}

void WorkflowUpdateSchema::unsetVisibility()
{
    m_Visibility.reset();
}
utility::string_t WorkflowUpdateSchema::getEnvironmentUuid() const
{
    return m_Environment_uuid.get();
}


void WorkflowUpdateSchema::setEnvironmentUuid(const utility::string_t& value)
{
    m_Environment_uuid = value;
}

bool WorkflowUpdateSchema::environmentUuidIsSet() const
{
    return m_Environment_uuid.has_value();
}

void WorkflowUpdateSchema::unsetEnvironment_uuid()
{
    m_Environment_uuid.reset();
}
bool WorkflowUpdateSchema::isRunOnEdge() const
{
    return m_Run_on_edge.get();
}

void WorkflowUpdateSchema::setRunOnEdge(bool value)
{
    m_Run_on_edge = value;
}

bool WorkflowUpdateSchema::runOnEdgeIsSet() const
{
    return m_Run_on_edge.has_value();
}

void WorkflowUpdateSchema::unsetRun_on_edge()
{
    m_Run_on_edge.reset();
}
utility::string_t WorkflowUpdateSchema::getExecutionTarget() const
{
    return m_Execution_target.get();
}


void WorkflowUpdateSchema::setExecutionTarget(const utility::string_t& value)
{
    m_Execution_target = value;
}

bool WorkflowUpdateSchema::executionTargetIsSet() const
{
    return m_Execution_target.has_value();
}

void WorkflowUpdateSchema::unsetExecution_target()
{
    m_Execution_target.reset();
}
std::map<utility::string_t, std::shared_ptr<AnyType>> WorkflowUpdateSchema::getMetadata() const
{
    return m_Metadata.get();
}


void WorkflowUpdateSchema::setMetadata(const std::map<utility::string_t, std::shared_ptr<AnyType>>& value)
{
    m_Metadata = value;
}

bool WorkflowUpdateSchema::metadataIsSet() const
{
    return m_Metadata.has_value();
}

void WorkflowUpdateSchema::unsetMetadata()
{
    m_Metadata.reset();
}
std::vector<utility::string_t> WorkflowUpdateSchema::getTags() const
{
    return m_Tags.get();
}


void WorkflowUpdateSchema::setTags(const std::vector<utility::string_t>& value)
{
    m_Tags = value;
}

bool WorkflowUpdateSchema::tagsIsSet() const
{
    return m_Tags.has_value();
}

void WorkflowUpdateSchema::unsetTags()
{
    m_Tags.reset();
}
bool WorkflowUpdateSchema::isIsTemplate() const
{
    return m_Is_template.get();
}

void WorkflowUpdateSchema::setIsTemplate(bool value)
{
    m_Is_template = value;
}

bool WorkflowUpdateSchema::isTemplateIsSet() const
{
    return m_Is_template.has_value();
}

void WorkflowUpdateSchema::unsetIs_template()
{
    m_Is_template.reset();
}

}
}
}
}


