/**
 * Cyberwave API
 * Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * CloudNodeWorkloadCompleteSchema.h
 *
 * Optional body for POST /{uuid}/complete.  Allows the cloud-node process to attach inline result data when marking a workload as completed, so the backend persists it before firing &#x60;&#x60;complete_workload_task&#x60;&#x60;.
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_CloudNodeWorkloadCompleteSchema_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_CloudNodeWorkloadCompleteSchema_H_

#include <boost/optional.hpp>

#include "CppRestOpenAPIClient/ModelBase.h"

#include <map>
#include "CppRestOpenAPIClient/AnyType.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



/// <summary>
/// Optional body for POST /{uuid}/complete.  Allows the cloud-node process to attach inline result data when marking a workload as completed, so the backend persists it before firing &#x60;&#x60;complete_workload_task&#x60;&#x60;.
/// </summary>
class  CloudNodeWorkloadCompleteSchema
    : public ModelBase
{
public:
    CloudNodeWorkloadCompleteSchema();
    virtual ~CloudNodeWorkloadCompleteSchema();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// CloudNodeWorkloadCompleteSchema members


    std::map<utility::string_t, std::shared_ptr<AnyType>> getResult() const;
    bool resultIsSet() const;
    void unsetResult();
    void setResult(const std::map<utility::string_t, std::shared_ptr<AnyType>>& value);

    bool isSuccess() const;
    bool successIsSet() const;
    void unsetSuccess();
    void setSuccess(bool value);


protected:
    boost::optional<std::map<utility::string_t, std::shared_ptr<AnyType>>> m_Result;

    bool m_Success;
    bool m_SuccessIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_CloudNodeWorkloadCompleteSchema_H_ */
