/**
 * Cyberwave API
 * Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.21.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ContactSubmissionUpdateSchema.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_ContactSubmissionUpdateSchema_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_ContactSubmissionUpdateSchema_H_

#include <boost/optional.hpp>

#include "CppRestOpenAPIClient/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {



class  ContactSubmissionUpdateSchema
    : public ModelBase
{
public:
    ContactSubmissionUpdateSchema();
    virtual ~ContactSubmissionUpdateSchema();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// ContactSubmissionUpdateSchema members


    utility::string_t getStatus() const;
    bool statusIsSet() const;
    void unsetStatus();
    void setStatus(const utility::string_t& value);

    utility::string_t getNotes() const;
    bool notesIsSet() const;
    void unsetNotes();
    void setNotes(const utility::string_t& value);

    utility::string_t getSuggestedResponse() const;
    bool suggestedResponseIsSet() const;
    void unsetSuggested_response();
    void setSuggestedResponse(const utility::string_t& value);

    utility::string_t getSuggestedOpportunityType() const;
    bool suggestedOpportunityTypeIsSet() const;
    void unsetSuggested_opportunity_type();
    void setSuggestedOpportunityType(const utility::string_t& value);

    utility::string_t getAssignedToUuid() const;
    bool assignedToUuidIsSet() const;
    void unsetAssigned_to_uuid();
    void setAssignedToUuid(const utility::string_t& value);


protected:
    boost::optional<utility::string_t> m_Status;

    boost::optional<utility::string_t> m_Notes;

    boost::optional<utility::string_t> m_Suggested_response;

    boost::optional<utility::string_t> m_Suggested_opportunity_type;

    boost::optional<utility::string_t> m_Assigned_to_uuid;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_ContactSubmissionUpdateSchema_H_ */
