/**
 * Cyberwave API
 * Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * DatasetHubFilesSchema.h
 *
 * Sibling paths from Hugging Face &#x60;&#x60;dataset_info&#x60;&#x60; (Hub file tree).
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_DatasetHubFilesSchema_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_DatasetHubFilesSchema_H_

#include <boost/optional.hpp>

#include "CppRestOpenAPIClient/ModelBase.h"

#include <cpprest/details/basic_types.h>
#include <vector>

namespace org {
namespace openapitools {
namespace client {
namespace model {



/// <summary>
/// Sibling paths from Hugging Face &#x60;&#x60;dataset_info&#x60;&#x60; (Hub file tree).
/// </summary>
class  DatasetHubFilesSchema
    : public ModelBase
{
public:
    DatasetHubFilesSchema();
    virtual ~DatasetHubFilesSchema();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// DatasetHubFilesSchema members


    utility::string_t getHfRepoId() const;
    bool hfRepoIdIsSet() const;
    void unsetHf_repo_id();
    void setHfRepoId(const utility::string_t& value);

    utility::string_t getHfRevision() const;
    bool hfRevisionIsSet() const;
    void unsetHf_revision();
    void setHfRevision(const utility::string_t& value);

    int32_t getTotal() const;
    bool totalIsSet() const;
    void unsetTotal();
    void setTotal(int32_t value);

    std::vector<utility::string_t> getFiles() const;
    bool filesIsSet() const;
    void unsetFiles();
    void setFiles(const std::vector<utility::string_t>& value);

    bool isTruncated() const;
    bool truncatedIsSet() const;
    void unsetTruncated();
    void setTruncated(bool value);


protected:
    utility::string_t m_Hf_repo_id;
    bool m_Hf_repo_idIsSet;

    utility::string_t m_Hf_revision;
    bool m_Hf_revisionIsSet;

    int32_t m_Total;
    bool m_TotalIsSet;

    std::vector<utility::string_t> m_Files;
    bool m_FilesIsSet;

    bool m_Truncated;
    bool m_TruncatedIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_DatasetHubFilesSchema_H_ */
