/**
 * Cyberwave API
 * Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * DatasetSchema.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_DatasetSchema_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_DatasetSchema_H_

#include <boost/optional.hpp>

#include "CppRestOpenAPIClient/ModelBase.h"

#include "CppRestOpenAPIClient/model/ProcessedDatasetSchema.h"
#include <cpprest/details/basic_types.h>
#include <map>
#include <vector>
#include "CppRestOpenAPIClient/AnyType.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

class ProcessedDatasetSchema;


class  DatasetSchema
    : public ModelBase
{
public:
    DatasetSchema();
    virtual ~DatasetSchema();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// DatasetSchema members


    utility::string_t getUuid() const;
    bool uuidIsSet() const;
    void unsetUuid();
    void setUuid(const utility::string_t& value);

    utility::string_t getName() const;
    bool nameIsSet() const;
    void unsetName();
    void setName(const utility::string_t& value);

    std::vector<utility::string_t> getEpisodes() const;
    bool episodesIsSet() const;
    void unsetEpisodes();
    void setEpisodes(const std::vector<utility::string_t>& value);

    std::map<utility::string_t, std::shared_ptr<AnyType>> getMetadata() const;
    bool metadataIsSet() const;
    void unsetMetadata();
    void setMetadata(const std::map<utility::string_t, std::shared_ptr<AnyType>>& value);

    std::vector<std::shared_ptr<ProcessedDatasetSchema>> getProcessedDatasets() const;
    bool processedDatasetsIsSet() const;
    void unsetProcessed_datasets();
    void setProcessedDatasets(const std::vector<std::shared_ptr<ProcessedDatasetSchema>>& value);

    utility::string_t getProcessingStatus() const;
    bool processingStatusIsSet() const;
    void unsetProcessing_status();
    void setProcessingStatus(const utility::string_t& value);

    bool isIsReady() const;
    bool isReadyIsSet() const;
    void unsetIs_ready();
    void setIsReady(bool value);

    bool isIsImported() const;
    bool isImportedIsSet() const;
    void unsetIs_imported();
    void setIsImported(bool value);

    utility::string_t getSource() const;
    bool sourceIsSet() const;
    void unsetSource();
    void setSource(const utility::string_t& value);

    utility::string_t getSourceFormat() const;
    bool sourceFormatIsSet() const;
    void unsetSource_format();
    void setSourceFormat(const utility::string_t& value);

    utility::string_t getSlug() const;
    bool slugIsSet() const;
    void unsetSlug();
    void setSlug(const utility::string_t& value);

    utility::string_t getVisibility() const;
    bool visibilityIsSet() const;
    void unsetVisibility();
    void setVisibility(const utility::string_t& value);

    int32_t getTotalEpisodes() const;
    bool totalEpisodesIsSet() const;
    void unsetTotal_episodes();
    void setTotalEpisodes(int32_t value);

    int32_t getProcessedEpisodes() const;
    bool processedEpisodesIsSet() const;
    void unsetProcessed_episodes();
    void setProcessedEpisodes(int32_t value);

    int32_t getFailedEpisodes() const;
    bool failedEpisodesIsSet() const;
    void unsetFailed_episodes();
    void setFailedEpisodes(int32_t value);

    std::vector<utility::string_t> getFailedEpisodeUuids() const;
    bool failedEpisodeUuidsIsSet() const;
    void unsetFailed_episode_uuids();
    void setFailedEpisodeUuids(const std::vector<utility::string_t>& value);

    std::vector<utility::string_t> getCameras() const;
    bool camerasIsSet() const;
    void unsetCameras();
    void setCameras(const std::vector<utility::string_t>& value);

    int32_t getFps() const;
    bool fpsIsSet() const;
    void unsetFps();
    void setFps(int32_t value);

    utility::string_t getRobotType() const;
    bool robotTypeIsSet() const;
    void unsetRobot_type();
    void setRobotType(const utility::string_t& value);

    int32_t getActionDim() const;
    bool actionDimIsSet() const;
    void unsetAction_dim();
    void setActionDim(int32_t value);

    int32_t getStateDim() const;
    bool stateDimIsSet() const;
    void unsetState_dim();
    void setStateDim(int32_t value);

    utility::datetime getCreatedAt() const;
    bool createdAtIsSet() const;
    void unsetCreated_at();
    void setCreatedAt(const utility::datetime& value);

    utility::datetime getUpdatedAt() const;
    bool updatedAtIsSet() const;
    void unsetUpdated_at();
    void setUpdatedAt(const utility::datetime& value);

    utility::string_t getCreatedBy() const;
    bool createdByIsSet() const;
    void unsetCreated_by();
    void setCreatedBy(const utility::string_t& value);

    utility::string_t getUpdatedBy() const;
    bool updatedByIsSet() const;
    void unsetUpdated_by();
    void setUpdatedBy(const utility::string_t& value);


protected:
    utility::string_t m_Uuid;
    bool m_UuidIsSet;

    boost::optional<utility::string_t> m_Name;

    std::vector<utility::string_t> m_Episodes;
    bool m_EpisodesIsSet;

    std::map<utility::string_t, std::shared_ptr<AnyType>> m_Metadata;
    bool m_MetadataIsSet;

    std::vector<std::shared_ptr<ProcessedDatasetSchema>> m_Processed_datasets;
    bool m_Processed_datasetsIsSet;

    utility::string_t m_Processing_status;
    bool m_Processing_statusIsSet;

    bool m_Is_ready;
    bool m_Is_readyIsSet;

    bool m_Is_imported;
    bool m_Is_importedIsSet;

    boost::optional<utility::string_t> m_Source;

    boost::optional<utility::string_t> m_Source_format;

    boost::optional<utility::string_t> m_Slug;

    utility::string_t m_Visibility;
    bool m_VisibilityIsSet;

    int32_t m_Total_episodes;
    bool m_Total_episodesIsSet;

    int32_t m_Processed_episodes;
    bool m_Processed_episodesIsSet;

    int32_t m_Failed_episodes;
    bool m_Failed_episodesIsSet;

    std::vector<utility::string_t> m_Failed_episode_uuids;
    bool m_Failed_episode_uuidsIsSet;

    boost::optional<std::vector<utility::string_t>> m_Cameras;

    boost::optional<int32_t> m_Fps;

    boost::optional<utility::string_t> m_Robot_type;

    boost::optional<int32_t> m_Action_dim;

    boost::optional<int32_t> m_State_dim;

    utility::datetime m_Created_at;
    bool m_Created_atIsSet;

    utility::datetime m_Updated_at;
    bool m_Updated_atIsSet;

    boost::optional<utility::string_t> m_Created_by;

    boost::optional<utility::string_t> m_Updated_by;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_DatasetSchema_H_ */
