/**
 * Cyberwave API
 * Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.21.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * EnvironmentNavigationSettingsPatchSchema.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_EnvironmentNavigationSettingsPatchSchema_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_EnvironmentNavigationSettingsPatchSchema_H_

#include <boost/optional.hpp>

#include "CppRestOpenAPIClient/ModelBase.h"

#include <map>
#include "CppRestOpenAPIClient/AnyType.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



class  EnvironmentNavigationSettingsPatchSchema
    : public ModelBase
{
public:
    EnvironmentNavigationSettingsPatchSchema();
    virtual ~EnvironmentNavigationSettingsPatchSchema();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// EnvironmentNavigationSettingsPatchSchema members


    std::map<utility::string_t, std::shared_ptr<AnyType>> getNavigation() const;
    bool navigationIsSet() const;
    void unsetNavigation();
    void setNavigation(const std::map<utility::string_t, std::shared_ptr<AnyType>>& value);


protected:
    std::map<utility::string_t, std::shared_ptr<AnyType>> m_Navigation;
    bool m_NavigationIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_EnvironmentNavigationSettingsPatchSchema_H_ */
