/**
 * Cyberwave API
 * Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.26.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * EnvironmentAgentInteractionIntent.h
 *
 * UI/orchestrator-provided scope for an environment-agent interaction.  These values describe where the interaction started. They deliberately do not try to classify the user&#39;s words into a specific action.
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_EnvironmentAgentInteractionIntent_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_EnvironmentAgentInteractionIntent_H_

#include <boost/optional.hpp>

#include "CppRestOpenAPIClient/ModelBase.h"


namespace org {
namespace openapitools {
namespace client {
namespace model {


class  EnvironmentAgentInteractionIntent
    : public ModelBase
{
public:
    EnvironmentAgentInteractionIntent();
    EnvironmentAgentInteractionIntent(utility::string_t str);
    operator utility::string_t() const {
        return enumToStrMap.at(getValue());
    }


    virtual ~EnvironmentAgentInteractionIntent();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    enum class eEnvironmentAgentInteractionIntent
    {
        WORKFLOW_CONTEXT,
        ENVIRONMENT_SCENE,
        ENVIRONMENT_CLEANUP,
        ASSET_REVISION,
        ASSET_REVIEW,
    };

    eEnvironmentAgentInteractionIntent getValue() const;
    void setValue(eEnvironmentAgentInteractionIntent const value);

    protected:
        eEnvironmentAgentInteractionIntent m_value;
        std::map<eEnvironmentAgentInteractionIntent,utility::string_t> enumToStrMap = {
        { eEnvironmentAgentInteractionIntent::WORKFLOW_CONTEXT, _XPLATSTR("WORKFLOW_CONTEXT") },
        { eEnvironmentAgentInteractionIntent::ENVIRONMENT_SCENE, _XPLATSTR("ENVIRONMENT_SCENE") },
        { eEnvironmentAgentInteractionIntent::ENVIRONMENT_CLEANUP, _XPLATSTR("ENVIRONMENT_CLEANUP") },
        { eEnvironmentAgentInteractionIntent::ASSET_REVISION, _XPLATSTR("ASSET_REVISION") },
        { eEnvironmentAgentInteractionIntent::ASSET_REVIEW, _XPLATSTR("ASSET_REVIEW") }
};
        std::map<utility::string_t,eEnvironmentAgentInteractionIntent> strToEnumMap = {
        { _XPLATSTR("WORKFLOW_CONTEXT"), eEnvironmentAgentInteractionIntent::WORKFLOW_CONTEXT },
        { _XPLATSTR("ENVIRONMENT_SCENE"), eEnvironmentAgentInteractionIntent::ENVIRONMENT_SCENE },
        { _XPLATSTR("ENVIRONMENT_CLEANUP"), eEnvironmentAgentInteractionIntent::ENVIRONMENT_CLEANUP },
        { _XPLATSTR("ASSET_REVISION"), eEnvironmentAgentInteractionIntent::ASSET_REVISION },
        { _XPLATSTR("ASSET_REVIEW"), eEnvironmentAgentInteractionIntent::ASSET_REVIEW }
};

};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_EnvironmentAgentInteractionIntent_H_ */
