/**
 * Cyberwave API
 * Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.21.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OpportunityUpdateSchema.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_OpportunityUpdateSchema_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_OpportunityUpdateSchema_H_

#include <boost/optional.hpp>

#include "CppRestOpenAPIClient/ModelBase.h"

#include "CppRestOpenAPIClient/model/Value.h"
#include <cpprest/details/basic_types.h>
#include <map>
#include "CppRestOpenAPIClient/AnyType.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



class  OpportunityUpdateSchema
    : public ModelBase
{
public:
    OpportunityUpdateSchema();
    virtual ~OpportunityUpdateSchema();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// OpportunityUpdateSchema members


    utility::string_t getName() const;
    bool nameIsSet() const;
    void unsetName();
    void setName(const utility::string_t& value);

    utility::string_t getDescription() const;
    bool descriptionIsSet() const;
    void unsetDescription();
    void setDescription(const utility::string_t& value);

    utility::string_t getOpportunityType() const;
    bool opportunityTypeIsSet() const;
    void unsetOpportunity_type();
    void setOpportunityType(const utility::string_t& value);

    utility::string_t getStage() const;
    bool stageIsSet() const;
    void unsetStage();
    void setStage(const utility::string_t& value);

    std::shared_ptr<Value> getValue() const;
    bool valueIsSet() const;
    void unsetValue();
    void setValue(const std::shared_ptr<Value>& value);

    utility::string_t getContactName() const;
    bool contactNameIsSet() const;
    void unsetContact_name();
    void setContactName(const utility::string_t& value);

    utility::string_t getContactEmail() const;
    bool contactEmailIsSet() const;
    void unsetContact_email();
    void setContactEmail(const utility::string_t& value);

    utility::string_t getCompanyName() const;
    bool companyNameIsSet() const;
    void unsetCompany_name();
    void setCompanyName(const utility::string_t& value);

    utility::string_t getExpectedCloseDate() const;
    bool expectedCloseDateIsSet() const;
    void unsetExpected_close_date();
    void setExpectedCloseDate(const utility::string_t& value);

    utility::string_t getNotes() const;
    bool notesIsSet() const;
    void unsetNotes();
    void setNotes(const utility::string_t& value);

    std::map<utility::string_t, std::shared_ptr<AnyType>> getMetadata() const;
    bool metadataIsSet() const;
    void unsetMetadata();
    void setMetadata(const std::map<utility::string_t, std::shared_ptr<AnyType>>& value);

    int32_t getYear() const;
    bool yearIsSet() const;
    void unsetYear();
    void setYear(int32_t value);

    bool isIsArchived() const;
    bool isArchivedIsSet() const;
    void unsetIs_archived();
    void setIsArchived(bool value);

    int32_t getSortOrder() const;
    bool sortOrderIsSet() const;
    void unsetSort_order();
    void setSortOrder(int32_t value);

    utility::string_t getWorkspaceUuid() const;
    bool workspaceUuidIsSet() const;
    void unsetWorkspace_uuid();
    void setWorkspaceUuid(const utility::string_t& value);

    utility::string_t getAssignedToUuid() const;
    bool assignedToUuidIsSet() const;
    void unsetAssigned_to_uuid();
    void setAssignedToUuid(const utility::string_t& value);


protected:
    boost::optional<utility::string_t> m_Name;

    boost::optional<utility::string_t> m_Description;

    boost::optional<utility::string_t> m_Opportunity_type;

    boost::optional<utility::string_t> m_Stage;

    boost::optional<std::shared_ptr<Value>> m_Value;

    boost::optional<utility::string_t> m_Contact_name;

    boost::optional<utility::string_t> m_Contact_email;

    boost::optional<utility::string_t> m_Company_name;

    boost::optional<utility::string_t> m_Expected_close_date;

    boost::optional<utility::string_t> m_Notes;

    boost::optional<std::map<utility::string_t, std::shared_ptr<AnyType>>> m_Metadata;

    boost::optional<int32_t> m_Year;

    boost::optional<bool> m_Is_archived;

    boost::optional<int32_t> m_Sort_order;

    boost::optional<utility::string_t> m_Workspace_uuid;

    boost::optional<utility::string_t> m_Assigned_to_uuid;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_OpportunityUpdateSchema_H_ */
