/**
 * Cyberwave API
 * Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.26.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * PartnerIntegrationAuthenticationType.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_PartnerIntegrationAuthenticationType_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_PartnerIntegrationAuthenticationType_H_

#include <boost/optional.hpp>

#include "CppRestOpenAPIClient/ModelBase.h"


namespace org {
namespace openapitools {
namespace client {
namespace model {


class  PartnerIntegrationAuthenticationType
    : public ModelBase
{
public:
    PartnerIntegrationAuthenticationType();
    PartnerIntegrationAuthenticationType(utility::string_t str);
    operator utility::string_t() const {
        return enumToStrMap.at(getValue());
    }


    virtual ~PartnerIntegrationAuthenticationType();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    enum class ePartnerIntegrationAuthenticationType
    {
        SSO,
        OAUTH2,
        BASIC,
        API_KEY,
        OTHER,
    };

    ePartnerIntegrationAuthenticationType getValue() const;
    void setValue(ePartnerIntegrationAuthenticationType const value);

    protected:
        ePartnerIntegrationAuthenticationType m_value;
        std::map<ePartnerIntegrationAuthenticationType,utility::string_t> enumToStrMap = {
        { ePartnerIntegrationAuthenticationType::SSO, _XPLATSTR("SSO") },
        { ePartnerIntegrationAuthenticationType::OAUTH2, _XPLATSTR("OAUTH2") },
        { ePartnerIntegrationAuthenticationType::BASIC, _XPLATSTR("BASIC") },
        { ePartnerIntegrationAuthenticationType::API_KEY, _XPLATSTR("API_KEY") },
        { ePartnerIntegrationAuthenticationType::OTHER, _XPLATSTR("OTHER") }
};
        std::map<utility::string_t,ePartnerIntegrationAuthenticationType> strToEnumMap = {
        { _XPLATSTR("SSO"), ePartnerIntegrationAuthenticationType::SSO },
        { _XPLATSTR("OAUTH2"), ePartnerIntegrationAuthenticationType::OAUTH2 },
        { _XPLATSTR("BASIC"), ePartnerIntegrationAuthenticationType::BASIC },
        { _XPLATSTR("API_KEY"), ePartnerIntegrationAuthenticationType::API_KEY },
        { _XPLATSTR("OTHER"), ePartnerIntegrationAuthenticationType::OTHER }
};

};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_PartnerIntegrationAuthenticationType_H_ */
