/**
 * Cyberwave API
 * Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.26.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * PolicyJointBindingRequest.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_PolicyJointBindingRequest_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_PolicyJointBindingRequest_H_

#include <boost/optional.hpp>

#include "CppRestOpenAPIClient/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {



class  PolicyJointBindingRequest
    : public ModelBase
{
public:
    PolicyJointBindingRequest();
    virtual ~PolicyJointBindingRequest();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// PolicyJointBindingRequest members


    utility::string_t getPrompt() const;
    bool promptIsSet() const;
    void unsetPrompt();
    void setPrompt(const utility::string_t& value);

    utility::string_t getWorkspaceUuid() const;
    bool workspaceUuidIsSet() const;
    void unsetWorkspace_uuid();
    void setWorkspaceUuid(const utility::string_t& value);

    utility::string_t getPreviousBindingUuid() const;
    bool previousBindingUuidIsSet() const;
    void unsetPrevious_binding_uuid();
    void setPreviousBindingUuid(const utility::string_t& value);

    utility::string_t getAssetUuid() const;
    bool assetUuidIsSet() const;
    void unsetAsset_uuid();
    void setAssetUuid(const utility::string_t& value);

    utility::datetime getExpectedUpdatedAt() const;
    bool expectedUpdatedAtIsSet() const;
    void unsetExpected_updated_at();
    void setExpectedUpdatedAt(const utility::datetime& value);


protected:
    utility::string_t m_Prompt;
    bool m_PromptIsSet;

    boost::optional<utility::string_t> m_Workspace_uuid;

    boost::optional<utility::string_t> m_Previous_binding_uuid;

    utility::string_t m_Asset_uuid;
    bool m_Asset_uuidIsSet;

    utility::datetime m_Expected_updated_at;
    bool m_Expected_updated_atIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_PolicyJointBindingRequest_H_ */
