/**
 * Cyberwave API
 * Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ProceduralPrimitiveTemplateSchema.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_ProceduralPrimitiveTemplateSchema_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_ProceduralPrimitiveTemplateSchema_H_

#include <boost/optional.hpp>

#include "CppRestOpenAPIClient/ModelBase.h"

#include <cpprest/details/basic_types.h>
#include <map>
#include <vector>
#include "CppRestOpenAPIClient/AnyType.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



class  ProceduralPrimitiveTemplateSchema
    : public ModelBase
{
public:
    ProceduralPrimitiveTemplateSchema();
    virtual ~ProceduralPrimitiveTemplateSchema();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// ProceduralPrimitiveTemplateSchema members


    utility::string_t getKey() const;
    bool keyIsSet() const;
    void unsetKey();
    void setKey(const utility::string_t& value);

    utility::string_t getVersion() const;
    bool versionIsSet() const;
    void unsetVersion();
    void setVersion(const utility::string_t& value);

    utility::string_t getCategory() const;
    bool categoryIsSet() const;
    void unsetCategory();
    void setCategory(const utility::string_t& value);

    utility::string_t getName() const;
    bool nameIsSet() const;
    void unsetName();
    void setName(const utility::string_t& value);

    utility::string_t getDescription() const;
    bool descriptionIsSet() const;
    void unsetDescription();
    void setDescription(const utility::string_t& value);

    std::vector<utility::string_t> getKeywords() const;
    bool keywordsIsSet() const;
    void unsetKeywords();
    void setKeywords(const std::vector<utility::string_t>& value);

    std::vector<utility::string_t> getLegacyRegistryIds() const;
    bool legacyRegistryIdsIsSet() const;
    void unsetLegacy_registry_ids();
    void setLegacyRegistryIds(const std::vector<utility::string_t>& value);

    std::vector<utility::string_t> getAliases() const;
    bool aliasesIsSet() const;
    void unsetAliases();
    void setAliases(const std::vector<utility::string_t>& value);

    std::map<utility::string_t, std::shared_ptr<AnyType>> getGenerator() const;
    bool generatorIsSet() const;
    void unsetGenerator();
    void setGenerator(const std::map<utility::string_t, std::shared_ptr<AnyType>>& value);

    std::map<utility::string_t, std::shared_ptr<AnyType>> getCoordinateFrame() const;
    bool coordinateFrameIsSet() const;
    void unsetCoordinate_frame();
    void setCoordinateFrame(const std::map<utility::string_t, std::shared_ptr<AnyType>>& value);

    std::map<utility::string_t, std::shared_ptr<AnyType>> getParameterSchema() const;
    bool parameterSchemaIsSet() const;
    void unsetParameter_schema();
    void setParameterSchema(const std::map<utility::string_t, std::shared_ptr<AnyType>>& value);

    std::map<utility::string_t, std::shared_ptr<AnyType>> getParametersSchema() const;
    bool parametersSchemaIsSet() const;
    void unsetParameters_schema();
    void setParametersSchema(const std::map<utility::string_t, std::shared_ptr<AnyType>>& value);

    std::map<utility::string_t, std::shared_ptr<AnyType>> getDefaults() const;
    bool defaultsIsSet() const;
    void unsetDefaults();
    void setDefaults(const std::map<utility::string_t, std::shared_ptr<AnyType>>& value);

    std::vector<utility::string_t> getOutputs() const;
    bool outputsIsSet() const;
    void unsetOutputs();
    void setOutputs(const std::vector<utility::string_t>& value);

    std::map<utility::string_t, std::shared_ptr<AnyType>> getDerivedValues() const;
    bool derivedValuesIsSet() const;
    void unsetDerived_values();
    void setDerivedValues(const std::map<utility::string_t, std::shared_ptr<AnyType>>& value);

    std::map<utility::string_t, std::shared_ptr<AnyType>> getValidation() const;
    bool validationIsSet() const;
    void unsetValidation();
    void setValidation(const std::map<utility::string_t, std::shared_ptr<AnyType>>& value);

    std::vector<std::map<utility::string_t, std::shared_ptr<AnyType>>> getExamples() const;
    bool examplesIsSet() const;
    void unsetExamples();
    void setExamples(const std::vector<std::map<utility::string_t, std::shared_ptr<AnyType>>>& value);

    std::map<utility::string_t, std::shared_ptr<AnyType>> getMetadata() const;
    bool metadataIsSet() const;
    void unsetMetadata();
    void setMetadata(const std::map<utility::string_t, std::shared_ptr<AnyType>>& value);


protected:
    utility::string_t m_Key;
    bool m_KeyIsSet;

    utility::string_t m_Version;
    bool m_VersionIsSet;

    utility::string_t m_Category;
    bool m_CategoryIsSet;

    utility::string_t m_Name;
    bool m_NameIsSet;

    utility::string_t m_Description;
    bool m_DescriptionIsSet;

    std::vector<utility::string_t> m_Keywords;
    bool m_KeywordsIsSet;

    std::vector<utility::string_t> m_Legacy_registry_ids;
    bool m_Legacy_registry_idsIsSet;

    std::vector<utility::string_t> m_Aliases;
    bool m_AliasesIsSet;

    std::map<utility::string_t, std::shared_ptr<AnyType>> m_Generator;
    bool m_GeneratorIsSet;

    std::map<utility::string_t, std::shared_ptr<AnyType>> m_Coordinate_frame;
    bool m_Coordinate_frameIsSet;

    std::map<utility::string_t, std::shared_ptr<AnyType>> m_Parameter_schema;
    bool m_Parameter_schemaIsSet;

    std::map<utility::string_t, std::shared_ptr<AnyType>> m_Parameters_schema;
    bool m_Parameters_schemaIsSet;

    std::map<utility::string_t, std::shared_ptr<AnyType>> m_Defaults;
    bool m_DefaultsIsSet;

    std::vector<utility::string_t> m_Outputs;
    bool m_OutputsIsSet;

    std::map<utility::string_t, std::shared_ptr<AnyType>> m_Derived_values;
    bool m_Derived_valuesIsSet;

    std::map<utility::string_t, std::shared_ptr<AnyType>> m_Validation;
    bool m_ValidationIsSet;

    std::vector<std::map<utility::string_t, std::shared_ptr<AnyType>>> m_Examples;
    bool m_ExamplesIsSet;

    std::map<utility::string_t, std::shared_ptr<AnyType>> m_Metadata;
    bool m_MetadataIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_ProceduralPrimitiveTemplateSchema_H_ */
