/**
 * Cyberwave API
 * Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.24.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * RLTaskImportResultSchema.h
 *
 * Summary returned after importing a task ZIP into an RL task.
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_RLTaskImportResultSchema_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_RLTaskImportResultSchema_H_

#include <boost/optional.hpp>

#include "CppRestOpenAPIClient/ModelBase.h"

#include "CppRestOpenAPIClient/model/RLTaskSchema.h"
#include <cpprest/details/basic_types.h>
#include <vector>

namespace org {
namespace openapitools {
namespace client {
namespace model {

class RLTaskSchema;


/// <summary>
/// Summary returned after importing a task ZIP into an RL task.
/// </summary>
class  RLTaskImportResultSchema
    : public ModelBase
{
public:
    RLTaskImportResultSchema();
    virtual ~RLTaskImportResultSchema();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// RLTaskImportResultSchema members


    std::shared_ptr<RLTaskSchema> getRlTask() const;
    bool rlTaskIsSet() const;
    void unsetRl_task();
    void setRlTask(const std::shared_ptr<RLTaskSchema>& value);

    int32_t getFilesImported() const;
    bool filesImportedIsSet() const;
    void unsetFiles_imported();
    void setFilesImported(int32_t value);

    std::vector<utility::string_t> getFilesSkippedGenerated() const;
    bool filesSkippedGeneratedIsSet() const;
    void unsetFiles_skipped_generated();
    void setFilesSkippedGenerated(const std::vector<utility::string_t>& value);

    std::vector<utility::string_t> getWarnings() const;
    bool warningsIsSet() const;
    void unsetWarnings();
    void setWarnings(const std::vector<utility::string_t>& value);

    bool isReplacedExisting() const;
    bool replacedExistingIsSet() const;
    void unsetReplaced_existing();
    void setReplacedExisting(bool value);


protected:
    std::shared_ptr<RLTaskSchema> m_Rl_task;
    bool m_Rl_taskIsSet;

    int32_t m_Files_imported;
    bool m_Files_importedIsSet;

    std::vector<utility::string_t> m_Files_skipped_generated;
    bool m_Files_skipped_generatedIsSet;

    std::vector<utility::string_t> m_Warnings;
    bool m_WarningsIsSet;

    bool m_Replaced_existing;
    bool m_Replaced_existingIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_RLTaskImportResultSchema_H_ */
