/**
 * Cyberwave API
 * Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * RLTaskCheckpointSchema.h
 *
 * Output schema for one &#x60;&#x60;RLTaskCheckpoint&#x60;&#x60; row.
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_RLTaskCheckpointSchema_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_RLTaskCheckpointSchema_H_

#include <stdexcept>
#include <boost/optional.hpp>

#include "CppRestOpenAPIClient/ModelBase.h"

#include <cpprest/details/basic_types.h>
#include <map>
#include "CppRestOpenAPIClient/AnyType.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



/// <summary>
/// Output schema for one &#x60;&#x60;RLTaskCheckpoint&#x60;&#x60; row.
/// </summary>
class  RLTaskCheckpointSchema
    : public ModelBase
{
public:
    RLTaskCheckpointSchema();
    virtual ~RLTaskCheckpointSchema();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// RLTaskCheckpointSchema members

    enum class Runtime_targetEnum
    {
        CYBERWAVE_RL,
        CYBERWAVE_RL_EXPERIMENTAL,
    };
    enum class Runtime_acceleratorEnum
    {
        CPU,
        GPU,
    };

    Runtime_targetEnum toRuntime_targetEnum(const utility::string_t& value) const;
    const utility::string_t fromRuntime_targetEnum(const Runtime_targetEnum value) const;


    Runtime_acceleratorEnum toRuntime_acceleratorEnum(const utility::string_t& value) const;
    const utility::string_t fromRuntime_acceleratorEnum(const Runtime_acceleratorEnum value) const;


    utility::string_t getUuid() const;
    bool uuidIsSet() const;
    void unsetUuid();
    void setUuid(const utility::string_t& value);

    utility::string_t getRlTaskUuid() const;
    bool rlTaskUuidIsSet() const;
    void unsetRl_task_uuid();
    void setRlTaskUuid(const utility::string_t& value);

    utility::string_t getName() const;
    bool nameIsSet() const;
    void unsetName();
    void setName(const utility::string_t& value);

    utility::string_t getDescription() const;
    bool descriptionIsSet() const;
    void unsetDescription();
    void setDescription(const utility::string_t& value);

    utility::string_t getAttachmentUuid() const;
    bool attachmentUuidIsSet() const;
    void unsetAttachment_uuid();
    void setAttachmentUuid(const utility::string_t& value);

    utility::string_t getWeightsUrl() const;
    bool weightsUrlIsSet() const;
    void unsetWeights_url();
    void setWeightsUrl(const utility::string_t& value);

    Runtime_targetEnum getRuntimeTarget() const;
    bool runtimeTargetIsSet() const;
    void unsetRuntime_target();
    void setRuntimeTarget(const Runtime_targetEnum value);

    Runtime_acceleratorEnum getRuntimeAccelerator() const;
    bool runtimeAcceleratorIsSet() const;
    void unsetRuntime_accelerator();
    void setRuntimeAccelerator(const Runtime_acceleratorEnum value);

    std::map<utility::string_t, std::shared_ptr<AnyType>> getRuntimeVersions() const;
    bool runtimeVersionsIsSet() const;
    void unsetRuntime_versions();
    void setRuntimeVersions(const std::map<utility::string_t, std::shared_ptr<AnyType>>& value);

    std::map<utility::string_t, std::shared_ptr<AnyType>> getPolicyInterface() const;
    bool policyInterfaceIsSet() const;
    void unsetPolicy_interface();
    void setPolicyInterface(const std::map<utility::string_t, std::shared_ptr<AnyType>>& value);

    std::map<utility::string_t, std::shared_ptr<AnyType>> getMetadata() const;
    bool metadataIsSet() const;
    void unsetMetadata();
    void setMetadata(const std::map<utility::string_t, std::shared_ptr<AnyType>>& value);

    utility::datetime getCreatedAt() const;
    bool createdAtIsSet() const;
    void unsetCreated_at();
    void setCreatedAt(const utility::datetime& value);

    utility::datetime getUpdatedAt() const;
    bool updatedAtIsSet() const;
    void unsetUpdated_at();
    void setUpdatedAt(const utility::datetime& value);

    utility::string_t getCreatedByUuid() const;
    bool createdByUuidIsSet() const;
    void unsetCreated_by_uuid();
    void setCreatedByUuid(const utility::string_t& value);


protected:
    utility::string_t m_Uuid;
    bool m_UuidIsSet;

    utility::string_t m_Rl_task_uuid;
    bool m_Rl_task_uuidIsSet;

    utility::string_t m_Name;
    bool m_NameIsSet;

    utility::string_t m_Description;
    bool m_DescriptionIsSet;

    boost::optional<utility::string_t> m_Attachment_uuid;

    utility::string_t m_Weights_url;
    bool m_Weights_urlIsSet;

    Runtime_targetEnum m_Runtime_target;
    bool m_Runtime_targetIsSet;

    Runtime_acceleratorEnum m_Runtime_accelerator;
    bool m_Runtime_acceleratorIsSet;

    std::map<utility::string_t, std::shared_ptr<AnyType>> m_Runtime_versions;
    bool m_Runtime_versionsIsSet;

    std::map<utility::string_t, std::shared_ptr<AnyType>> m_Policy_interface;
    bool m_Policy_interfaceIsSet;

    std::map<utility::string_t, std::shared_ptr<AnyType>> m_Metadata;
    bool m_MetadataIsSet;

    utility::datetime m_Created_at;
    bool m_Created_atIsSet;

    utility::datetime m_Updated_at;
    bool m_Updated_atIsSet;

    boost::optional<utility::string_t> m_Created_by_uuid;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_RLTaskCheckpointSchema_H_ */
