/**
 * Cyberwave API
 * Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * TargetPoseSchema.h
 *
 * 6-DoF target pose for the end-effector.
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_TargetPoseSchema_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_TargetPoseSchema_H_

#include <boost/optional.hpp>

#include "CppRestOpenAPIClient/ModelBase.h"

#include <vector>

namespace org {
namespace openapitools {
namespace client {
namespace model {



/// <summary>
/// 6-DoF target pose for the end-effector.
/// </summary>
class  TargetPoseSchema
    : public ModelBase
{
public:
    TargetPoseSchema();
    virtual ~TargetPoseSchema();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// TargetPoseSchema members


    std::vector<double> getPosition() const;
    bool positionIsSet() const;
    void unsetPosition();
    void setPosition(std::vector<double> value);

    std::vector<double> getQuaternion() const;
    bool quaternionIsSet() const;
    void unsetQuaternion();
    void setQuaternion(std::vector<double> value);


protected:
    std::vector<double> m_Position;
    bool m_PositionIsSet;

    std::vector<double> m_Quaternion;
    bool m_QuaternionIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_TargetPoseSchema_H_ */
