/**
 * Cyberwave API
 * Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * TwinActionRequestSchema.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_TwinActionRequestSchema_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_TwinActionRequestSchema_H_

#include <stdexcept>
#include <boost/optional.hpp>

#include "CppRestOpenAPIClient/ModelBase.h"

#include <cpprest/details/basic_types.h>
#include <map>
#include "CppRestOpenAPIClient/model/MotionPlanSchema.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

class MotionPlanSchema;


class  TwinActionRequestSchema
    : public ModelBase
{
public:
    TwinActionRequestSchema();
    virtual ~TwinActionRequestSchema();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// TwinActionRequestSchema members

    enum class ExecutionEnum
    {
        ASYNC,
    };

    ExecutionEnum toExecutionEnum(const utility::string_t& value) const;
    const utility::string_t fromExecutionEnum(const ExecutionEnum value) const;


    utility::string_t getActionType() const;
    bool actionTypeIsSet() const;
    void unsetAction_type();
    void setActionType(const utility::string_t& value);

    utility::string_t getName() const;
    bool nameIsSet() const;
    void unsetName();
    void setName(const utility::string_t& value);

    std::shared_ptr<MotionPlanSchema> getPlan() const;
    bool planIsSet() const;
    void unsetPlan();
    void setPlan(const std::shared_ptr<MotionPlanSchema>& value);

    std::map<utility::string_t, double> getJoints() const;
    bool jointsIsSet() const;
    void unsetJoints();
    void setJoints(std::map<utility::string_t, double> value);

    utility::string_t getScope() const;
    bool scopeIsSet() const;
    void unsetScope();
    void setScope(const utility::string_t& value);

    utility::string_t getEnvironmentUuid() const;
    bool environmentUuidIsSet() const;
    void unsetEnvironment_uuid();
    void setEnvironmentUuid(const utility::string_t& value);

    ExecutionEnum getExecution() const;
    bool executionIsSet() const;
    void unsetExecution();
    void setExecution(const ExecutionEnum value);

    bool isPreview() const;
    bool previewIsSet() const;
    void unsetPreview();
    void setPreview(bool value);

    utility::string_t getSourceType() const;
    bool sourceTypeIsSet() const;
    void unsetSource_type();
    void setSourceType(const utility::string_t& value);

    int32_t getTickMs() const;
    bool tickMsIsSet() const;
    void unsetTick_ms();
    void setTickMs(int32_t value);

    int32_t getTransitionMs() const;
    bool transitionMsIsSet() const;
    void unsetTransition_ms();
    void setTransitionMs(int32_t value);

    int32_t getHoldMs() const;
    bool holdMsIsSet() const;
    void unsetHold_ms();
    void setHoldMs(int32_t value);


protected:
    utility::string_t m_Action_type;
    bool m_Action_typeIsSet;

    boost::optional<utility::string_t> m_Name;

    boost::optional<std::shared_ptr<MotionPlanSchema>> m_Plan;

    boost::optional<std::map<utility::string_t, double>> m_Joints;

    utility::string_t m_Scope;
    bool m_ScopeIsSet;

    boost::optional<utility::string_t> m_Environment_uuid;

    ExecutionEnum m_Execution;
    bool m_ExecutionIsSet;

    bool m_Preview;
    bool m_PreviewIsSet;

    boost::optional<utility::string_t> m_Source_type;

    boost::optional<int32_t> m_Tick_ms;

    boost::optional<int32_t> m_Transition_ms;

    boost::optional<int32_t> m_Hold_ms;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_TwinActionRequestSchema_H_ */
